#!/usr/bin/env python3
"""AusMT positional-contract generator (ADR-001 contract package).

`contract/columns.json` is the ONE place the catalogue/sci/tf column ORDER is defined. This script
generates the language-specific constants both consumers read — the engine's `engine/extract/_contract.py`
and the portal's `portal/src/contract.js` — so a consumer can never silently lag the producer.

Usage:
  python contract/generate.py --write    # (re)write the generated files from columns.json
  python contract/generate.py --check    # CI gate: exit 1 if a generated file is out of sync

Both generated files are committed (like portal/config.js) and the `--check` mode is run in CI, so a
columns.json edit that forgets to regenerate — or a hand-edit of a generated file — fails the build.
Requires an explicit --write/--check argv: no-args or an unrecognised flag (e.g. --help) prints usage
and writes NOTHING, so a stray `--help` can never silently fall through to the write branch.

This module also carries MTCAT_VERSION, THE single machine-readable source of the MTCAT schema
version: the constant is the source, and the schema title merely DISPLAYS it and is verified
against it rather than being parsed as the source. `mtcat_schema_version()`
returns the constant after verifying the schema artifact's displayed title agrees, and this
generator propagates it into `_contract.py` the same way it propagates the column order: as a
generated constant, gated by `--check`, so an engine consumer cannot carry a version literal of
its own. SURVEY_METADATA_VERSION and survey_metadata_schema_version() do the same for the second
public contract (survey-metadata.json): the constant is the source, the schema title displays it,
and `_contract.py` gains the generated SURVEY_METADATA_SCHEMA_VERSION mirror. STATION_VERSION and
station_schema_version() do the same for the third (station.json), with STATION_SCHEMA_VERSION as its
generated mirror.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
import json

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent                                  # the ausmt monorepo root
SRC = HERE / "columns.json"
LIC_SRC = HERE / "licenses.json"                    # the licence instrument single source (like columns.json)
PROF_SRC = HERE / "attribution_profiles.json"       # the custodian attribution-profile single source (like licenses.json)
MTCAT_SRC = ROOT / "engine" / "schema" / "mtcat.schema.json"   # the MTCAT schema version's single source
# The survey-metadata schema artifact (the second public contract): its title DISPLAYS the version
# SURVEY_METADATA_VERSION below declares, and survey_metadata_schema_version() verifies the two agree.
SURVEY_METADATA_SRC = ROOT / "engine" / "schema" / "ausmt-survey-metadata.schema.json"
# The station schema artifact (the third public contract): same inversion again, the title DISPLAYS
# the version STATION_VERSION below declares and station_schema_version() verifies the two agree.
STATION_SRC = ROOT / "engine" / "schema" / "ausmt-station.schema.json"
PY_OUT = ROOT / "engine" / "extract" / "_contract.py"
JS_OUT = ROOT / "portal" / "src" / "contract.js"
BANNER = ("GENERATED by contract/generate.py from contract/columns.json, licenses.json and "
          "attribution_profiles.json: DO NOT EDIT.")
# The schema's self-identifying title: "MTCAT v<MAJOR>.<MINOR>: <what the document is>".
_TITLE_RE = re.compile(r"^MTCAT v(\d+\.\d+):")
# The survey-metadata schema's self-identifying title: "AusMT Survey Metadata <MAJOR>.<MINOR>[-draft]:
# <what the document is>". The optional -draft suffix is the 0.x display convention (the document's
# `version` literal and the $id segment carry the bare MAJOR.MINOR).
_SURVEY_METADATA_TITLE_RE = re.compile(r"^AusMT Survey Metadata (\d+\.\d+)(-draft)?:")
# The station schema's self-identifying title, by the same convention: "AusMT Station Metadata
# <MAJOR>.<MINOR>[-draft]: <what the document is>".
_STATION_TITLE_RE = re.compile(r"^AusMT Station Metadata (\d+\.\d+)(-draft)?:")

# THE single machine-readable source of the MTCAT schema version: the version source is a machine
# constant and the title is generated from it. Every surface that states a
# version derives from THIS constant: the schema artifact's title (verified below - the title
# DISPLAYS the version and mtcat_schema_version() refuses to run if it disagrees), the generated
# engine constant in engine/extract/_contract.py, the emitter's portal.version, gen_config's
# browser reflection (the portal footer chip), and the docs current-version display (pinned by
# engine/tests/test_mtcat_version_parity.py). To bump: change this constant, update the schema
# artifact's displayed title to match, then regenerate (`python contract/generate.py --write` and
# `python3 portal/tools/gen_config.py`).
MTCAT_VERSION = "2.0"

# THE single machine-readable source of the survey-metadata schema version (the second public
# contract, data/products/<survey_id>/survey-metadata.json; the same inversion as MTCAT_VERSION above:
# the constant is the source, the schema artifact's title displays it and is verified against it).
# Every surface that states this version derives from THIS constant: the schema title (verified by
# survey_metadata_schema_version()), the generated engine constant SURVEY_METADATA_SCHEMA_VERSION in
# engine/extract/_contract.py (the emitter's document `version` and the served schema route segment),
# the schema's own versioned $id and the docs current-version display (all pinned by
# engine/tests/test_survey_metadata_version_parity.py). To bump: change this constant, update the
# schema artifact's displayed title and $id to match, then regenerate (`python contract/generate.py
# --write`).
SURVEY_METADATA_VERSION = "0.1"

# THE single machine-readable source of the station schema version (the third public contract,
# data/products/<slug>/<station>/station.json; the same inversion as the two constants above). Every
# surface that states this version derives from THIS constant: the schema title (verified by
# station_schema_version()), the generated engine constant STATION_SCHEMA_VERSION in
# engine/extract/_contract.py (the emitter's document `version` and the served schema route segment),
# the schema's own versioned $id and the docs current-version display (all pinned by
# engine/tests/test_station_version_parity.py). To bump: change this constant, update the schema
# artifact's displayed title and $id to match, then regenerate (`python contract/generate.py --write`).
STATION_VERSION = "0.1"


def station_schema_version() -> str:
    """The station schema version: STATION_VERSION above, THE single source, cross-checked against the
    schema artifact's own displayed title before it is handed out (the same discipline as
    survey_metadata_schema_version(): a title that disagrees with the constant fails loudly here and in
    `--check`, so two version claims can never ship side by side)."""
    schema = json.loads(STATION_SRC.read_text(encoding="utf-8"))
    title = schema.get("title", "")
    m = _STATION_TITLE_RE.match(title)
    if not m:
        raise SystemExit(f"ERROR: {STATION_SRC} must display its version in its title as "
                         f'"AusMT Station Metadata <MAJOR>.<MINOR>[-draft]: ..."; got {title!r}')
    if m.group(1) != STATION_VERSION:
        raise SystemExit(f"ERROR: {STATION_SRC} displays version {m.group(1)!r} in its title, but the "
                         f"single-source STATION_VERSION constant in contract/generate.py is "
                         f"{STATION_VERSION!r}; update the title to display the constant (the constant "
                         f"is the source, the title is the display)")
    return STATION_VERSION


def survey_metadata_schema_version() -> str:
    """The survey-metadata schema version: SURVEY_METADATA_VERSION above, THE single source, cross-
    checked against the schema artifact's own displayed title before it is handed out (the same
    discipline as mtcat_schema_version(): a title that disagrees with the constant fails loudly here
    and in `--check`, so two version claims can never ship side by side)."""
    schema = json.loads(SURVEY_METADATA_SRC.read_text(encoding="utf-8"))
    title = schema.get("title", "")
    m = _SURVEY_METADATA_TITLE_RE.match(title)
    if not m:
        raise SystemExit(f"ERROR: {SURVEY_METADATA_SRC} must display its version in its title as "
                         f'"AusMT Survey Metadata <MAJOR>.<MINOR>[-draft]: ..."; got {title!r}')
    if m.group(1) != SURVEY_METADATA_VERSION:
        raise SystemExit(f"ERROR: {SURVEY_METADATA_SRC} displays version {m.group(1)!r} in its title, "
                         f"but the single-source SURVEY_METADATA_VERSION constant in contract/generate.py "
                         f"is {SURVEY_METADATA_VERSION!r}; update the title to display the constant (the "
                         f"constant is the source, the title is the display)")
    return SURVEY_METADATA_VERSION


def mtcat_schema_version() -> str:
    """The MTCAT schema version: MTCAT_VERSION above, THE single source of truth, cross-checked
    against the schema artifact's own displayed title before it is handed out.

    The schema title must NOT be parsed as the source: the machine-readable source is a constant a
    generator can propagate, and the title is a DISPLAY surface verified against it. The
    verification is what keeps the pin property:
    a schema whose title disagrees with the constant fails loudly here (and in `--check`, which
    calls this) rather than letting two version claims ship side by side. The result is also checked
    against the schema's own MAJOR.MINOR pattern for `portal.version`, so a malformed constant can
    never be stamped into every published document.
    """
    schema = json.loads(MTCAT_SRC.read_text(encoding="utf-8"))
    title = schema.get("title", "")
    m = _TITLE_RE.match(title)
    if not m:
        raise SystemExit(f"ERROR: {MTCAT_SRC} must display its version in its title as "
                         f'"MTCAT v<MAJOR>.<MINOR>: ..."; got {title!r}')
    if m.group(1) != MTCAT_VERSION:
        raise SystemExit(f"ERROR: {MTCAT_SRC} displays version {m.group(1)!r} in its title, but the "
                         f"single-source MTCAT_VERSION constant in contract/generate.py is "
                         f"{MTCAT_VERSION!r}; update the title to display the constant (the constant "
                         f"is the source, the title is the display)")
    pattern = schema["properties"]["portal"]["properties"]["version"]["pattern"]
    if not re.fullmatch(pattern, MTCAT_VERSION):
        raise SystemExit(f"ERROR: MTCAT_VERSION {MTCAT_VERSION!r} does not match the schema's own "
                         f"portal.version pattern /{pattern}/")
    return MTCAT_VERSION


def _load():
    d = json.loads(SRC.read_text(encoding="utf-8"))
    return d["catalogue"], d["sci"], d["tf"]


def _load_lic():
    # The licence allow-list/alias/url tables. Emitted verbatim into both generated files so the
    # engine's redistributable() gate and the validator's recognised-id gate read ONE source and cannot
    # drift. Keys ordered as authored in licenses.json (Python dicts + json preserve insertion order).
    d = json.loads(LIC_SRC.read_text(encoding="utf-8"))
    return {"redistributable": d["redistributable"], "recognised_only": d["recognised_only"],
            "aliases": d["aliases"], "urls": d["urls"]}


def _load_prof():
    # The custodian attribution-profile table. Emitted verbatim into both generated files so the
    # engine's license_instrument_text() and the portal's licenseInstrumentText() render one source and
    # cannot drift. Keys ordered as authored in attribution_profiles.json (insertion order preserved).
    d = json.loads(PROF_SRC.read_text(encoding="utf-8"))
    return d["profiles"]


def _py(cat, sci, tf, lic, prof, mtver, smver, stver):
    def arr(name, xs):
        return f"{name} = [{', '.join(repr(x) for x in xs)}]"
    return (
        "# " + BANNER + "\n"
        "# The authoritative positional column order of catalogue.json / sci.json / tf.json. Read BY\n"
        "# POSITION across the engine and the portal (see docs/docs/developer/data-files.md). APPEND,\n"
        "# never reorder. To change: edit contract/columns.json, then `python contract/generate.py`.\n\n"
        + arr("CATALOGUE_COLUMNS", cat) + "\n"
        + arr("SCI_COLUMNS", sci) + "\n"
        + arr("TF_COLUMNS", tf) + "\n\n"
        "# Licence instrument (single-sourced in contract/licenses.json): the redistribution allow-list\n"
        "# read by build_portal.redistributable(), plus recognised metadata-only ids, legacy aliases and\n"
        "# per-id deed URLs. Edit contract/licenses.json, then regenerate — never hand-edit here.\n"
        + f"LICENSES = {json.dumps(lic, indent=4)}\n\n"
        "# Custodian attribution profiles (single-sourced in contract/attribution_profiles.json): the\n"
        "# per-custodian required-attribution templates rendered by _license_text.license_instrument_text().\n"
        "# Edit contract/attribution_profiles.json, then regenerate — never hand-edit here.\n"
        + f"PROFILES = {json.dumps(prof, indent=4, ensure_ascii=False)}\n\n"
        "# The MTCAT schema version, generated from contract/generate.py's MTCAT_VERSION constant (THE\n"
        "# single source; the schema artifact's title DISPLAYS it and is verified against it). This is a\n"
        "# generated mirror so build_portal's emitter and config defaults hold no version literal of their\n"
        "# own. To bump: change MTCAT_VERSION and the schema's displayed title, then regenerate; never\n"
        "# hand-edit here.\n"
        + f"MTCAT_SCHEMA_VERSION = {mtver!r}\n\n"
        "# The survey-metadata schema version, generated from contract/generate.py's SURVEY_METADATA_VERSION\n"
        "# constant (THE single source; the schema artifact's title DISPLAYS it and is verified against it).\n"
        "# The emitter stamps this into every survey-metadata.json `version` and names the served schema\n"
        "# route segment from it; it holds no version literal of its own. Never hand-edit here.\n"
        + f"SURVEY_METADATA_SCHEMA_VERSION = {smver!r}\n\n"
        "# The station schema version, generated from contract/generate.py's STATION_VERSION constant\n"
        "# (THE single source; the schema artifact's title DISPLAYS it and is verified against it). The\n"
        "# emitter stamps this into every station.json `version` and names the served schema route\n"
        "# segment from it; it holds no version literal of its own. Never hand-edit here.\n"
        + f"STATION_SCHEMA_VERSION = {stver!r}\n"
    )


def _js(cat, sci, tf, lic, prof):
    def names(xs):
        return "[" + ", ".join(json.dumps(x) for x in xs) + "]"

    def idx(xs):
        return "{ " + ", ".join(f"{x}: {i}" for i, x in enumerate(xs)) + " }"
    return (
        "// " + BANNER + "\n"
        "// Reference a column by its NAMED index map (C / SC / T), never by a literal position, so a\n"
        "// reorder cannot silently mis-align a consumer.\n"
        f"var CAT_COLUMNS = {names(cat)};\n"
        f"var SCI_COLUMNS = {names(sci)};\n"
        f"var TF_COLUMNS  = {names(tf)};\n"
        f"var C  = {idx(cat)};\n"
        f"var SC = {idx(sci)};\n"
        f"var T  = {idx(tf)};\n"
        "// The licence instrument (single-sourced in contract/licenses.json): allow-list + aliases + deed\n"
        "// URLs. exports.js reads LICENSES.urls for the LICENSE.txt that travels in the bulk-download zip.\n"
        f"var LICENSES = {json.dumps(lic, indent=2)};\n"
        "// Custodian attribution profiles (single-sourced in contract/attribution_profiles.json):\n"
        "// exports.js licenseInstrumentText() reads PROFILES to render a source's required attribution.\n"
        f"var PROFILES = {json.dumps(prof, indent=2, ensure_ascii=False)};\n"
    )


def _parse_args(argv):
    # exit_on_error=False + a raising error handler: argparse's own --help still calls parser.exit()
    # (SystemExit), which is what we want to route to usage+exit(2) below WITHOUT falling through to
    # the write branch — the bug this replaces let *any* unrecognised argv (including --help) reach
    # the unconditional write at the bottom of the old main().
    p = argparse.ArgumentParser(prog="contract/generate.py", add_help=False,
        description="Generate _contract.py / contract.js from contract/columns.json.")
    p.add_argument("--check", action="store_true", help="CI gate: exit 1 if a generated file is out of sync; writes nothing")
    p.add_argument("--write", action="store_true", help="(re)write the generated files from columns.json")
    p.add_argument("-h", "--help", action="store_true", help="show this help message and write nothing")
    ns, unknown = p.parse_known_args(argv)
    if ns.help or unknown or not (ns.check or ns.write) or (ns.check and ns.write):
        p.print_usage(sys.stderr)
        return None
    return "check" if ns.check else "write"


def main(argv):
    mode = _parse_args(argv)
    if mode is None:
        return 2
    cat, sci, tf = _load()
    lic = _load_lic()
    prof = _load_prof()
    py = _py(cat, sci, tf, lic, prof, mtcat_schema_version(), survey_metadata_schema_version(),
             station_schema_version())
    js = _js(cat, sci, tf, lic, prof)
    if mode == "check":
        stale = [p.relative_to(ROOT) for p, want in ((PY_OUT, py), (JS_OUT, js))
                 if (p.read_text(encoding="utf-8") if p.exists() else None) != want]
        if stale:
            print("CONTRACT DRIFT — regenerate with `python contract/generate.py --write`. Stale: "
                  + ", ".join(str(p) for p in stale), file=sys.stderr)
            return 1
        print("contract: _contract.py and contract.js are in sync with columns.json / licenses.json / "
              "attribution_profiles.json / the MTCAT schema version / the survey-metadata schema version "
              "/ the station schema version")
        return 0
    PY_OUT.write_text(py, encoding="utf-8")
    JS_OUT.write_text(js, encoding="utf-8")
    print(f"wrote {PY_OUT.relative_to(ROOT)} and {JS_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
