#!/usr/bin/env python3
"""AusMT positional-contract generator (ADR-001 contract package).

`contract/columns.json` is the ONE place the catalogue/sci/tf column ORDER is defined. This script
generates the language-specific constants both consumers read — the engine's `engine/extract/_contract.py`
and the portal's `portal/src/contract.js` — so a consumer can never silently lag the producer.

Usage:
  python contract/generate.py --write    # (re)write the generated files from columns.json
  python contract/generate.py --check    # CI gate: exit 1 if a generated file is out of sync

Both generated files are committed (like portal/config.js) and the `--check` mode is run in CI, so a
columns.json edit that forgets to regenerate — or a hand-edit of a generated file — fails the build.
Requires an explicit --write/--check argv: no-args or an unrecognised flag (e.g. --help) prints usage
and writes NOTHING, so a stray `--help` can never silently fall through to the write branch.

This module also carries `mtcat_schema_version()`, the ONE parser of the MTCAT schema version. The
schema FILE is that version's single source of truth (see the function), and this generator propagates
it into `_contract.py` the same way it propagates the column order: as a generated constant, gated by
`--check`, so an engine consumer cannot carry a version literal of its own.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
import json

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent                                  # the ausmt monorepo root
SRC = HERE / "columns.json"
LIC_SRC = HERE / "licenses.json"                    # C6: the licence instrument single source (like columns.json)
PROF_SRC = HERE / "attribution_profiles.json"       # C46: the custodian attribution-profile single source (like licenses.json)
MTCAT_SRC = ROOT / "engine" / "schema" / "mtcat.schema.json"   # the MTCAT schema version's single source
PY_OUT = ROOT / "engine" / "extract" / "_contract.py"
JS_OUT = ROOT / "portal" / "src" / "contract.js"
BANNER = ("GENERATED by contract/generate.py from contract/columns.json + licenses.json + "
          "attribution_profiles.json — DO NOT EDIT.")
# The schema's self-identifying title: "MTCAT v<MAJOR>.<MINOR>: <what the document is>".
_TITLE_RE = re.compile(r"^MTCAT v(\d+\.\d+):")


def mtcat_schema_version() -> str:
    """The MTCAT schema version, read from the schema's own title. THE single source of truth.

    engine/schema/mtcat.schema.json is the artifact being versioned, so it is the artifact that gets to
    declare the version: `$id` is deliberately unversioned (docs/docs/reference/mtcat-schema.md argues
    a versioned identifier nobody serves is worse than none), which leaves `title` as the one place the
    number is written, and the reference page already tells harvesters to read it there. Every other
    site that needs the version derives it from here rather than repeating the literal: the emitter's
    portal block, load_portal_config's defaults, and gen_config's default for a config that omits the
    key. Four independent literals is what this replaces; three separate review rounds each found one
    more of them, which is what a value with four homes does.

    The parse is strict and the result is checked against the schema's own MAJOR.MINOR pattern for
    `portal.version`, so a rewritten title or a malformed version fails loudly here rather than
    stamping something plausible into every published document.
    """
    schema = json.loads(MTCAT_SRC.read_text(encoding="utf-8"))
    title = schema.get("title", "")
    m = _TITLE_RE.match(title)
    if not m:
        raise SystemExit(f"ERROR: {MTCAT_SRC} must declare its version in its title as "
                         f'"MTCAT v<MAJOR>.<MINOR>: ..."; got {title!r}')
    version = m.group(1)
    pattern = schema["properties"]["portal"]["properties"]["version"]["pattern"]
    if not re.fullmatch(pattern, version):
        raise SystemExit(f"ERROR: MTCAT schema version {version!r} read from the title does not match "
                         f"the schema's own portal.version pattern /{pattern}/")
    return version


def _load():
    d = json.loads(SRC.read_text(encoding="utf-8"))
    return d["catalogue"], d["sci"], d["tf"]


def _load_lic():
    # The licence allow-list/alias/url tables (C6). Emitted verbatim into both generated files so the
    # engine's redistributable() gate and the validator's recognised-id gate read ONE source and cannot
    # drift. Keys ordered as authored in licenses.json (Python dicts + json preserve insertion order).
    d = json.loads(LIC_SRC.read_text(encoding="utf-8"))
    return {"redistributable": d["redistributable"], "recognised_only": d["recognised_only"],
            "aliases": d["aliases"], "urls": d["urls"]}


def _load_prof():
    # The custodian attribution-profile table (C46). Emitted verbatim into both generated files so the
    # engine's license_instrument_text() and the portal's licenseInstrumentText() render one source and
    # cannot drift. Keys ordered as authored in attribution_profiles.json (insertion order preserved).
    d = json.loads(PROF_SRC.read_text(encoding="utf-8"))
    return d["profiles"]


def _py(cat, sci, tf, lic, prof, mtver):
    def arr(name, xs):
        return f"{name} = [{', '.join(repr(x) for x in xs)}]"
    return (
        "# " + BANNER + "\n"
        "# The authoritative positional column order of catalogue.json / sci.json / tf.json. Read BY\n"
        "# POSITION across the engine and the portal (see docs/docs/developer/data-files.md). APPEND,\n"
        "# never reorder. To change: edit contract/columns.json, then `python contract/generate.py`.\n\n"
        + arr("CATALOGUE_COLUMNS", cat) + "\n"
        + arr("SCI_COLUMNS", sci) + "\n"
        + arr("TF_COLUMNS", tf) + "\n\n"
        "# C6 licence instrument (single-sourced in contract/licenses.json): the redistribution allow-list\n"
        "# read by build_portal.redistributable(), plus recognised metadata-only ids, legacy aliases and\n"
        "# per-id deed URLs. Edit contract/licenses.json, then regenerate — never hand-edit here.\n"
        + f"LICENSES = {json.dumps(lic, indent=4)}\n\n"
        "# C46 custodian attribution profiles (single-sourced in contract/attribution_profiles.json): the\n"
        "# per-custodian required-attribution templates rendered by _license_text.license_instrument_text().\n"
        "# Edit contract/attribution_profiles.json, then regenerate — never hand-edit here.\n"
        + f"PROFILES = {json.dumps(prof, indent=4, ensure_ascii=False)}\n\n"
        "# The MTCAT schema version, read from engine/schema/mtcat.schema.json's own title by\n"
        "# contract/generate.py:mtcat_schema_version(). The schema file is the SINGLE SOURCE; this is a\n"
        "# generated mirror so build_portal's emitter and config defaults hold no version literal of their\n"
        "# own. To bump: edit the schema title, then regenerate; never hand-edit here.\n"
        + f"MTCAT_SCHEMA_VERSION = {mtver!r}\n"
    )


def _js(cat, sci, tf, lic, prof):
    def names(xs):
        return "[" + ", ".join(json.dumps(x) for x in xs) + "]"

    def idx(xs):
        return "{ " + ", ".join(f"{x}: {i}" for i, x in enumerate(xs)) + " }"
    return (
        "// " + BANNER + "\n"
        "// Positional column contract for catalogue / sci / tf. Reference columns by the NAMED index\n"
        "// maps (C / SC / T) — e.g. r[C.ausmt_id], sc[SC.dim], t[T.pt_az] — so a reorder in\n"
        "// contract/columns.json can't silently mis-align a consumer. See docs/docs/developer/data-files.md.\n"
        f"var CAT_COLUMNS = {names(cat)};\n"
        f"var SCI_COLUMNS = {names(sci)};\n"
        f"var TF_COLUMNS  = {names(tf)};\n"
        f"var C  = {idx(cat)};\n"
        f"var SC = {idx(sci)};\n"
        f"var T  = {idx(tf)};\n"
        "// C6 licence instrument (single-sourced in contract/licenses.json): allow-list + aliases + deed\n"
        "// URLs. exports.js reads LICENSES.urls for the LICENSE.txt that travels in the bulk-download zip.\n"
        f"var LICENSES = {json.dumps(lic, indent=2)};\n"
        "// C46 custodian attribution profiles (single-sourced in contract/attribution_profiles.json):\n"
        "// exports.js licenseInstrumentText() reads PROFILES to render a source's required attribution.\n"
        f"var PROFILES = {json.dumps(prof, indent=2, ensure_ascii=False)};\n"
    )


def _parse_args(argv):
    # exit_on_error=False + a raising error handler: argparse's own --help still calls parser.exit()
    # (SystemExit), which is what we want to route to usage+exit(2) below WITHOUT falling through to
    # the write branch — the bug this replaces let *any* unrecognised argv (including --help) reach
    # the unconditional write at the bottom of the old main().
    p = argparse.ArgumentParser(prog="contract/generate.py", add_help=False,
        description="Generate _contract.py / contract.js from contract/columns.json.")
    p.add_argument("--check", action="store_true", help="CI gate: exit 1 if a generated file is out of sync; writes nothing")
    p.add_argument("--write", action="store_true", help="(re)write the generated files from columns.json")
    p.add_argument("-h", "--help", action="store_true", help="show this help message and write nothing")
    ns, unknown = p.parse_known_args(argv)
    if ns.help or unknown or not (ns.check or ns.write) or (ns.check and ns.write):
        p.print_usage(sys.stderr)
        return None
    return "check" if ns.check else "write"


def main(argv):
    mode = _parse_args(argv)
    if mode is None:
        return 2
    cat, sci, tf = _load()
    lic = _load_lic()
    prof = _load_prof()
    py, js = _py(cat, sci, tf, lic, prof, mtcat_schema_version()), _js(cat, sci, tf, lic, prof)
    if mode == "check":
        stale = [p.relative_to(ROOT) for p, want in ((PY_OUT, py), (JS_OUT, js))
                 if (p.read_text(encoding="utf-8") if p.exists() else None) != want]
        if stale:
            print("CONTRACT DRIFT — regenerate with `python contract/generate.py --write`. Stale: "
                  + ", ".join(str(p) for p in stale), file=sys.stderr)
            return 1
        print("contract: _contract.py and contract.js are in sync with columns.json / licenses.json / "
              "attribution_profiles.json / the MTCAT schema version")
        return 0
    PY_OUT.write_text(py, encoding="utf-8")
    JS_OUT.write_text(js, encoding="utf-8")
    print(f"wrote {PY_OUT.relative_to(ROOT)} and {JS_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
