"""C34/D1+D3 — the gw-runner generates LICENSE.md + README.md into a submitted package at intake
(after safe-extract, before validation), fail-closed and non-destructive.

Each test states its failure criterion and tests an independent observable (real bytes on disk, the
REAL validator's report), never metadata self-consistency.

The engine's stdlib-only _license_text leaf (D2) is imported here the way the runner reaches it in
the stack-less lane: engine/extract on sys.path (the leaf pulls no heavy stack, so this needs no
mt_metadata). The runner's own _generate_intake_files uses the SAME import path.
"""
from __future__ import annotations

import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

# Make the engine's stdlib-only _license_text leaf importable (the runner's intake module reaches it
# via `from extract._license_text import ...`, falling back to the bare sibling name — this insert
# feeds that fallback in the local/gateway test lane where `extract` is not pip-installed).
_ENGINE_DIR = Path(__file__).resolve().parents[2] / "engine"
sys.path.insert(0, str(_ENGINE_DIR / "extract"))

from gateway.runner import intake  # noqa: E402
from gateway.runner import runner  # noqa: E402
from gateway.tests.conftest import require_validator_dir  # noqa: E402

_NOW = datetime(2026, 7, 7, 13, 30, tzinfo=timezone.utc)
_STAMP_PREFIX = "Generated by the AusMT gateway from the survey's declared metadata on"

# A structured (Prototype-20) survey with a recognised, redistributable licence + two EDIs. Enough
# for the real validator to reach a no-FAIL verdict once LICENSE.md/README.md are present.
_SURVEY_YAML = """\
schema_version: "0.2"
slug: intake-survey-2026
project_name: Intake Test Survey
version: 1.0.0
country: Australia
organisation:
  name: University of Example
abstract: >
  A two-station broadband deployment used to exercise intake file generation.
dates: { start: 2019, end: 2021 }
license: CC-BY-4.0
access:
  level: open
  embargo_until: null
"""


def _make_package(root: Path, *, survey_yaml: str = _SURVEY_YAML, n_edi: int = 2) -> Path:
    """Build an extracted-package-shaped folder <root>/<slug>/ with survey.yaml + n_edi EDIs, the
    layout safe_extract produces (package_dir/<slug>/...)."""
    pkg = root / "intake-survey-2026"
    (pkg / "transfer_functions" / "edi").mkdir(parents=True)
    (pkg / "survey.yaml").write_text(survey_yaml, encoding="utf-8")
    for i in range(n_edi):
        # A minimal but validator-clean EDI: coordinates in HEAD + a FREQ block (the real
        # validate_survey.py FAILs edi_parse otherwise), so the only structure signals in play are the
        # LICENSE.md/README.md presence WARNINGs this feature targets.
        (pkg / "transfer_functions" / "edi" / f"S{i:02d}.edi").write_text(
            ">HEAD\n  LAT=-30:08:45.2\n  LONG=136:58:12.0\n>END\n>FREQ ORDER=INC //1\n  1.0\n",
            encoding="utf-8")
    return pkg


# --------------------------------------------------------------------------------------------------
# D3 — generation into a package that lacks the files.
# --------------------------------------------------------------------------------------------------
def test_generates_both_files_with_stamp(tmp_path):
    # FAILS IF either file is missing after generation, or either lacks the machine stamp on its first
    # line. proven RED by disabling generation (return [] from generate_intake_files -> no files).
    pkg = _make_package(tmp_path)
    written = intake.generate_intake_files(pkg, now_utc=_NOW)
    assert written == ["LICENSE.md", "README.md"], written
    lic = (pkg / "LICENSE.md").read_text(encoding="utf-8")
    rdm = (pkg / "README.md").read_text(encoding="utf-8")
    assert lic.startswith(_STAMP_PREFIX), lic[:120]
    assert rdm.startswith(_STAMP_PREFIX), rdm[:120]
    assert "2026-07-07" in lic.splitlines()[0]
    assert "Replace via a metadata edit or resubmission." in lic.splitlines()[0]


def test_license_md_text_equals_engine_bundle_text(tmp_path):
    # Single-source proof (D2): the rights body inside LICENSE.md is the ENGINE's own
    # license_instrument_text output for the same id — so LICENSE.md and the bundle LICENSE.txt can
    # never carry divergent rights wording. FAILS IF intake stops delegating to _license_text.
    import _license_text as lt  # noqa: PLC0415
    pkg = _make_package(tmp_path)
    intake.generate_intake_files(pkg, now_utc=_NOW)
    lic = (pkg / "LICENSE.md").read_text(encoding="utf-8")
    # The engine's rights text for this survey (org name + citation year), the same call intake makes.
    expected_rights = lt.license_instrument_text("CC-BY-4.0", "University of Example", "2021")
    assert expected_rights in lic, lic
    assert "CC-BY-4.0" in lic and "creativecommons.org/licenses/by/4.0" in lic


def test_readme_carries_declared_metadata(tmp_path):
    # README skeleton (D3): name, organisation, dates, station count, licence, abstract, citation —
    # all from survey.yaml. FAILS IF a required field is dropped from the skeleton.
    pkg = _make_package(tmp_path, n_edi=2)
    intake.generate_intake_files(pkg, now_utc=_NOW)
    rdm = (pkg / "README.md").read_text(encoding="utf-8")
    assert "# Intake Test Survey" in rdm
    assert "University of Example" in rdm
    assert "2019–2021" in rdm
    assert "Stations: 2" in rdm
    assert "CC-BY-4.0" in rdm
    assert "broadband deployment" in rdm         # the abstract
    assert "## Citation" in rdm
    assert "(2021)" in rdm                        # citation year


# --------------------------------------------------------------------------------------------------
# D3 — fail-closed on an unrecognised licence: NO LICENSE.md (the WARNING stands), README still made.
# --------------------------------------------------------------------------------------------------
def test_unrecognised_license_generates_no_license_md(tmp_path):
    # FAILS IF a LICENSE.md is fabricated for a placeholder/typo licence. proven RED by weakening the
    # gate (recognised -> always True) which would write a LICENSE.md naming a bogus id.
    bad_yaml = _SURVEY_YAML.replace("license: CC-BY-4.0", "license: TBD by uploader")
    pkg = _make_package(tmp_path, survey_yaml=bad_yaml)
    written = intake.generate_intake_files(pkg, now_utc=_NOW)
    assert "LICENSE.md" not in written
    assert not (pkg / "LICENSE.md").exists(), "an unrecognised licence must NOT get a LICENSE.md"
    # README is still generated (it is not licence-gated) and states the raw declared licence.
    assert "README.md" in written
    assert (pkg / "README.md").exists()


def test_typo_license_generates_no_license_md(tmp_path):
    # The exact C6 typo hole, at intake: a single-char typo (letter O for zero) is NOT recognised.
    bad_yaml = _SURVEY_YAML.replace("license: CC-BY-4.0", "license: CC-BY-4.O")
    pkg = _make_package(tmp_path, survey_yaml=bad_yaml)
    written = intake.generate_intake_files(pkg, now_utc=_NOW)
    assert not (pkg / "LICENSE.md").exists(), written


def test_recognised_metadata_only_license_still_gets_license_md(tmp_path):
    # A recognised-but-metadata-only id ('ALL RIGHTS RESERVED') is NOT redistributable but IS
    # recognised, so it still gets a correct rights statement. FAILS IF the gate reused
    # `redistributable` (too narrow) instead of `recognised`.
    yaml_arr = _SURVEY_YAML.replace("license: CC-BY-4.0", "license: ALL RIGHTS RESERVED")
    pkg = _make_package(tmp_path, survey_yaml=yaml_arr)
    written = intake.generate_intake_files(pkg, now_utc=_NOW)
    assert "LICENSE.md" in written
    assert "ALL RIGHTS RESERVED" in (pkg / "LICENSE.md").read_text(encoding="utf-8")


# --------------------------------------------------------------------------------------------------
# D3 — never overwrite an existing file (byte-identity).
# --------------------------------------------------------------------------------------------------
def test_existing_files_are_never_overwritten(tmp_path):
    # FAILS IF generation clobbers a package's own LICENSE.md/README.md. proven RED by removing the
    # `if not path.exists()` guard, which would replace the submitter's bytes with the skeleton.
    pkg = _make_package(tmp_path)
    orig_lic = b"# The submitter's own hand-written LICENSE\nCustom terms.\n"
    orig_rdm = b"# The submitter's own README\nHand-written notes.\n"
    (pkg / "LICENSE.md").write_bytes(orig_lic)
    (pkg / "README.md").write_bytes(orig_rdm)
    written = intake.generate_intake_files(pkg, now_utc=_NOW)
    assert written == [], "nothing should be written when both files already exist"
    assert (pkg / "LICENSE.md").read_bytes() == orig_lic
    assert (pkg / "README.md").read_bytes() == orig_rdm


def test_one_existing_one_missing_only_generates_the_missing(tmp_path):
    # Mixed: an existing README is preserved byte-for-byte while a missing LICENSE.md is generated.
    pkg = _make_package(tmp_path)
    orig_rdm = b"# Submitter README, keep me\n"
    (pkg / "README.md").write_bytes(orig_rdm)
    written = intake.generate_intake_files(pkg, now_utc=_NOW)
    assert written == ["LICENSE.md"]
    assert (pkg / "README.md").read_bytes() == orig_rdm
    assert (pkg / "LICENSE.md").exists()


# --------------------------------------------------------------------------------------------------
# D3 — PII: generated content contains no submitter contact details (independent-observable grep).
# --------------------------------------------------------------------------------------------------
def test_generated_files_contain_no_pii(tmp_path):
    # The runner never sees the DB's submitter fields (a job carries only ids + paths), and intake
    # reads ONLY survey.yaml. Even so, pin it: put canary PII in the survey.yaml's OWN metadata-
    # adjacent-but-non-generated fields and assert none of it reaches the generated bytes. FAILS IF a
    # future skeleton starts echoing a contact/email/orcid field.
    pii_email = "submitter-canary@example.test"
    pii_orcid = "0000-0002-1825-0097"
    yaml_pii = _SURVEY_YAML + (
        f"submitter_email: {pii_email}\n"        # not a real schema field, but a hostile/legacy file could carry it
        f"lead_investigator:\n  name: Private Person\n  orcid: {pii_orcid}\n"
    )
    pkg = _make_package(tmp_path, survey_yaml=yaml_pii)
    intake.generate_intake_files(pkg, now_utc=_NOW)
    for fname in ("LICENSE.md", "README.md"):
        body = (pkg / fname).read_text(encoding="utf-8")
        assert pii_email not in body, f"{fname} leaked a submitter email"
        assert pii_orcid not in body, f"{fname} leaked an ORCID"
        assert "Private Person" not in body, f"{fname} leaked an investigator name"


# --------------------------------------------------------------------------------------------------
# Robustness — generation is best-effort and never raises on bad input.
# --------------------------------------------------------------------------------------------------
def test_missing_survey_yaml_generates_nothing(tmp_path):
    pkg = tmp_path / "no-yaml"
    (pkg / "transfer_functions" / "edi").mkdir(parents=True)
    assert intake.generate_intake_files(pkg, now_utc=_NOW) == []
    assert not (pkg / "LICENSE.md").exists() and not (pkg / "README.md").exists()


def test_unparseable_survey_yaml_generates_nothing(tmp_path):
    pkg = tmp_path / "bad-yaml"
    pkg.mkdir()
    (pkg / "survey.yaml").write_text("this: : : not valid yaml: [", encoding="utf-8")
    assert intake.generate_intake_files(pkg, now_utc=_NOW) == []


def test_runner_generate_intake_files_never_raises(tmp_path, monkeypatch):
    # runner._generate_intake_files is best-effort: if intake blows up, it returns [] (never
    # propagates) so a valid package is not wrongly quarantined. FAILS IF the swallow is removed.
    def boom(*_a, **_k):
        raise RuntimeError("simulated intake failure")

    monkeypatch.setattr(intake, "generate_intake_files", boom)
    # A single-package layout so _single_package_root resolves.
    _make_package(tmp_path)
    assert runner._generate_intake_files(tmp_path) == []


# --------------------------------------------------------------------------------------------------
# D1 — end-to-end through the REAL validator: the two structure WARNINGs flip to PASS in one run.
# --------------------------------------------------------------------------------------------------
def _run_real_validator(validator_dir: Path, package_root: Path, out_json: Path) -> dict:
    import json
    validator_file = validator_dir / "validate_survey.py"
    subprocess.run([sys.executable, str(validator_file), str(package_root), "--json", str(out_json)],
                   capture_output=True, text=True)
    return json.loads(out_json.read_text(encoding="utf-8"))


def _structure_levels(report: dict, needle: str) -> list[str]:
    return [str(i.get("level")).upper() for i in report.get("items", [])
            if i.get("check") == "structure" and needle in str(i.get("message", ""))]


def test_real_validator_structure_warnings_flip_to_pass(tmp_path):
    # NO MOCKS: the REAL validate_survey.py (sibling or committed vendored). BEFORE generation the
    # validator WARNs 'LICENSE.md missing' + 'README.md missing'; AFTER generation both are PASS — in
    # the same package the runner would hand it. This is the D1 property: the generated files are
    # visible to the validator in the same run. FAILS IF generation stops running before validation,
    # or the validator no longer sees the generated files.
    validator_dir = require_validator_dir()
    pkg = _make_package(tmp_path)

    before = _run_real_validator(validator_dir, pkg, tmp_path / "before.json")
    lic_before = _structure_levels(before, "LICENSE.md")
    rdm_before = _structure_levels(before, "README.md")
    assert lic_before == ["WARNING"], before
    assert rdm_before == ["WARNING"], before

    written = intake.generate_intake_files(pkg, now_utc=_NOW)
    assert set(written) == {"LICENSE.md", "README.md"}, written

    after = _run_real_validator(validator_dir, pkg, tmp_path / "after.json")
    assert _structure_levels(after, "LICENSE.md") == ["PASS"], after
    assert _structure_levels(after, "README.md") == ["PASS"], after
    # And no NEW FAIL was introduced by the generated content.
    fails_after = [i for i in after.get("items", []) if str(i.get("level")).upper() in ("FAIL", "ERROR")]
    assert not fails_after, fails_after


def test_process_job_generates_files_before_validation(tmp_path, monkeypatch):
    # End-to-end through the runner's process_job with the validator + engine STUBBED: assert that by
    # the time the validator subprocess is invoked, the package on disk already carries the generated
    # LICENSE.md + README.md (generation ran BEFORE validation in _do_work). FAILS IF the generation
    # call is moved after the validator, or dropped.
    import io
    import json
    import zipfile
    from gateway import jobs

    # Build a real add-survey-shaped zip (single <slug>/ root) so safe_extract yields package/<slug>/.
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("intake-survey-2026/survey.yaml", _SURVEY_YAML)
        zf.writestr("intake-survey-2026/transfer_functions/edi/S00.edi",
                    ">HEAD\n  LAT=-30:08:45\n  LONG=136:58:12\n>END\n")
    sid = "01INTAKE"
    cfg = runner.RunnerConfig(
        incoming_dir=tmp_path / "incoming", quarantine_dir=tmp_path / "quarantine",
        jobs_dir=tmp_path / "jobs", validator_path=str(tmp_path / "validator"), timeout_s=900)
    jobs.ensure_dirs(cfg.jobs_dir)
    quarantine = cfg.quarantine_dir / sid
    zpath = cfg.incoming_dir / f"{sid}.zip"
    zpath.parent.mkdir(parents=True, exist_ok=True)
    zpath.write_bytes(buf.getvalue())
    running = cfg.jobs_dir / "running" / f"{sid}.json"
    running.write_text(json.dumps({
        "submission_id": sid, "zip_path": str(zpath), "quarantine_dir": str(quarantine),
    }), encoding="utf-8")

    seen_at_validation = {}

    def fake_sub(cmd, *, cwd, deadline):
        if any("validate_survey.py" in c for c in cmd):
            # Record whether the generated files exist on disk AT VALIDATION TIME.
            folder = Path(cmd[2])
            seen_at_validation["license"] = (folder / "LICENSE.md").exists()
            seen_at_validation["readme"] = (folder / "README.md").exists()
            (Path(cmd[4])).write_text(json.dumps(
                {"items": [{"level": "PASS", "check": "structure", "message": "LICENSE.md present"}]}),
                encoding="utf-8")
            return subprocess.CompletedProcess(cmd, 0, stdout="[PASS   ] structure ok", stderr="")
        # engine preview stub: write a catalogue so the summary is populated.
        out_dir = Path(cmd[cmd.index("--out") + 1])
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / "catalogue.json").write_text("[[\"s0\"]]", encoding="utf-8")
        return subprocess.CompletedProcess(cmd, 0, stdout="", stderr="")

    monkeypatch.setattr(runner, "_run_subprocess", fake_sub)
    runner.process_job(cfg, running)

    assert seen_at_validation.get("license") is True, "LICENSE.md not present when the validator ran"
    assert seen_at_validation.get("readme") is True, "README.md not present when the validator ran"
    # And they physically persist in the (curator-reviewed) package.
    pkg_root = quarantine / "package" / "intake-survey-2026"
    assert (pkg_root / "LICENSE.md").exists() and (pkg_root / "README.md").exists()
    payload = json.loads((cfg.jobs_dir / "done" / f"{sid}.json").read_text(encoding="utf-8"))
    assert payload["outcome"] == jobs.OUTCOME_VALIDATED, payload
