#!/usr/bin/env python3
"""Generate deploy/frontdoor/ts-routes.map, the front door's time-series hand-off table.

    "/go/ts/<survey>/<station>/<level>" "<percent-encoded NCI urlPath>"

one line per PROJECTED (survey, station, level), from the same per-survey verified-resource
registers `build_portal --ts-index` reads. The file is COMMITTED and Caddy `import`s it into a map
whose `default ""` is what 404s every path the table does not name.

    python deploy/scripts/gen_ts_routes.py --write    # (re)write the table from the registers
    python deploy/scripts/gen_ts_routes.py --check    # gate: exit 1 if the table is out of sync

An NCI urlPath cannot be derived from a route path (D15: the state segment is not in the id), so
resolution needs a lookup, and a committed one makes R5 membership greppable in review. Membership
is `_tsproject.route_rows()`, imported, never restated: the flag is projected for withheld
stations too (R13), so suppression lives here, in resolution, and the table renders from the same
predicate as ts_access.json - key sets equal by construction.

The survey serve verdict is the one restated seam (build_portal pulls the mt_metadata stack; see
`_survey_serves`); the key-set parity legs are the drift backstop. The registers live in the
sibling ausmt-surveys checkout, so `--check` runs pre-commit, on the box, and in gateway-ci; an
absent register root STOPS rather than passing vacuously.

A survey this reader cannot resolve drops ITS OWN routes only, recorded as an `# UNRESOLVED` line:
failing the whole generation left the previously committed table serving routes the build had
already suppressed.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent                  # deploy/scripts
ROOT = HERE.parents[1]                                  # the ausmt monorepo root
OUT_DEFAULT = ROOT / "deploy" / "frontdoor" / "ts-routes.map"
# The registers sit in the sibling surveys checkout, beside the monorepo root (the sibling rule
# gateway/tests/fixtures/sync_vendored_validator.py:31-34 already resolves the validator by).
SURVEYS_DEFAULT = ROOT.parent / "ausmt-surveys" / "surveys"

# The engine seams this table must not have a second opinion about. Both are stdlib-only modules;
# build_portal itself is NOT imported (it pulls mt_metadata/mth5, which a deploy tool must not need).
sys.path.insert(0, str(ROOT / "engine" / "extract"))
import _coordaccess as coordacc      # noqa: E402  (the C42 per-station coordinate gate)
import _stationcheck as stcheck      # noqa: E402  (the route prefix, the ENCODER, the encoded-route rule)
import _tsindex as tsindex           # noqa: E402  (the register reader and its closed vocabularies)
import _tsproject as tsproject       # noqa: E402  (THE projection: who gets a route)

BANNER = ("GENERATED by deploy/scripts/gen_ts_routes.py from the ausmt-surveys ts-index registers "
          "- DO NOT EDIT.")
# What build_portal.safe_component() leaves behind, which is what an ausmt_id and a served product
# path are made of. VERIFIED here rather than re-applied: sanitising a published id inside a
# redirect table would quietly mint a route under an identifier no build ever assigned.
_SAFE_SEGMENT = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")


class GenError(Exception):
    """The registers cannot be turned into a route table without guessing. Nothing is written."""


class _CorpusUnknown:
    """`known_ids` for a reader with no corpus: the published-id stop is the build's
    (build_portal.py:5064); the key-set parity leg catches a row the corpus does not publish."""

    def __contains__(self, _sid) -> bool:
        return True


def _survey_serves(access_block) -> bool:
    """The survey ACCESS half of the gate build_portal applies at :5187.

    Restated, not re-decided: access_serve_state (build_portal.py:241-281) serves ONLY
    `access.level: open`; metadata_only never serves, and an embargoed survey stays withheld
    whatever `embargo_until` says (a lapsed date does not auto-publish). An absent level is 'open'
    (the corpus predates the field); anything unrecognised is not 'open' and so fails closed."""
    raw = access_block.get("level") if isinstance(access_block, dict) else access_block
    level = str(raw).strip().lower() if raw not in (None, "") else "open"
    return (level or "open") == "open"


def _package_slug(pkgdir: Path, doc: dict) -> str:
    """The survey slug the ausmt_id is built from (build_portal.py:4425: the declared slug, else the
    package directory name). Verified against the safe-segment shape rather than sanitised."""
    slug = str(doc.get("slug") or pkgdir.name).strip()
    if not _SAFE_SEGMENT.match(slug) or ".." in slug:
        raise GenError(
            f"{pkgdir.name}: slug {slug!r} is not the shape build_portal.safe_component() emits, so "
            f"the route table cannot name it without rewriting a published id. Fix the slug.")
    return slug


def _target(pkgdir: Path, sid: str, level: str, url_path: str) -> str:
    """The map VALUE: url_path through _stationcheck's encoder (the one station.json's access_url
    uses) and held to the same encoded-route rule in BOTH directions, traversal refusal included -
    the module's predicates, never a second opinion."""
    # Neither refusal quotes the url_path: the row is already identified, and echoing an
    # unvalidated archive string into a file the front door imports buys nothing.
    if stcheck.ts_path_walks_up(url_path):
        raise GenError(f"{pkgdir.name}: {sid}/{level} url_path walks up out of the fileServer "
                       f"root; a route table is the last place to resolve that.")
    target = stcheck.ts_encode_path(url_path)
    if not stcheck._TS_ENCODED.match(target):
        raise GenError(f"{pkgdir.name}: {sid}/{level} url_path does not encode to a route "
                       f"{stcheck.TS_ACCESS_PREFIX} can serve")
    return target


def _reason(root, package, text) -> str:
    """A drop reason for the committed record: register root stripped (the string lands in a file
    `--check` byte-compares across checkouts) and the package prefix deduplicated."""
    out = str(text).replace(str(Path(root)) + "/", "").replace(str(Path(root)), ".")
    prefix = f"{package}: "
    return out[len(prefix):] if out.startswith(prefix) else out


def _survey_routes(root, pkgdir, doc) -> list:
    """[(map key, map value)] for ONE package. Raises GenError for anything this reader cannot
    resolve without guessing; the caller contains that to this survey."""
    access = doc.get("access")
    # The coordinate half of the gate, from the engine's own seam. A per-station OVERRIDE keys on the
    # record's BASE id, so this reader (which has no variant tag) resolves it through the module's
    # own CONSERVATIVE resolver: it masks every station the build masks and possibly one more, which
    # is the direction that can only drop a route, never keep one a withheld position needs gone.
    cdefault, coverrides = coordacc.parse_coordinate_policy(access)
    survey_open = _survey_serves(access)
    slug = _package_slug(pkgdir, doc)
    register = tsindex.load(root, pkgdir.name, _CorpusUnknown())
    out: list = []
    for sid in sorted(register):
        if not _SAFE_SEGMENT.match(sid) or ".." in sid:
            raise GenError(f"{pkgdir.name}: station id {sid!r} is not the shape a published "
                           f"ausmt_id carries; the register names a station this table cannot "
                           f"route without rewriting its id.")
        policy = coordacc.station_policy_by_published_id(cdefault, coverrides, sid)
        station_open = survey_open and coordacc.coordinates_served(policy)
        for level, entry in sorted(tsproject.route_rows(register[sid], station_open).items()):
            out.append((f"/go/ts/{slug}/{sid}/{level}",
                        _target(pkgdir, sid, level, entry["url_path"])))
    return out


def routes(surveys_root) -> tuple:
    """([(map key, map value)] sorted, {package: reason}) over every survey package.

    An unresolvable survey drops ITS OWN routes only (a dropped route 404s, the safe direction;
    raising out of the loop left the stale committed table serving suppressed routes). The drop is
    recorded in the committed file, so review sees it and `--check` reds when it changes. An ABSENT
    register root still stops everything: no input would make this check pass vacuously."""
    root = Path(surveys_root)
    if not root.is_dir():
        raise GenError(f"no survey packages at {root} (pass --surveys <ausmt-surveys>/surveys). The "
                       f"registers are the input; without them this check would pass vacuously.")
    import yaml  # noqa: PLC0415  (house style: local import where used; _tsindex needs it too)
    out: list = []
    unresolved: dict = {}
    for pkgdir in sorted(p for p in root.iterdir() if (p / "survey.yaml").is_file()):
        try:
            doc = yaml.safe_load((pkgdir / "survey.yaml").read_text(encoding="utf-8")) or {}
            if not isinstance(doc, dict):
                raise GenError(f"{pkgdir.name}: survey.yaml is not a mapping")
            out += _survey_routes(root, pkgdir, doc)
        except (GenError, tsindex.TsIndexError, coordacc.CoordinatePolicyError) as e:
            unresolved[pkgdir.name] = _reason(root, pkgdir.name, e)
        # Anything else - unparseable YAML, an unreadable file, a bug in this reader - is contained
        # the same way and named for what it is rather than guessed at, because a wrong reason in a
        # committed file sends the next operator to the wrong place.
        except Exception as e:                                                   # noqa: BLE001
            unresolved[pkgdir.name] = _reason(
                root, pkgdir.name, f"unresolvable ({type(e).__name__}: {e})")
    out.sort()
    return out, unresolved


def _reason_line(text) -> str:
    """A drop reason as a Caddyfile comment: one line, lexer-significant characters (braces, `$`,
    backtick) dropped rather than trusted inside a comment, truncated (stderr carries the full
    message). The caller already stripped machine-specific paths for `--check` byte-comparison."""
    flat = " ".join(str(text).split())
    safe = "".join(c for c in flat if c.isalnum() or c in " .,:;/_()[]'\"-")
    return safe[:240]


def render(rows, unresolved=None) -> str:
    """The committed file: banner, one UNRESOLVED comment per dropped survey, one `"key" "value"`
    line per route. No date (a churning header fails --check on quiet days) and no host (it lives
    once, in the Caddyfile's redir target). The UNRESOLVED lines are in the FILE because membership
    is the R5 decision: a change belongs in a human-readable diff and a `--check` that reds."""
    unresolved = unresolved or {}
    head = (f"# {BANNER}\n"
            f"# {len(rows)} route(s): open access + review:verified only (R5); level2 never routes "
            f"(D19).\n")
    for pkg in sorted(unresolved):
        head += f"# UNRESOLVED {pkg}: {_reason_line(unresolved[pkg])}\n"
    return head + "".join(f'"{key}" "{value}"\n' for key, value in rows)


def _parse_args(argv):
    """--check XOR --write, on contract/generate.py's precedent: no-args, --help or an unrecognised
    flag prints usage and writes NOTHING (a stray --help must never fall through to the write)."""
    p = argparse.ArgumentParser(prog="deploy/scripts/gen_ts_routes.py", add_help=False,
                                description="Generate deploy/frontdoor/ts-routes.map from the "
                                            "per-survey ts-index registers.")
    p.add_argument("--check", action="store_true",
                   help="gate: exit 1 if the committed table is out of sync; writes nothing")
    p.add_argument("--write", action="store_true", help="(re)write the table from the registers")
    p.add_argument("--surveys", default=str(SURVEYS_DEFAULT),
                   help="the survey-package root carrying <pkg>/ts-index.yaml (default: the sibling "
                        "ausmt-surveys checkout)")
    p.add_argument("--out", default=str(OUT_DEFAULT), help="the route table to write or check")
    p.add_argument("-h", "--help", action="store_true", help="show this help and write nothing")
    ns, unknown = p.parse_known_args(argv)
    if ns.help or unknown or not (ns.check or ns.write) or (ns.check and ns.write):
        p.print_usage(sys.stderr)
        return None
    return ns


def main(argv) -> int:
    ns = _parse_args(argv)
    if ns is None:
        return 2
    try:
        rows, unresolved = routes(ns.surveys)
    except GenError as e:
        print(f"gen_ts_routes: {e}", file=sys.stderr)
        return 2
    for pkg in sorted(unresolved):
        print(f"gen_ts_routes: WARNING: {pkg} DROPPED from the table - {unresolved[pkg]}",
              file=sys.stderr)
    if unresolved:
        print(f"gen_ts_routes: WARNING: {len(unresolved)} survey(s) publish NO hand-off routes in "
              f"this table. Every /go/ts/ path under them 404s, which is the safe direction, but "
              f"their hand-offs are OFFLINE until the cause is fixed.", file=sys.stderr)
    want = render(rows, unresolved)
    out = Path(ns.out)
    if ns.check:
        got = out.read_text(encoding="utf-8") if out.exists() else None
        if got != want:
            print(f"ROUTE-TABLE DRIFT - regenerate with `python deploy/scripts/gen_ts_routes.py "
                  f"--write`. {out} does not match the registers at {ns.surveys}. Until it does, a "
                  f"withheld station may still resolve and a published one may 404.", file=sys.stderr)
            return 1
        print(f"ts-routes: {out.name} is in sync with the registers ({len(rows)} route(s))")
        return 0
    out.write_text(want, encoding="utf-8")
    print(f"wrote {out} ({len(rows)} route(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
