#!/usr/bin/env python3
"""Generate deploy/frontdoor/ts-routes.map, the front door's time-series hand-off table.

    "/go/ts/<survey>/<station>/<level>" "<percent-encoded NCI urlPath>"

one line per PROJECTED (survey, station, level), from the same per-survey verified-resource
registers `build_portal --ts-index` reads. The file is COMMITTED and Caddy `import`s it into a map
whose `default ""` is what 404s every path the table does not name.

    python deploy/scripts/gen_ts_routes.py --write    # (re)write the table from the registers
    python deploy/scripts/gen_ts_routes.py --check    # gate: exit 1 if the table is out of sync

WHY A TABLE AT ALL (D15). Nothing in Caddy can derive an NCI `urlPath` from
`/go/ts/gawler/SA104A/level1_mth5`: the crawler stores the archive's own string verbatim precisely
because it cannot be rebuilt by joining catalog segments (musgraves' NT/SA/WA state segment is not
in the station id at all). So resolution needs a lookup, and a committed one makes the R5
membership greppable in review.

MEMBERSHIP IS `_tsproject.route_rows()`, IMPORTED, NEVER RESTATED. `has_time_series` is projected
for withheld stations too (existence semantics, R13), so mtcat.json hands an enumerator every
segment of one of these paths: suppression cannot live in discovery and must live in RESOLUTION.
This table IS that resolution, and it renders from the one predicate ts_access.json renders from,
which is what makes their key sets equal by construction rather than by coincidence.

THE ONE THING THIS READER DOES NOT SHARE WITH THE BUILD is the survey serve verdict, which lives in
build_portal (a module that pulls the whole mt_metadata stack). It is restated here as the two
lines it is - only `access.level: open` serves, and no embargo date ever opens a survey - with the
coordinate half of the gate imported from `_coordaccess` rather than restated. The key-set parity
leg in deploy/tests and doctor-box.sh is what proves the restatement has not drifted.

RUNS WHERE THE REGISTERS ARE: they live in the SIBLING ausmt-surveys checkout, so `--check` belongs
to the pre-commit battery (rule 7), to the box (where surveys-live is the sibling), and to
gateway-ci, which clones that sibling for exactly this gate. With no register root it STOPS rather
than reporting a vacuous pass.

A SURVEY THIS READER CANNOT RESOLVE DROPS ITS OWN ROUTES AND NOTHING ELSE'S, recorded in the table
as an `# UNRESOLVED` line. Failing the whole generation was worse than it looked: nothing was
written, so the PREVIOUSLY COMMITTED table went on serving while the build had already suppressed
the station, and suppression that cannot be published is not suppression.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent                  # deploy/scripts
ROOT = HERE.parents[1]                                  # the ausmt monorepo root
OUT_DEFAULT = ROOT / "deploy" / "frontdoor" / "ts-routes.map"
# The registers sit in the sibling surveys checkout, beside the monorepo root (the sibling rule
# gateway/tests/fixtures/sync_vendored_validator.py:31-34 already resolves the validator by).
SURVEYS_DEFAULT = ROOT.parent / "ausmt-surveys" / "surveys"

# The engine seams this table must not have a second opinion about. Both are stdlib-only modules;
# build_portal itself is NOT imported (it pulls mt_metadata/mth5, which a deploy tool must not need).
sys.path.insert(0, str(ROOT / "engine" / "extract"))
import _coordaccess as coordacc      # noqa: E402  (the C42 per-station coordinate gate)
import _stationcheck as stcheck      # noqa: E402  (the route prefix, the ENCODER, the encoded-route rule)
import _tsindex as tsindex           # noqa: E402  (the register reader and its closed vocabularies)
import _tsproject as tsproject       # noqa: E402  (THE projection: who gets a route)

BANNER = ("GENERATED by deploy/scripts/gen_ts_routes.py from the ausmt-surveys ts-index registers "
          "- DO NOT EDIT.")
# What build_portal.safe_component() leaves behind, which is what an ausmt_id and a served product
# path are made of. VERIFIED here rather than re-applied: sanitising a published id inside a
# redirect table would quietly mint a route under an identifier no build ever assigned.
_SAFE_SEGMENT = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")


class GenError(Exception):
    """The registers cannot be turned into a route table without guessing. Nothing is written."""


class _CorpusUnknown:
    """`known_ids` for a reader with no corpus. The stop that matches a register row to a PUBLISHED
    station id is the build's (build_portal.py:5064) and it is a hard error there; this table is
    generated from registers a build has already accepted, so it accepts the register's own keys and
    lets the key-set parity leg catch a row the corpus does not publish."""

    def __contains__(self, _sid) -> bool:
        return True


def _survey_serves(access_block) -> bool:
    """The survey ACCESS half of the gate build_portal applies at :5187.

    Restated, not re-decided: access_serve_state (build_portal.py:241-281) serves ONLY
    `access.level: open`; metadata_only never serves, and an embargoed survey stays withheld
    whatever `embargo_until` says (a lapsed date does not auto-publish). An absent level is 'open'
    (the corpus predates the field); anything unrecognised is not 'open' and so fails closed."""
    raw = access_block.get("level") if isinstance(access_block, dict) else access_block
    level = str(raw).strip().lower() if raw not in (None, "") else "open"
    return (level or "open") == "open"


def _package_slug(pkgdir: Path, doc: dict) -> str:
    """The survey slug the ausmt_id is built from (build_portal.py:4425: the declared slug, else the
    package directory name). Verified against the safe-segment shape rather than sanitised."""
    slug = str(doc.get("slug") or pkgdir.name).strip()
    if not _SAFE_SEGMENT.match(slug) or ".." in slug:
        raise GenError(
            f"{pkgdir.name}: slug {slug!r} is not the shape build_portal.safe_component() emits, so "
            f"the route table cannot name it without rewriting a published id. Fix the slug.")
    return slug


def _target(pkgdir: Path, sid: str, level: str, url_path: str) -> str:
    """The map VALUE: the register's url_path through the ONE encoder, which is _stationcheck's -
    the same call station.json's `access_url` is built from, so the front door's Location and the
    published route are the same string minus the host. Two `quote()` calls that agree today would
    diverge the day one learns about a character the other does not, and the failure is silent in
    the worst way: a working route in the record beside a 404 in the table, for one file. The result
    is then held to the SAME encoded-route rule _stationcheck applies to the published route, so a
    value this table admits is a value that gate admits - AND THE CONVERSE, which was the asymmetry
    worth naming: the traversal refusal below is that module's predicate, not a second opinion, so a
    string station.json is allowed to publish is a string this table can serve."""
    # Neither refusal quotes the offending url_path. The reason is recorded in the COMMITTED table,
    # and one (station, level) names one file, so the row is already identified; echoing an
    # unvalidated archive string into the file the front door imports buys nothing.
    if stcheck.ts_path_walks_up(url_path):
        raise GenError(f"{pkgdir.name}: {sid}/{level} url_path walks up out of the fileServer "
                       f"root; a route table is the last place to resolve that.")
    target = stcheck.ts_encode_path(url_path)
    if not stcheck._TS_ENCODED.match(target):
        raise GenError(f"{pkgdir.name}: {sid}/{level} url_path does not encode to a route "
                       f"{stcheck.TS_ACCESS_PREFIX} can serve")
    return target


def _relative(root, text) -> str:
    """A drop reason with the register root stripped. _tsindex names the file by its full path, and
    that path lands in a COMMITTED file `--check` byte-compares, so it has to be the same string on
    every checkout."""
    return str(text).replace(str(Path(root)) + "/", "").replace(str(Path(root)), ".")


def _survey_routes(root, pkgdir, doc) -> list:
    """[(map key, map value)] for ONE package. Raises GenError for anything this reader cannot
    resolve without guessing; the caller contains that to this survey."""
    access = doc.get("access")
    # The coordinate half of the gate, from the engine's own seam. A per-station OVERRIDE keys on the
    # record's BASE id, so this reader (which has no variant tag) resolves it through the module's
    # own CONSERVATIVE resolver: it masks every station the build masks and possibly one more, which
    # is the direction that can only drop a route, never keep one a withheld position needs gone.
    cdefault, coverrides = coordacc.parse_coordinate_policy(access)
    survey_open = _survey_serves(access)
    slug = _package_slug(pkgdir, doc)
    register = tsindex.load(root, pkgdir.name, _CorpusUnknown())
    out: list = []
    for sid in sorted(register):
        if not _SAFE_SEGMENT.match(sid) or ".." in sid:
            raise GenError(f"{pkgdir.name}: station id {sid!r} is not the shape a published "
                           f"ausmt_id carries; the register names a station this table cannot "
                           f"route without rewriting its id.")
        policy = coordacc.station_policy_by_published_id(cdefault, coverrides, sid)
        station_open = survey_open and coordacc.coordinates_served(policy)
        for level, entry in sorted(tsproject.route_rows(register[sid], station_open).items()):
            out.append((f"/go/ts/{slug}/{sid}/{level}",
                        _target(pkgdir, sid, level, entry["url_path"])))
    return out


def routes(surveys_root) -> tuple:
    """([(map key, map value)] sorted, {package: reason}) over every survey package.

    A SURVEY THIS READER CANNOT RESOLVE DROPS ITS OWN ROUTES AND NOTHING ELSE'S. Raising out of the
    loop was the wrong failure mode: main() then wrote nothing, so ONE unresolvable survey anywhere
    left the whole table un-regenerable while the previously committed one went on serving - a
    withheld flip suppressed in the data and still resolving at the edge, which is the exact leak
    this table exists to prevent. Dropping is the safe direction, because a route the table stops
    naming 404s; the only cost is a broken hand-off. The drop is not silent: it is recorded IN the
    committed file, so it shows in review, and `--check` reds the moment it changes.

    The one thing that still stops everything is an ABSENT register root: with no input at all this
    check would pass vacuously, and a vacuous pass is not a suppression decision."""
    root = Path(surveys_root)
    if not root.is_dir():
        raise GenError(f"no survey packages at {root} (pass --surveys <ausmt-surveys>/surveys). The "
                       f"registers are the input; without them this check would pass vacuously.")
    import yaml  # noqa: PLC0415  (house style: local import where used; _tsindex needs it too)
    out: list = []
    unresolved: dict = {}
    for pkgdir in sorted(p for p in root.iterdir() if (p / "survey.yaml").is_file()):
        try:
            doc = yaml.safe_load((pkgdir / "survey.yaml").read_text(encoding="utf-8")) or {}
            if not isinstance(doc, dict):
                raise GenError(f"{pkgdir.name}: survey.yaml is not a mapping")
            out += _survey_routes(root, pkgdir, doc)
        except (GenError, tsindex.TsIndexError, coordacc.CoordinatePolicyError) as e:
            unresolved[pkgdir.name] = _relative(root, e)
        except Exception as e:                                                   # noqa: BLE001
            unresolved[pkgdir.name] = _relative(
                root, f"survey.yaml is unreadable ({type(e).__name__}: {e})")
    out.sort()
    return out, unresolved


def _reason_line(text) -> str:
    """One drop reason as a Caddyfile comment: whitespace collapsed onto one line, and the characters
    a Caddyfile lexer gives meaning to (braces, `$`, backtick) dropped rather than trusted to stay
    inside a comment. Truncated, because the committed file records WHICH survey dropped and why in
    outline; the operator gets the full message on stderr.

    The caller has already made the text MACHINE-INDEPENDENT by stripping the register root: this
    string lands in a committed file that `--check` byte-compares, so an absolute path from whichever
    checkout generated it would red the gate on every other one."""
    flat = " ".join(str(text).split())
    safe = "".join(c for c in flat if c.isalnum() or c in " .,:;/_()[]'\"-")
    return safe[:240]


def render(rows, unresolved=None) -> str:
    """The committed file: a banner, one comment line per survey this reader could not resolve, then
    one `"key" "value"` line per route. No date and no host - a churning header would fail --check on
    a day nothing changed, and the host lives once, in the Caddyfile's redir target, so a map value
    can never name another one.

    The UNRESOLVED lines are the committed record of a survey whose routes were dropped. They are in
    the file rather than only on stderr for the reason the table itself is committed: membership IS
    the R5 decision, so a change to it belongs in a diff a human reads and in a `--check` that reds."""
    unresolved = unresolved or {}
    head = (f"# {BANNER}\n"
            f"# {len(rows)} route(s): open access + review:verified only (R5); level2 never routes "
            f"(D19).\n")
    for pkg in sorted(unresolved):
        head += f"# UNRESOLVED {pkg}: {_reason_line(unresolved[pkg])}\n"
    return head + "".join(f'"{key}" "{value}"\n' for key, value in rows)


def _parse_args(argv):
    """--check XOR --write, on contract/generate.py's precedent: no-args, --help or an unrecognised
    flag prints usage and writes NOTHING (a stray --help must never fall through to the write)."""
    p = argparse.ArgumentParser(prog="deploy/scripts/gen_ts_routes.py", add_help=False,
                                description="Generate deploy/frontdoor/ts-routes.map from the "
                                            "per-survey ts-index registers.")
    p.add_argument("--check", action="store_true",
                   help="gate: exit 1 if the committed table is out of sync; writes nothing")
    p.add_argument("--write", action="store_true", help="(re)write the table from the registers")
    p.add_argument("--surveys", default=str(SURVEYS_DEFAULT),
                   help="the survey-package root carrying <pkg>/ts-index.yaml (default: the sibling "
                        "ausmt-surveys checkout)")
    p.add_argument("--out", default=str(OUT_DEFAULT), help="the route table to write or check")
    p.add_argument("-h", "--help", action="store_true", help="show this help and write nothing")
    ns, unknown = p.parse_known_args(argv)
    if ns.help or unknown or not (ns.check or ns.write) or (ns.check and ns.write):
        p.print_usage(sys.stderr)
        return None
    return ns


def main(argv) -> int:
    ns = _parse_args(argv)
    if ns is None:
        return 2
    try:
        rows, unresolved = routes(ns.surveys)
    except GenError as e:
        print(f"gen_ts_routes: {e}", file=sys.stderr)
        return 2
    for pkg in sorted(unresolved):
        print(f"gen_ts_routes: WARNING: {pkg} DROPPED from the table - {unresolved[pkg]}",
              file=sys.stderr)
    if unresolved:
        print(f"gen_ts_routes: WARNING: {len(unresolved)} survey(s) publish NO hand-off routes in "
              f"this table. Every /go/ts/ path under them 404s, which is the safe direction, but "
              f"their hand-offs are OFFLINE until the cause is fixed.", file=sys.stderr)
    want = render(rows, unresolved)
    out = Path(ns.out)
    if ns.check:
        got = out.read_text(encoding="utf-8") if out.exists() else None
        if got != want:
            print(f"ROUTE-TABLE DRIFT - regenerate with `python deploy/scripts/gen_ts_routes.py "
                  f"--write`. {out} does not match the registers at {ns.surveys}. Until it does, a "
                  f"withheld station may still resolve and a published one may 404.", file=sys.stderr)
            return 1
        print(f"ts-routes: {out.name} is in sync with the registers ({len(rows)} route(s))")
        return 0
    out.write_text(want, encoding="utf-8")
    print(f"wrote {out} ({len(rows)} route(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
