"""Shared access to the vendored, self-contained test fixture so science unit tests do NOT depend on
a sibling ausmt-surveys checkout. Cross-repo integration is a separate, explicit concern."""
from pathlib import Path

FIXTURES = Path(__file__).resolve().parent / "fixtures"
EXAMPLE_SURVEY = FIXTURES / "example-survey"


def example_edis():
    return sorted((EXAMPLE_SURVEY / "transfer_functions" / "edi").glob("*.edi"))


def make_emtfxml_inputs(dest_dir, edis=None, survey_id="example-survey", survey_meta=None):
    """Write EMTF XML transfer functions into `dest_dir`, generated by THIS ENGINE's own emitter
    (ausmt_science.ingest.normalize) from the vendored example EDIs. Returns the sorted XML paths.

    Generated rather than committed on purpose: the emitter and the reader are the same mt_metadata
    build, so the fixture is self-consistent BY CONSTRUCTION and cannot drift into testing stale
    bytes when the pinned library moves. normalize() also writes a derived .edi beside each XML; it
    is removed here so the fixture directory holds EMTF XML and nothing else.

    Requires the mt_metadata stack (callers importorskip it, as the MTH5 input tests do)."""
    from ausmt_science.ingest.normalize import normalize  # noqa: PLC0415  (heavy stack; lazy)

    dest_dir = Path(dest_dir)
    dest_dir.mkdir(parents=True, exist_ok=True)
    for e in (edis if edis is not None else example_edis()):
        res = normalize(e, dest_dir, survey_id=survey_id, station_id=Path(e).stem,
                        survey_meta=survey_meta)
        Path(res.derived_edi).unlink(missing_ok=True)
    return sorted(dest_dir.glob("*.xml"))
