"""EMTF XML is a FIRST-CLASS submission input alongside EDI and MTH5 (owner ruling 2026-08-03), so a
station whose transfer function arrives only as EMTF XML must build and serve the FULL product set,
and a station that has both must resolve to its EDI.

Every test here runs the REAL build (build_portal.main over a package on disk) rather than asserting
on hand-built structures, and every EMTF XML fixture is generated by the engine's own emitter from
the vendored sample survey, so the ingest path is exercised against bytes this build actually writes.

Pre-fix (revert engine/extract/build_portal.py): transfer_functions/emtfxml/ is not enumerated at
all, so an XML-only package builds 0 stations and the build FAILS with rc 2 ("pipeline produced 0
stations") -- every test below goes red on that.
"""
import hashlib
import json
import re
import shutil
import sys
import zipfile
from pathlib import Path

import pytest

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(ROOT / "extract"))
sys.path.insert(0, str(ROOT))

pytest.importorskip("mt_metadata")

import build_portal as bp  # noqa: E402
from _fixtures import EXAMPLE_SURVEY, example_edis, make_emtfxml_inputs  # noqa: E402

SCHEMA = json.loads((ROOT / "schema" / "build_report.schema.json").read_text(encoding="utf-8"))
SLUG = "example-survey"


def _package(root, *, xml_stations=(), edi_stations=(), yaml_text=None, edi_filenames=None):
    """A survey package at <root>/<SLUG> carrying the named stations as EMTF XML and/or EDI. The XML
    is emitted by the engine's own writer from the matching sample EDI, so an 'A in both folders'
    package holds two renditions of ONE real station -- exactly the precedence case.

    `edi_filenames` files a station's EDI under a name of the caller's choosing. An EDI's filename
    carries no authority -- the build reads the station id from DATAID inside the file -- so a
    custodian file may legitimately be named for a different station than it holds."""
    pkg = root / SLUG
    (pkg).mkdir(parents=True, exist_ok=True)
    pkg.joinpath("survey.yaml").write_text(
        yaml_text if yaml_text is not None
        else (EXAMPLE_SURVEY / "survey.yaml").read_text(encoding="utf-8"), encoding="utf-8")
    by_stem = {p.stem: p for p in example_edis()}
    if edi_stations:
        d = pkg / "transfer_functions" / "edi"
        d.mkdir(parents=True, exist_ok=True)
        for s in edi_stations:
            shutil.copy(by_stem[s], d / (edi_filenames or {}).get(s, f"{s}.edi"))
    if xml_stations:
        make_emtfxml_inputs(pkg / "transfer_functions" / "emtfxml",
                            edis=[by_stem[s] for s in xml_stations], survey_id=SLUG)
    return pkg


def _build(tmp_path, surveys_root, extra=()):
    out, prod = tmp_path / "data", tmp_path / "products"
    rc = bp.main(["--surveys", str(surveys_root), "--out", str(out), "--products", str(prod),
                  "--bundle-edi", "--no-validate", *extra])
    return rc, out, prod


def _docs(out):
    return {name: json.loads((out / f"{name}.json").read_text(encoding="utf-8"))
            for name in ("catalogue", "manifest", "build_report", "build_provenance")}


def test_emtfxml_only_survey_builds_and_serves_the_full_product_set(tmp_path):
    """FAILS IF an XML-only survey does not build, or serves less than the full product set: the
    catalogue row, the per-station science products, the canonical re-emitted EMTF XML, a generated
    EDI (mt_metadata writes one from the same TF), the manifest rows for both formats, and membership
    in both per-survey bundles. This is the ruling's whole point -- 'so all formats are covered'."""
    _package(tmp_path / "surveys", xml_stations=("EXAMPLE01", "EXAMPLE02"))
    rc, out, prod = _build(tmp_path, tmp_path / "surveys")
    assert rc == 0, "an EMTF-XML-only survey must build"

    d = _docs(out)
    ids = {row[0] for row in d["catalogue"]}
    assert ids == {"EXAMPLE01", "EXAMPLE02"}, ids
    assert d["build_provenance"]["input_formats"] == ["emtfxml"], d["build_provenance"]["input_formats"]

    for st in ("EXAMPLE01", "EXAMPLE02"):
        assert (out / "xml" / SLUG / f"{st}.xml").is_file(), f"{st}: canonical EMTF XML served"
        assert (out / "edi" / SLUG / f"{st}.edi").is_file(), f"{st}: generated EDI served"
        sj = json.loads((prod / SLUG / st / "station.json").read_text(encoding="utf-8"))
        assert sj["distribution"]["edi_available"] is True, sj["distribution"]
        assert sj["distribution"]["edi_path"] == f"edi/{SLUG}/{st}.edi", sj["distribution"]
        # provenance stays honest about what was actually ingested
        assert sj["provenance"]["input_file"] == f"{st}.xml", sj["provenance"]
        assert sj["data"]["n_periods"] > 0, sj
        # the dimensionality CALL lives in dimensionality.json only — station.json stopped restating it
        dj = prod / SLUG / st / "dimensionality.json"
        assert dj.is_file()
        assert json.loads(dj.read_text(encoding="utf-8"))["classification"], dj

    rows = {(f["station"], f["format"]) for f in d["manifest"]["files"]}
    assert rows == {("EXAMPLE01", "edi"), ("EXAMPLE01", "emtfxml"),
                    ("EXAMPLE02", "edi"), ("EXAMPLE02", "emtfxml")}, rows
    assert {b["format"] for b in d["manifest"]["bundles"]} == {"edi-zip", "xml-zip"}, \
        d["manifest"]["bundles"]
    assert d["build_report"]["surveys"][SLUG]["ingest_sources"] == \
        {"EXAMPLE01": "emtfxml", "EXAMPLE02": "emtfxml"}


def test_emtfxml_input_matches_the_edi_input_it_was_written_from(tmp_path):
    """FAILS IF the XML path is not the SAME science pathway as the EDI path. The fixture XML is this
    engine's own rendering of the sample EDI, so ingesting either must yield the same station record
    and the same diagnostics -- any divergence is the ingest seam, not the data."""
    _package(tmp_path / "a", edi_stations=("EXAMPLE01", "EXAMPLE02"))
    _package(tmp_path / "b", xml_stations=("EXAMPLE01", "EXAMPLE02"))
    rc_a, out_a, _ = _build(tmp_path / "ra", tmp_path / "a")
    rc_b, out_b, _ = _build(tmp_path / "rb", tmp_path / "b")
    assert rc_a == 0 and rc_b == 0

    ka = {row[0]: row for row in json.loads((out_a / "catalogue.json").read_text(encoding="utf-8"))}
    kb = {row[0]: row for row in json.loads((out_b / "catalogue.json").read_text(encoding="utf-8"))}
    assert set(ka) == set(kb) and ka, "same station set from both inputs"
    for sid, a in ka.items():
        b = kb[sid]
        assert abs(a[2] - b[2]) < 1e-4 and abs(a[3] - b[3]) < 1e-4, f"{sid}: coordinates match"
        assert a[6] == b[6], f"{sid}: n_periods match"
        assert a[8] == b[8], f"{sid}: type match"
    sa = json.loads((out_a / "sci.json").read_text(encoding="utf-8"))
    sb = json.loads((out_b / "sci.json").read_text(encoding="utf-8"))
    assert [r[5] for r in sa] == [r[5] for r in sb], "dimensionality identical across input formats"


def test_edi_wins_when_one_station_has_both_edi_and_emtfxml(tmp_path):
    """OWNER PRECEDENCE RULING (2026-08-03): where a station has both, the EDI is the canonical
    source and the XML is kept in the package but NOT ingested.

    FAILS IF the XML rendition displaces or duplicates the EDI-sourced station. The package holds
    EXAMPLE01 as BOTH an EDI and an EMTF XML, plus EXAMPLE02 as XML only: EXAMPLE01 must resolve to
    edi (and its served EDI must be the custodian's own bytes, not a regenerated one), EXAMPLE02 to
    emtfxml, and the XML rendition of EXAMPLE01 must still sit untouched in the package."""
    pkg = _package(tmp_path / "surveys", edi_stations=("EXAMPLE01",),
                   xml_stations=("EXAMPLE01", "EXAMPLE02"))
    rc, out, prod = _build(tmp_path, tmp_path / "surveys")
    assert rc == 0

    d = _docs(out)
    assert d["build_report"]["surveys"][SLUG]["ingest_sources"] == \
        {"EXAMPLE01": "edi", "EXAMPLE02": "emtfxml"}, \
        "EDI wins for the station that has both; the XML-only station comes from emtfxml"
    assert sorted(d["build_provenance"]["input_formats"]) == ["edi", "emtfxml"]
    ids = sorted(row[0] for row in d["catalogue"])
    assert ids == ["EXAMPLE01", "EXAMPLE02"], \
        f"the doubly-supplied station must appear ONCE, not twice: {ids}"

    src_edi = pkg / "transfer_functions" / "edi" / "EXAMPLE01.edi"
    assert (out / "edi" / SLUG / "EXAMPLE01.edi").read_bytes() == src_edi.read_bytes(), \
        "the EDI-sourced station serves the custodian's own bytes, never a regenerated EDI"
    assert (pkg / "transfer_functions" / "emtfxml" / "EXAMPLE01.xml").is_file(), \
        "the superseded XML stays in the package, untouched"
    # exactly one edi + one xml artifact per station, no duplicate/variant rows
    rows = sorted((f["station"], f["format"]) for f in d["manifest"]["files"])
    assert rows == [("EXAMPLE01", "edi"), ("EXAMPLE01", "emtfxml"),
                    ("EXAMPLE02", "edi"), ("EXAMPLE02", "emtfxml")], rows


def _collision_package(root):
    """The served-EDI namespace collision, built from real bytes: station EXAMPLE01's custodian EDI
    filed under the name EXAMPLE02.edi (legal -- the id comes from DATAID, not the filename), and
    station EXAMPLE02 supplied ONLY as EMTF XML, whose generated EDI is named for the station. Two
    naming schemes, one directory, one contested name."""
    pkg = _package(root, edi_stations=("EXAMPLE01",), xml_stations=("EXAMPLE02",),
                   edi_filenames={"EXAMPLE01": "EXAMPLE02.edi"})
    assert (pkg / "transfer_functions" / "edi" / "EXAMPLE02.edi").is_file()
    assert (pkg / "transfer_functions" / "emtfxml" / "EXAMPLE02.xml").is_file()
    return pkg


def test_a_generated_edi_never_lands_on_a_custodian_edi_filename(tmp_path):
    """SERVED-EDI NAMESPACE. out/edi/<slug>/ holds two naming schemes: a custodian EDI keeps its own
    submitted filename, and an EMTF-XML-sourced station's generated EDI is named for the station.
    They are not disjoint, and a collision is SILENT -- one file on disk, two manifest rows naming
    it, both sha256 columns verifying against the same bytes.

    FAILS IF the two stations share a served file, if a manifest row's sha256 does not match the
    bytes at its own url, if the custodian's file is not served verbatim, or if the survey EDI zip
    claims more stations than it holds."""
    pkg = _collision_package(tmp_path / "surveys")
    rc, out, prod = _build(tmp_path, tmp_path / "surveys")
    assert rc == 0, "a legal package must build"

    d = _docs(out)
    assert d["build_report"]["surveys"][SLUG]["ingest_sources"] == \
        {"EXAMPLE01": "edi", "EXAMPLE02": "emtfxml"}, "fixture sanity: one station per source format"

    edi_rows = {f["station"]: f for f in d["manifest"]["files"] if f["format"] == "edi"}
    assert set(edi_rows) == {"EXAMPLE01", "EXAMPLE02"}, edi_rows
    urls = [row["url"] for row in edi_rows.values()]
    assert len(set(urls)) == 2, f"two stations must not advertise ONE served file: {urls}"

    for sid, row in edi_rows.items():
        served = out / row["url"]
        assert served.is_file(), f"{sid}: the advertised file must exist"
        assert hashlib.sha256(served.read_bytes()).hexdigest() == row["sha256"], \
            f"{sid}: the manifest digest must be the digest of the bytes at its own url"

    custodian = (pkg / "transfer_functions" / "edi" / "EXAMPLE02.edi").read_bytes()
    assert (out / edi_rows["EXAMPLE01"]["url"]).read_bytes() == custodian, \
        "the EDI-sourced station serves the custodian's own bytes, under the custodian's own filename"
    assert (out / edi_rows["EXAMPLE02"]["url"]).read_bytes() != custodian, \
        "the XML-sourced station must serve ITS OWN generated EDI, not its neighbour's science"

    for sid in ("EXAMPLE01", "EXAMPLE02"):
        sj = json.loads((prod / SLUG / sid / "station.json").read_text(encoding="utf-8"))
        assert sj["distribution"]["edi_path"] == edi_rows[sid]["url"], sj["distribution"]

    served_dir = sorted(p.name for p in (out / "edi" / SLUG).glob("*.edi"))
    assert len(served_dir) == 2, f"one served EDI per station: {served_dir}"
    zip_path = out / "bundles" / f"{SLUG}-edi.zip"
    members = [n for n in zipfile.ZipFile(zip_path).namelist() if n != "LICENSE.txt"]
    bundle = next(b for b in d["manifest"]["bundles"] if b["format"] == "edi-zip")
    assert len(members) == bundle["n_stations"] == 2, (members, bundle["n_stations"])


def test_the_build_refuses_two_manifest_rows_over_one_served_file(tmp_path, monkeypatch):
    """THE INVARIANT BEHIND THE FIX, not just the fix. Naming is one way two rows could end up over
    one file; the gate is what makes the class impossible. Driven by restoring the pre-fix naming
    rule (always <station>.edi, blind to the custodian namespace) over the collision package.

    FAILS IF the build publishes a manifest in which one served file is two stations' download. It
    must exit non-zero and name both claimants, rather than emit a corpus where both rows verify."""
    _collision_package(tmp_path / "surveys")
    monkeypatch.setattr(bp, "_derived_edi_filename", lambda station_id, taken: f"{station_id}.edi")
    rc, out, _prod = _build(tmp_path, tmp_path / "surveys")
    assert rc == 2, "a served file claimed by two manifest rows must fail the build"
    assert not (out / "manifest.json").exists(), \
        "a build that refuses must not leave a published manifest behind"


def test_roundtrip_gate_failure_serves_no_bytes_and_is_loud_in_the_build_report(tmp_path, monkeypatch):
    """ROUND-TRIP HONESTY. normalize() is the gate: EMTF XML in -> TF -> EMTF XML out must satisfy the
    same maxdiff closeness check the EDI pipeline uses, and a file that cannot round-trip must fail
    THAT STATION loudly, never silently.

    FAILS IF a failed station is served anyway or the failure is invisible. The failure is injected at
    the gate itself (normalize raises for one station, exactly as a real maxdiff breach does) so the
    consequence is deterministic. An EDI-sourced station falls back to its custodian EDI; an
    EMTF-XML-sourced one has nothing behind it, so it must serve NO bytes at all -- no canonical XML,
    no generated EDI, no manifest row -- while its sibling serves normally.

    _emit_served_xml does `from ausmt_science.ingest.normalize import normalize` at CALL time, so
    patching the module attribute is picked up on the next call (same technique as test_build_report)."""
    import ausmt_science.ingest.normalize as _ni  # noqa: PLC0415

    real = _ni.normalize
    victim = "EXAMPLE01"
    # Build the package with the REAL emitter first -- the fixture is written by normalize() too, so
    # patching before this point would sabotage the fixture instead of the build under test.
    _package(tmp_path / "surveys", xml_stations=("EXAMPLE01", "EXAMPLE02"))

    def _fake(src, out_dir, *, survey_id, station_id=None, **kw):
        if station_id and victim in str(station_id):
            raise RuntimeError("canonical EMTF-XML round-trip FAILED: impedance maxdiff=1.234e+00")
        return real(src, out_dir, survey_id=survey_id, station_id=station_id, **kw)

    monkeypatch.setattr(_ni, "normalize", _fake)
    rc, out, prod = _build(tmp_path, tmp_path / "surveys")
    assert rc == 0, "one station failing the gate must not abort the corpus build"

    d = _docs(out)
    jsonschema = pytest.importorskip("jsonschema")
    jsonschema.validate(d["build_report"], SCHEMA)
    survey = d["build_report"]["surveys"][SLUG]

    assert [r["station"] for r in survey["xml_failures"]] == [victim], survey["xml_failures"]
    assert survey["xml_failures"][0]["error"] == "RuntimeError", survey["xml_failures"]
    assert any("serve NO bytes at all" in w and victim in w for w in survey["warnings"]), \
        f"the warning must state the real consequence for an XML-sourced station: {survey['warnings']}"

    assert not (out / "xml" / SLUG / f"{victim}.xml").exists(), "no canonical XML for a failed station"
    assert not (out / "edi" / SLUG / f"{victim}.edi").exists(), \
        "no generated EDI either -- the generated EDI comes from the SAME gated normalize() call"
    assert {(f["station"], f["format"]) for f in d["manifest"]["files"]} == \
        {("EXAMPLE02", "edi"), ("EXAMPLE02", "emtfxml")}, \
        "only the station that passed the gate is advertised"
    sj = json.loads((prod / SLUG / victim / "station.json").read_text(encoding="utf-8"))
    assert sj["distribution"]["edi_available"] is False and sj["distribution"]["edi_path"] is None, \
        f"station.json must not advertise a download that was never written: {sj['distribution']}"
    # the failed station is still DISCOVERABLE -- it is a byte gap, not a disappearance
    assert victim in {row[0] for row in d["catalogue"]}


_Z_CELL = re.compile(r'(<value[^>]*name="Zxy"[^>]*>)([^<]+)(</value>)')


def _corrupt_first_impedance_cell(xml_path):
    """Corrupt a REAL generated EMTF XML the way a damaged submission is corrupt: replace the first
    Zxy value cell with a non-numeric pair. mt_metadata still READS the file, so normalize() gets as
    far as writing the canonical XML and the derived EDI, and only the round-trip comparison after
    them raises. That ordering is the whole point: a gate failure happens with two files already
    written into the served tree, which a normalize() stubbed to raise immediately cannot reproduce.
    """
    text = xml_path.read_text(encoding="utf-8")
    doctored, n = _Z_CELL.subn(lambda m: m.group(1) + "NaN NaN" + m.group(3), text, count=1)
    assert n == 1, f"fixture assumption: {xml_path.name} carries a Zxy value cell to corrupt"
    xml_path.write_text(doctored, encoding="utf-8")


def test_a_real_round_trip_failure_leaves_no_unverified_bytes_in_the_served_tree(tmp_path):
    """ROUND-TRIP HONESTY against a genuinely corrupted file, with nothing stubbed. The served data
    tree is handed out by PATH: deploy's file server serves whatever is under it, and
    /data/xml/<slug>/<station>.xml is a documented public URL, so a file needs no manifest row to be
    fetchable. A station the build reports as serving no bytes must therefore leave none.

    FAILS IF the gate fires and the unverified canonical XML or derived EDI is still on disk. Both
    are written before the comparison that rejects them. Self-guarding: if the corruption stops
    tripping the gate, the xml_failures assertion goes red rather than the test passing vacuously."""
    pkg = _package(tmp_path / "surveys", xml_stations=("EXAMPLE01", "EXAMPLE02"))
    victim = "EXAMPLE01"
    _corrupt_first_impedance_cell(pkg / "transfer_functions" / "emtfxml" / f"{victim}.xml")

    rc, out, prod = _build(tmp_path, tmp_path / "surveys")
    assert rc == 0, "one station failing the gate must not abort the corpus build"

    d = _docs(out)
    survey = d["build_report"]["surveys"][SLUG]
    assert [r["station"] for r in survey["xml_failures"]] == [victim], \
        f"the corrupted station must FAIL the round-trip gate: {survey['xml_failures']}"
    assert any("serve NO bytes at all" in w and victim in w for w in survey["warnings"]), \
        survey["warnings"]

    leftovers = sorted(str(p.relative_to(out)) for p in out.rglob(f"{victim}.*") if p.is_file())
    assert leftovers == [], \
        f"the served tree must hold nothing for a station that serves nothing: {leftovers}"
    assert {(f["station"], f["format"]) for f in d["manifest"]["files"]} == \
        {("EXAMPLE02", "edi"), ("EXAMPLE02", "emtfxml")}, "only the station that passed is advertised"
    assert (out / "xml" / SLUG / "EXAMPLE02.xml").is_file() and \
        (out / "edi" / SLUG / "EXAMPLE02.edi").is_file(), "the healthy sibling is unaffected"
    sj = json.loads((prod / SLUG / victim / "station.json").read_text(encoding="utf-8"))
    assert sj["distribution"]["edi_available"] is False and sj["distribution"]["edi_path"] is None, \
        sj["distribution"]
    assert victim in {row[0] for row in d["catalogue"]}, "a byte gap, not a disappearance"


def _corrupt_first_edi_impedance_value(edi_path):
    """The same corruption on the EDI side: the first value of the first >ZXYR data line."""
    text = edi_path.read_text(encoding="utf-8", errors="replace")
    m = re.search(r"(>ZXYR[^\n]*\n)([^\n]*\n)", text)
    assert m, f"fixture assumption: {edi_path.name} carries a >ZXYR block"
    first = m.group(2).split()[0]
    edi_path.write_text(text[:m.start(2)] + m.group(2).replace(first, "NaN", 1) + text[m.end(2):],
                        encoding="utf-8")


def test_a_real_round_trip_failure_leaves_no_unverified_bytes_for_an_edi_station(tmp_path):
    """The EDI-sourced leg of the same emitter, kept beside its sibling because it is the same
    failure path in _emit_served_xml. An EDI-sourced station keeps its custodian EDI when the XML
    emission fails, so the consequence differs -- but the two files normalize() wrote before the
    gate rejected them are just as unverified, and out/xml/<slug>/ is just as public.

    FAILS IF the rejected canonical XML, or the derived EDI written beside it, survives in the served
    tree. The custodian EDI must still serve: this is a lost XML download, not a lost station."""
    pkg = _package(tmp_path / "surveys", edi_stations=("EXAMPLE01", "EXAMPLE02"))
    victim = "EXAMPLE01"
    _corrupt_first_edi_impedance_value(pkg / "transfer_functions" / "edi" / f"{victim}.edi")

    rc, out, _prod = _build(tmp_path, tmp_path / "surveys")
    assert rc == 0

    d = _docs(out)
    survey = d["build_report"]["surveys"][SLUG]
    assert [r["station"] for r in survey["xml_failures"]] == [victim], \
        f"the corrupted station must FAIL the round-trip gate: {survey['xml_failures']}"

    assert not (out / "xml" / SLUG / f"{victim}.xml").exists(), \
        "the rejected canonical XML must not sit at its own public URL"
    assert not (out / "xml" / SLUG / f"{victim}.edi").exists(), \
        "nor the derived EDI written beside it before the gate ran"
    assert (out / "edi" / SLUG / f"{victim}.edi").is_file(), \
        "an EDI-sourced station still serves the custodian file it was built from"
    rows = {(f["station"], f["format"]) for f in d["manifest"]["files"]}
    assert (victim, "edi") in rows and (victim, "emtfxml") not in rows, rows


def test_embargoed_emtfxml_survey_serves_no_bytes(tmp_path):
    """EMBARGO INHERITANCE (the reviewer must PROVE it, not accept it). The XML ingest lands in the
    same station pipeline, so the C1 access gate applies unchanged.

    FAILS IF an embargoed EMTF-XML-only survey serves any byte: no canonical XML, no generated EDI,
    no bundles, no manifest rows, and a WITHHELD station.json carrying no TF-derived science -- while
    the survey stays fully in the discovery catalogue."""
    y = (EXAMPLE_SURVEY / "survey.yaml").read_text(encoding="utf-8").replace(
        "access:\n  level: open\n", 'access:\n  level: embargoed\n  embargo_until: "2099-01-01"\n')
    assert "embargoed" in y, "the fixture's access block must have been rewritten"
    _package(tmp_path / "surveys", xml_stations=("EXAMPLE01", "EXAMPLE02"), yaml_text=y)
    rc, out, prod = _build(tmp_path, tmp_path / "surveys")
    assert rc == 0

    d = _docs(out)
    assert d["manifest"]["files"] == [] and d["manifest"]["bundles"] == [], d["manifest"]
    assert not (out / "xml").exists(), "an embargoed survey emits NO canonical XML"
    assert not (out / "edi").exists(), "an embargoed survey emits NO generated EDI"
    assert not (out / "bundles").exists(), "an embargoed survey emits NO bundles"
    assert len(d["catalogue"]) == 2, "embargo withholds bytes, not discovery"
    sj = json.loads((prod / SLUG / "EXAMPLE01" / "station.json").read_text(encoding="utf-8"))
    assert sj["withheld"] is True and sj["access"]["served"] is False, sj
    assert "diagnostics" not in sj and "location" not in sj, \
        f"the derived science of an embargoed XML-only survey must be withheld too: {sorted(sj)}"


def test_withheld_coordinate_emtfxml_station_serves_no_coordinates_and_no_bytes(tmp_path):
    """COORDINATE POLICY INHERITANCE. The C42 per-station byte gate is applied at the emit seam, which
    the XML path shares, so a withheld-coordinate station must lose its coordinates AND its bytes --
    an EMTF XML is a full coordinate + elevation bearer, so it is withheld, never redacted.

    FAILS IF a withheld XML station serves a coordinate, a canonical XML, or a generated EDI."""
    y = (EXAMPLE_SURVEY / "survey.yaml").read_text(encoding="utf-8").replace(
        "access:\n  level: open\n",
        "access:\n  level: open\n  coordinate_overrides:\n    EXAMPLE01: withheld\n")
    assert "coordinate_overrides" in y
    _package(tmp_path / "surveys", xml_stations=("EXAMPLE01", "EXAMPLE02"), yaml_text=y)
    rc, out, prod = _build(tmp_path, tmp_path / "surveys")
    assert rc == 0

    d = _docs(out)
    cat = {row[0]: row for row in d["catalogue"]}
    assert cat["EXAMPLE01"][2] is None and cat["EXAMPLE01"][3] is None, \
        "a withheld station's coordinates are null in the catalogue"
    assert cat["EXAMPLE02"][2] is not None, "its exact sibling is unaffected"
    assert not (out / "xml" / SLUG / "EXAMPLE01.xml").exists(), "no canonical XML for a withheld station"
    assert not (out / "edi" / SLUG / "EXAMPLE01.edi").exists(), "no generated EDI either"
    assert (out / "xml" / SLUG / "EXAMPLE02.xml").is_file() and \
        (out / "edi" / SLUG / "EXAMPLE02.edi").is_file(), "the exact sibling still serves both formats"
    assert {(f["station"], f["format"]) for f in d["manifest"]["files"]} == \
        {("EXAMPLE02", "edi"), ("EXAMPLE02", "emtfxml")}, d["manifest"]["files"]
    sj = json.loads((prod / SLUG / "EXAMPLE01" / "station.json").read_text(encoding="utf-8"))
    assert sj["location"] == {"lat": None, "lon": None}, sj["location"]
    assert sj["distribution"]["edi_available"] is False and sj["distribution"]["edi_path"] is None, \
        sj["distribution"]


def test_declared_frame_is_read_from_the_file_not_from_a_library_default(tmp_path):
    """C25 honesty on the XML path. The frame an EMTF XML declares lives in
    <Site><Orientation angle_to_geographic_north=...>. mt_metadata 1.0.9's EMTF-XML reader leaves the
    TF's own _rotation_angle at a bare 0 regardless of what the file says, so reading THAT would
    report every station as 'declared-zero' -- a library default asserted as a station fact.

    FAILS IF a station whose file declares 30 degrees is recorded as declared-zero (the pre-fix
    behaviour of reading _rotation_angle), or if the station is refused rather than served as stored.
    The sibling, which really does declare 0, must still read declared-zero."""
    pkg = _package(tmp_path / "surveys", xml_stations=("EXAMPLE01", "EXAMPLE02"))
    victim = pkg / "transfer_functions" / "emtfxml" / "EXAMPLE01.xml"
    text = victim.read_text(encoding="utf-8")
    assert 'angle_to_geographic_north="0.000"' in text, \
        "fixture assumption: the emitter writes the site Orientation angle"
    victim.write_text(text.replace('angle_to_geographic_north="0.000"',
                                   'angle_to_geographic_north="30.000"'), encoding="utf-8")

    rc, out, prod = _build(tmp_path, tmp_path / "surveys")
    assert rc == 0
    a = json.loads((prod / SLUG / "EXAMPLE01" / "station.json").read_text(encoding="utf-8"))["frame"]
    b = json.loads((prod / SLUG / "EXAMPLE02" / "station.json").read_text(encoding="utf-8"))["frame"]
    assert a["frame_served"] == "declared-azimuth" and a["declared_azimuth_deg"] == 30.0, a
    assert a["evidence"]["orientation_angle_to_geographic_north_deg"] == 30.0, a["evidence"]
    assert a["derotated"] is False, "v3 never rotates: the frame is recorded, not corrected"
    assert b["frame_served"] == "declared-zero" and b["declared_azimuth_deg"] == 0.0, b


def test_per_period_rotation_declaration_refuses_the_station():
    """C25 POLICY v3 applies to the XML path too: AusMT serves data AS STORED and never serves a
    per-period-mixed frame, so the XML frame reader must REFUSE a per-period declaration rather than
    pick one of the angles.

    Exercised at the unit seam on purpose: on the pinned mt_metadata no real EMTF XML reaches this
    branch (the reader collapses the file's frame to a single site-level Orientation), so there is no
    fixture that can drive it. This is the non-vacuity proof that the fail-closed guard CAN fail --
    it stops the XML path from silently serving what the EDI path refuses, should a future reader
    surface per-period angles.

    FAILS IF a per-period rotation is served, or is served under one of its own angles."""
    class _Ori:
        angle_to_geographic_north = 0.0
        reference_frame = "geographic"

    class _SM:
        orientation = _Ori()

    class _TF:
        station_metadata = _SM()
        _rotation_angle = [0.0, 0.0, 30.0, 30.0]

    facts, fail = bp._emtfxml_frame(_TF(), 4)
    assert fail and "per-period" in fail.lower(), fail
    assert "30" in fail and "never serves a per-period-mixed frame" in fail, fail
    assert "frame_served" not in facts, "a refused station is never given a served-frame verdict"

    # control: the same station with ONE declared angle serves as stored
    _TF._rotation_angle = [30.0, 30.0, 30.0, 30.0]
    _Ori.angle_to_geographic_north = 30.0
    facts, fail = bp._emtfxml_frame(_TF(), 4)
    assert fail is None and facts["frame_served"] == "declared-azimuth", (facts, fail)
    assert facts["declared_azimuth_deg"] == 30.0, facts

    # and an EMTF XML that asserts NO orientation is recorded as not-asserted, never as zero
    _Ori.angle_to_geographic_north = None
    facts, fail = bp._emtfxml_frame(_TF(), 4)
    assert fail is None and facts["frame_served"] == "not-asserted", facts
    assert facts["declared_azimuth_deg"] is None, facts


def test_a_generated_edi_and_its_survey_zip_are_byte_reproducible_across_builds(tmp_path):
    """THE SERVED-EDI CROSS-BUILD INVARIANT, over the source format that could break it. The
    manifest reference states that the served EDI and the per-survey EDI zip are byte-reproducible
    across builds, so their SHA-256 is a stable cross-build invariant, unlike the EMTF XML and the
    MTH5. That was free while every served EDI was a custodian copy. An EMTF-XML-sourced station's
    EDI is WRITTEN by mt_metadata, whose EDI header writer stamps FILEDATE with the wall clock at
    write time, so without the source-stamped FILEDATE the generated file (and the survey zip that
    carries it) hashes differently on every build.

    ONE package, built TWICE, with the input bytes checked unchanged in between so a drifting digest
    can only come from the build. test_manifest.py's determinism test cannot see this: the sample
    survey it builds is EDI-only, so no generated EDI exists in it.

    FAILS IF a served EDI or the EDI zip changes digest across two builds of one package, or if the
    generated EDI's FILEDATE is not its source document's own creation time."""
    surveys = tmp_path / "surveys"
    pkg = _package(surveys, xml_stations=("EXAMPLE02",), edi_stations=("EXAMPLE01",))
    before = {p.relative_to(pkg).as_posix(): hashlib.sha256(p.read_bytes()).hexdigest()
              for p in sorted(pkg.rglob("*")) if p.is_file()}

    rc1, out1, _p1 = _build(tmp_path / "b1", surveys)
    rc2, out2, _p2 = _build(tmp_path / "b2", surveys)
    assert rc1 == 0 and rc2 == 0, (rc1, rc2)
    after = {p.relative_to(pkg).as_posix(): hashlib.sha256(p.read_bytes()).hexdigest()
             for p in sorted(pkg.rglob("*")) if p.is_file()}
    assert before == after, "the build must not modify the submitted package it is reading"

    m1, m2 = _docs(out1)["manifest"], _docs(out2)["manifest"]
    assert _docs(out1)["build_report"]["surveys"][SLUG]["ingest_sources"] == \
        {"EXAMPLE01": "edi", "EXAMPLE02": "emtfxml"}, "fixture sanity: one station per source format"

    def digests(man, fmt, scope):
        return sorted((r["url"], r["sha256"]) for r in man[scope] if r["format"] == fmt)

    edi1 = digests(m1, "edi", "files")
    assert len(edi1) == 2, f"both stations must serve an EDI: {edi1}"
    assert edi1 == digests(m2, "edi", "files"), \
        f"served EDI digests drifted across two builds of ONE package: {edi1} vs {digests(m2, 'edi', 'files')}"
    zip1 = digests(m1, "edi-zip", "bundles")
    assert zip1 and zip1 == digests(m2, "edi-zip", "bundles"), \
        f"the survey EDI zip digest drifted across two builds: {zip1} vs {digests(m2, 'edi-zip', 'bundles')}"

    # the mechanism, not just the symptom: the generated file carries its SOURCE document's date
    gen_url = next(r["url"] for r in m1["files"] if r["format"] == "edi" and r["station"] == "EXAMPLE02")
    text = (out1 / gen_url).read_text(encoding="utf-8", errors="replace")
    filedate = re.search(r"^\s*FILEDATE=(.+?)\s*$", text, re.M)
    source_date = re.search(r"^\s*original_file\.date=(.+?)\s*$", text, re.M)
    assert filedate and source_date, "the generated EDI must carry both a FILEDATE and a source date"
    assert filedate.group(1) == source_date.group(1), \
        f"FILEDATE must be the source document's own date, got {filedate.group(1)} vs {source_date.group(1)}"
