"""The time-series hand-off routes: the generated table AND the front-door directives that serve it.

`/go/ts/<survey>/<station>/<level>` 302s to the one NCI THREDDS fileServer URL for that file, and
404s for every path the table does not name. Two artifacts, pinned together here because neither is
safe alone:

  * `deploy/frontdoor/ts-routes.map` - GENERATED by deploy/scripts/gen_ts_routes.py from the
    per-survey verified-resource registers and COMMITTED, one line per projected (survey, station,
    level). It is the FIFTH leak artifact of the module's section-2 sweep and the only one that is not
    JSON, which is why its sweep lives here rather than in the engine's root-level sweep.
  * the Caddyfile map + two handles that turn it into a redirect, and refuse everything else.

THE TABLE IS THE SUPPRESSION (R5). `has_time_series` is projected for withheld stations too
(existence semantics), so mtcat.json hands an enumerator every segment of one of these paths:
suppression cannot live in discovery and must live in RESOLUTION. The map admits ONLY open-access,
`review: verified`, non-level2 rows, so an unlisted path cannot produce a Location at all - the
map's `default ""` 404s it by construction rather than by filter. A front-door leak is invisible to
an engine-side rglob, which is why this pin lives in deploy/tests.

EVERY NEGATIVE CARRIES A SENSITIVITY CONTROL: the same path, with the row admitted, resolves. A dead
matcher or a mis-built fixture would otherwise pass every 404 pin for the wrong reason.

The textual + generator legs run everywhere (stdlib + PyYAML). Where a caddy binary is on PATH the
directives are additionally driven against a REAL Caddy, exactly as test_frontdoor_pathurl_contract
does; CI installs caddy (gateway-ci.yml), so the runtime legs run there.
"""
from __future__ import annotations

import json
import re
import shutil
import socket
import subprocess
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

import pytest

_REPO = Path(__file__).resolve().parents[2]
_FRONTDOOR = _REPO / "deploy" / "frontdoor"
_FD_CADDY = _FRONTDOOR / "Caddyfile"
_COMPOSE = _FRONTDOOR / "compose.yaml"
_INSTALL = _FRONTDOOR / "install-frontdoor.sh"
_DOCTOR = _FRONTDOOR / "doctor.sh"
_RUNBOOK = _FRONTDOOR / "RUNBOOK.md"
_MAP = _FRONTDOOR / "ts-routes.map"
_GEN = _REPO / "deploy" / "scripts" / "gen_ts_routes.py"
# The percent-encoding vectors the engine leaf and the portal JS mirror are both held to.
_VECTORS = _REPO / "engine" / "tests" / "fixtures" / "ts_url_vectors.json"

sys.path.insert(0, str(_REPO / "deploy" / "scripts"))
import gen_ts_routes as gen          # noqa: E402  (also puts engine/extract on sys.path)
import _stationcheck as stcheck      # noqa: E402  (TS_ACCESS_PREFIX + the encoded-route rule)
import _tsindex as tsindex           # noqa: E402  (the closed level vocabulary)
import _tsproject as tsproject       # noqa: E402  (THE projection both renderings must share)

_HAS_CADDY = shutil.which("caddy") is not None

_SECTION_OPEN = "# ---- TIME-SERIES HAND-OFF ROUTES"
_SECTION_CLOSE = "# ---- end time-series hand-off routes"
_MAP_MOUNT = "/etc/caddy/ts-routes.map"
# The corpus encoding vector, restated as a fixture: only the encoded form answers 200 at NCI, and a
# literal space in a Location is a dead download.
_RAW_ZIP = "arch/OPEN1 [REMOTE].zip"
_ENC_ZIP = "arch/OPEN1%20%5BREMOTE%5D.zip"


# ==================================================================================================
# Fixture corpus: one open survey (a verified row, a pending row, a retired row and a level2 row),
# one embargoed survey and one metadata_only survey, each carrying a verified row that must NOT
# route. Driving the REAL generator over it is what makes the leak sweep below non-vacuous.
# ==================================================================================================
def _survey_yaml(slug: str, level: str, extra: str = "") -> str:
    return (f"slug: {slug}\nname: {slug} fixture\nlicense: CC-BY-4.0\n"
            f"access:\n  level: {level}\n  embargo_until: null\n{extra}")


def _row(level: str, url_path: str, review: str, extra: str = "") -> str:
    return (f"    - level: {level}\n      url_path: \"{url_path}\"\n"
            f"      filename: \"{Path(url_path).name}\"\n      bytes: 4096\n"
            f"      verified: \"2026-08-24\"\n      match_method: exact\n"
            f"      review: {review}\n{extra}")


def _corpus(root: Path, *, held_level: str = "embargoed") -> Path:
    """The synthetic survey root. `held_level` flips the embargoed survey open, which is the
    SENSITIVITY CONTROL for every withheld pin: the same register row, one access level apart."""
    surveys = root / "surveys"
    for slug, level, rows in (
        ("open-survey", "open",
         _row("raw_packed", _RAW_ZIP, "verified")
         + _row("level2", "arch/OPEN1-tf.edi", "verified")
         + "  PEND1:\n" + _row("raw_packed", "arch/PEND1.zip", "pending")
         + "  RETIRE1:\n" + _row("raw_packed", "arch/RETIRE1.zip", "retired",
                                 "      retired: \"2026-08-01\"\n"
                                 "      retired_reason: withdrawn by the custodian\n")),
        ("held-survey", held_level, _row("raw_packed", "arch/HELD1.zip", "verified")),
        ("meta-survey", "metadata_only", _row("raw_packed", "arch/META1.zip", "verified")),
    ):
        d = surveys / slug
        d.mkdir(parents=True)
        (d / "survey.yaml").write_text(_survey_yaml(slug, level), encoding="utf-8")
        first = {"open-survey": "OPEN1", "held-survey": "HELD1", "meta-survey": "META1"}[slug]
        (d / "ts-index.yaml").write_text(f"ts_index:\n  {first}:\n{rows}", encoding="utf-8")
    return surveys


def _generate(tmp_path: Path, **kw) -> tuple[Path, str]:
    """(map path, rendered text) from the REAL generator over the fixture corpus."""
    surveys = _corpus(tmp_path, **kw)
    out = tmp_path / "ts-routes.map"
    rc = gen.main(["--write", "--surveys", str(surveys), "--out", str(out)])
    assert rc == 0, "the generator must succeed over the fixture corpus"
    return out, out.read_text(encoding="utf-8")


def _keys(text: str) -> list:
    return [ln.split('" "')[0][1:] for ln in text.splitlines() if ln.startswith('"')]


def _pairs(text: str) -> dict:
    out = {}
    for ln in text.splitlines():
        if not ln.startswith('"'):
            continue
        key, value = ln.split('" "')
        out[key[1:]] = value.rstrip('"')
    return out


# ==================================================================================================
# The generator: membership, and the five things that must never reach the table
# ==================================================================================================
def test_generator_admits_only_the_open_verified_routable_row(tmp_path):
    """THE MEMBERSHIP PIN. Over a corpus carrying one of every state, the table holds EXACTLY the
    open + `review: verified` + routable row. FAILS IF membership widens by any one of the four."""
    _out, text = _generate(tmp_path)
    assert _keys(text) == ["/go/ts/open-survey/OPEN1/raw_packed"], (
        f"only the open, verified, non-level2 row may route; got {_keys(text)}")


def test_generator_leak_sweep_over_the_shipped_table(tmp_path):
    """THE FIFTH ARTIFACT of the section-2 leak sweep, swept where it lives: NO NCI path, filename or
    size for a withheld, metadata-only, `review: pending`, retired or level2 row appears ANYWHERE in
    the generated bytes - not as a value, not as a key, not in the banner. FAILS IF any suppressed
    row's route detail reaches the front door's table."""
    _out, text = _generate(tmp_path)
    for token in ("HELD1", "META1", "PEND1", "RETIRE1", "OPEN1-tf", "level2"):
        assert token not in text.replace("level2 never routes", ""), (
            f"{token} is suppressed, so no trace of it may appear in the route table:\n{text}")


def test_generator_leak_sweep_is_non_vacuous(tmp_path):
    """SENSITIVITY CONTROL for the sweep above. The SAME embargoed register row, with the survey's
    access level flipped to open, DOES route - so the sweep is measuring the access gate rather than
    a fixture that never had the row. FAILS IF the control row does not appear (the sweep would then
    pass for the wrong reason)."""
    _out, text = _generate(tmp_path, held_level="open")
    assert "/go/ts/held-survey/HELD1/raw_packed" in text, (
        f"the control row must route once its survey is open:\n{text}")
    assert "arch/HELD1.zip" in text, "the control row must carry its route detail"


def test_generator_membership_is_the_shared_projection_not_a_second_opinion(tmp_path):
    """KEY-SET PARITY, the drift guard the split-host shape needs: the table's (station, level) keys
    equal what `_tsproject.route_rows` - the same predicate ts_access.json renders from - answers
    for the same registers. A row cannot resolve that the data does not publish, or vice versa.
    FAILS IF the generator ever grows a membership rule of its own."""
    surveys = _corpus(tmp_path)
    out = tmp_path / "ts-routes.map"
    assert gen.main(["--write", "--surveys", str(surveys), "--out", str(out)]) == 0
    expected = set()
    for slug, sid, open_ in (("open-survey", "OPEN1", True), ("open-survey", "PEND1", True),
                             ("open-survey", "RETIRE1", True), ("held-survey", "HELD1", False),
                             ("meta-survey", "META1", False)):
        rows = tsindex.load(surveys, slug, gen._CorpusUnknown()).get(sid, [])
        for level in tsproject.route_rows(rows, open_):
            expected.add(f"/go/ts/{slug}/{sid}/{level}")
    assert set(_keys(out.read_text(encoding="utf-8"))) == expected


def test_generator_percent_encodes_the_route_like_the_published_access_url(tmp_path):
    """The map VALUE is the register's url_path encoded exactly as station.json's access_url is:
    `C5 [REMOTE].zip` only answers 200 as `C5%20%5BREMOTE%5D.zip`. Held to the SAME encoded-route
    rule _stationcheck applies to the published route, so a value this table admits is one that gate
    admits. FAILS IF a literal space or bracket reaches a Location, or the encoding drifts."""
    _out, text = _generate(tmp_path)
    assert _pairs(text)["/go/ts/open-survey/OPEN1/raw_packed"] == _ENC_ZIP
    for value in _pairs(text).values():
        assert stcheck._TS_ENCODED.match(value), f"{value!r} is not an encoded fileServer path"


def test_generator_ASKS_the_one_encoder_rather_than_restating_it(monkeypatch):
    """"Encoded the same way" was a coincidence held by the test above; this makes it an import.

    Two `quote(safe="/")` calls that agree today diverge the day one of them learns about a
    character the other does not, and the failure is silent in the worst way: station.json would
    publish a route that works while this table published one that 404s at the archive, for the same
    file. So the generator CALLS `_stationcheck.ts_encode_path` - the engine seam it already imports
    for `TS_ACCESS_PREFIX` and the encoded-route rule - and is driven here by replacing it."""
    monkeypatch.setattr(stcheck, "ts_encode_path", lambda p: "SENTINEL/x.zip", raising=False)
    assert gen._target(Path("open-survey"), "OPEN1", "raw_packed", _RAW_ZIP) == "SENTINEL/x.zip"


def test_generator_reproduces_every_shared_percent_encoding_vector():
    """The third arm of the shared vector file (engine/tests/fixtures/ts_url_vectors.json): the
    engine leaf and the portal's JS mirror are pinned against it in their own suites, and the map
    VALUE is the same string without the host. A vector that reds here reds on all three."""
    doc = json.loads(_VECTORS.read_text(encoding="utf-8"))
    assert doc["prefix"] == stcheck.TS_ACCESS_PREFIX
    for v in doc["vectors"]:
        got = gen._target(Path("open-survey"), "OPEN1", "raw_packed", v["url_path"])
        assert got == v["encoded_path"], v["name"]
        # ...and the Location Caddy builds from it is the published access_url, byte for byte.
        assert stcheck.TS_ACCESS_PREFIX + got == v["expected"], v["name"]


def test_generator_honours_a_per_station_coordinate_override_and_keeps_generating(tmp_path):
    """A position-withheld station LOSES ITS ROUTE, and every other survey keeps its own.

    The station's raw time series carries the true position in every corner the coordinate mask
    exists to hide, so the route has to go. Refusing to generate is the WRONG way to achieve that:
    main then writes nothing, so a single override anywhere leaves the whole table un-regenerable
    while the committed one goes on resolving the station the mask has just withheld. Suppression
    that cannot be published is not suppression.

    The override keys the BASE station id and this reader holds no variant tag, so it resolves
    through _coordaccess's own conservative resolver - it drops every station the build drops and
    possibly one more, a direction that can only 404 a hand-off, never keep one alive."""
    surveys = _corpus(tmp_path, held_level="open")     # held-survey routes: the survivor control
    sy = surveys / "open-survey" / "survey.yaml"
    sy.write_text(sy.read_text(encoding="utf-8")
                  + "  coordinate_overrides:\n    OPEN1: withheld\n", encoding="utf-8")
    out = tmp_path / "ts-routes.map"
    assert gen.main(["--write", "--surveys", str(surveys), "--out", str(out)]) == 0, (
        "an override is a suppression decision this reader can make, not a reason to stop")
    text = out.read_text(encoding="utf-8")
    assert "/go/ts/open-survey/OPEN1/raw_packed" not in _keys(text), text
    assert _RAW_ZIP not in text and _ENC_ZIP not in text, (
        f"no route detail for a position-withheld station may reach the table:\n{text}")
    assert "/go/ts/held-survey/HELD1/raw_packed" in _keys(text), (
        "sensitivity: the rest of the corpus still routes, so the table stays producible")


def test_a_coordinate_override_covers_the_stations_variant_records_too(tmp_path):
    """base_station_id strips an engine-appended `.<variant>` tag, so an override on `A1` masks
    `A1.b` as well. This reader has no variant field, so it matches the SHAPE instead - equal to the
    key, or the key plus a dot - which is the conservative SUPERSET of what the build masks. A2 is
    the control: the mask is per station, not per survey."""
    surveys = tmp_path / "variant-surveys"
    d = surveys / "var-survey"
    d.mkdir(parents=True)
    (d / "survey.yaml").write_text(
        _survey_yaml("var-survey", "open") + "  coordinate_overrides:\n    A1: withheld\n",
        encoding="utf-8")
    (d / "ts-index.yaml").write_text(
        "ts_index:\n"
        + "".join(f"  {sid}:\n" + _row("raw_packed", f"arch/{sid}.zip", "verified")
                  for sid in ("A1", "A1.b", "A2")), encoding="utf-8")
    out = tmp_path / "ts-routes.map"
    assert gen.main(["--write", "--surveys", str(surveys), "--out", str(out)]) == 0
    text = out.read_text(encoding="utf-8")
    assert _keys(text) == ["/go/ts/var-survey/A2/raw_packed"], _keys(text)
    for masked in ("A1.zip", "A1.b.zip"):
        assert masked not in text, f"{masked} belongs to a masked physical site:\n{text}"


def test_an_unresolvable_survey_drops_its_own_routes_and_nothing_elses(tmp_path):
    """CONTAINMENT, the property that makes the table always producible.

    A register this reader cannot read is a survey-level stop, not a corpus-level one: it publishes
    no routes and every other survey publishes its own. Dropping is the safe direction (a route the
    table stops naming 404s, which is a broken hand-off rather than a leak); raising out of the loop
    was not, because the fallback was a STALE table still serving. FAILS IF one bad register can
    take the corpus offline, or if a bad register silently keeps its routes."""
    surveys = _corpus(tmp_path, held_level="open")
    reg = surveys / "open-survey" / "ts-index.yaml"
    reg.write_text(reg.read_text(encoding="utf-8") + "stray_block:\n  a: 1\n", encoding="utf-8")
    out = tmp_path / "ts-routes.map"
    assert gen.main(["--write", "--surveys", str(surveys), "--out", str(out)]) == 0
    text = out.read_text(encoding="utf-8")
    assert _keys(text) == ["/go/ts/held-survey/HELD1/raw_packed"], _keys(text)
    assert _RAW_ZIP not in text and _ENC_ZIP not in text, "the dropped survey publishes no detail"


def test_a_dropped_survey_is_recorded_in_the_committed_table(tmp_path):
    """The drop is not silent. Membership IS the R5 decision, so a change to it belongs in a diff a
    human reads and in a `--check` that reds - which is why the record lives in the committed file
    and not only on stderr. And the reason names NO absolute path: this file is byte-compared, so a
    path from whichever checkout generated it would red the gate on every other one."""
    surveys = _corpus(tmp_path, held_level="open")
    reg = surveys / "open-survey" / "ts-index.yaml"
    reg.write_text(reg.read_text(encoding="utf-8") + "stray_block:\n  a: 1\n", encoding="utf-8")
    out = tmp_path / "ts-routes.map"
    assert gen.main(["--write", "--surveys", str(surveys), "--out", str(out)]) == 0
    text = out.read_text(encoding="utf-8")
    marks = [ln for ln in text.splitlines() if ln.startswith("# UNRESOLVED ")]
    assert marks == [m for m in marks if m.startswith("# UNRESOLVED open-survey: ")], marks
    assert "stray_block" in marks[0], marks
    assert str(surveys) not in text and str(tmp_path) not in text, (
        f"a committed, byte-compared file may carry no machine path:\n{text}")
    # ...and a table carrying the record still round-trips through --check unchanged.
    assert gen.main(["--check", "--surveys", str(surveys), "--out", str(out)]) == 0


@pytest.mark.parametrize("why,mutate,forbidden", [
    ("a url_path that walks up out of the fileServer root",
     lambda s: (s / "open-survey" / "ts-index.yaml").write_text(
         "ts_index:\n  OPEN1:\n" + _row("raw_packed", "my80/../../../etc/passwd", "verified"),
         encoding="utf-8"),
     "passwd"),
    ("a slug no published ausmt_id could carry",
     lambda s: (s / "open-survey" / "survey.yaml").write_text(
         _survey_yaml("../escape", "open"), encoding="utf-8"),
     '"/go/ts/../escape'),
], ids=["traversal-url-path", "unsafe-slug"])
def test_the_refusal_branches_drop_their_survey_and_leave_the_table_standing(tmp_path, why, mutate,
                                                                            forbidden):
    """The two refusals that were uncovered code, and each is now a survey-scope drop rather than a
    corpus-scope stop, so each needs its own pin. A `..` url_path is the string _stationcheck also
    refuses (one predicate, both readers), and a slug outside safe_component's shape would mint a
    route under an identifier no build ever assigned. Either takes that survey's hand-offs offline;
    neither takes the corpus's, and neither string reaches the file the front door imports."""
    surveys = _corpus(tmp_path, held_level="open")
    mutate(surveys)
    out = tmp_path / "ts-routes.map"
    assert gen.main(["--write", "--surveys", str(surveys), "--out", str(out)]) == 0, why
    text = out.read_text(encoding="utf-8")
    assert _keys(text) == ["/go/ts/held-survey/HELD1/raw_packed"], (why, _keys(text))
    assert any(ln.startswith("# UNRESOLVED open-survey: ") for ln in text.splitlines()), text
    assert forbidden not in text, (why, text)


def test_a_dropped_survey_reds_check_until_the_drop_is_committed(tmp_path):
    """The other half of not-silent: a survey that STARTS failing changes the file, so the gate
    catches it. A drop that left the bytes identical would be invisible to review and to CI."""
    surveys = _corpus(tmp_path, held_level="open")
    out = tmp_path / "ts-routes.map"
    assert gen.main(["--write", "--surveys", str(surveys), "--out", str(out)]) == 0
    reg = surveys / "open-survey" / "ts-index.yaml"
    reg.write_text(reg.read_text(encoding="utf-8") + "stray_block:\n  a: 1\n", encoding="utf-8")
    assert gen.main(["--check", "--surveys", str(surveys), "--out", str(out)]) == 1


def test_generator_survey_serve_verdict_matches_the_access_vocabulary(tmp_path):
    """The one predicate this reader restates rather than imports (access_serve_state lives in
    build_portal, which pulls the whole mt_metadata stack). Pin the whole vocabulary: only `open`
    serves; metadata_only never does; an embargoed survey stays withheld whatever embargo_until says
    - a LAPSED date does not auto-publish, which is the trap the engine's own rule was written for;
    an absent level is open (the corpus predates the field) and an unrecognised one fails closed."""
    for level, embargo, want in (("open", None, True), ("open", "2099-01-01", True),
                                 ("embargoed", "2099-01-01", False), ("embargoed", "2001-01-01", False),
                                 ("embargoed", None, False), ("metadata_only", None, False),
                                 ("", None, True), (None, None, True), ("open-ish", None, False)):
        block = {"level": level, "embargo_until": embargo}
        assert gen._survey_serves(block) is want, f"access.level={level!r} must serve={want}"
    assert gen._survey_serves(None) is True, "a flat/absent access block is the legacy all-open corpus"


def test_generator_check_mode_gates_a_hand_edit(tmp_path):
    """--check is the rule-7 gate: green on the generated bytes, exit 1 the moment the table and the
    registers disagree (a hand-added line, a register that moved without a regenerate). FAILS IF a
    drifted table reports in sync - a stale table is a stale ACCESS decision."""
    surveys = _corpus(tmp_path)
    out = tmp_path / "ts-routes.map"
    assert gen.main(["--write", "--surveys", str(surveys), "--out", str(out)]) == 0
    assert gen.main(["--check", "--surveys", str(surveys), "--out", str(out)]) == 0
    out.write_text(out.read_text(encoding="utf-8") + '"/go/ts/held-survey/HELD1/raw_packed" "x"\n',
                   encoding="utf-8")
    assert gen.main(["--check", "--surveys", str(surveys), "--out", str(out)]) == 1


def test_generator_stops_without_registers_instead_of_passing_vacuously(tmp_path):
    """The registers live in the SIBLING surveys checkout. With no register root the check STOPS
    (exit 2) rather than reporting an empty table in sync, which would be a green light for a
    withdrawal nobody made. FAILS IF a missing input can produce a pass."""
    assert gen.main(["--check", "--surveys", str(tmp_path / "nope"), "--out", str(tmp_path / "m")]) == 2


def test_generator_writes_nothing_without_an_explicit_mode(tmp_path):
    """contract/generate.py's precedent: no-args, --help, an unrecognised flag, or both modes at once
    prints usage and writes NOTHING, so a stray --help can never fall through to the write branch."""
    out = tmp_path / "ts-routes.map"
    surveys = _corpus(tmp_path)
    for argv in ([], ["--help"], ["--bogus"], ["--check", "--write"]):
        assert gen.main([*argv, "--surveys", str(surveys), "--out", str(out)]) == 2
    assert not out.exists()


# ==================================================================================================
# The committed table
# ==================================================================================================
def test_committed_table_is_generated_shape_and_routable_tokens_only():
    """The shipped ts-routes.map: a generated banner, then `"key" "value"` lines whose keys are
    /go/ts/<survey>/<station>/<level> over the register's CLOSED level vocabulary minus the tokens
    that never project, whose values are encoded fileServer paths, and no key twice (one path names
    one file). FAILS IF a hand-edit, a stray token or a duplicate route reaches the front door."""
    text = _MAP.read_text(encoding="utf-8")
    assert text.startswith("# GENERATED by deploy/scripts/gen_ts_routes.py"), (
        "the table must announce that it is generated")
    routable = set(tsindex.LEVELS) - set(tsproject.NEVER_PROJECTS)
    keys = _keys(text)
    assert len(keys) == len(set(keys)), "one (survey, station, level) names one file"
    for key, value in _pairs(text).items():
        parts = key.split("/")
        assert parts[:3] == ["", "go", "ts"] and len(parts) == 6, f"bad route key {key!r}"
        assert parts[5] in routable, f"{key!r} routes a level that never projects"
        assert stcheck._TS_ENCODED.match(value), f"{key!r} -> {value!r} is not an encoded path"
    body = [ln for ln in text.splitlines() if not ln.startswith("#")]
    assert all(ln.startswith('"') and ln.endswith('"') for ln in body if ln), (
        "every route line must be a quoted key/value pair")


def test_the_drift_gate_is_wired_into_the_lane_that_owns_deploy():
    """`--check` IS the gate on the committed table's membership, and this file's shape pins
    cannot stand in for it: they hold no registers, so a table naming a route the registers not
    admit passes every one of them. gateway-ci is the workflow that triggers on `deploy/**`, so the gate
    belongs there, with the sibling register checkout it needs. FAILS IF the step is renamed away or
    the invocation drifts off `--check`."""
    wf = (_REPO / ".github" / "workflows" / "gateway-ci.yml").read_text(encoding="utf-8")
    assert "deploy/scripts/gen_ts_routes.py --check" in wf, (
        "gateway-ci must run the route-table drift gate; without it a register that moved without "
        "the table merges with both repos' CI green")
    assert "AUSMT_SURVEYS_URL" in wf, "the gate needs the sibling register checkout"
    assert "::warning::" in wf, (
        "an unset AUSMT_SURVEYS_URL must announce that the gate did not run, never pass quietly")


def test_committed_table_never_routes_a_level2_row():
    """Restated over the SHIPPED bytes: the archive's level_2 tree holds transfer functions, so
    a level2 route would assert a verified TIME SERIES for a station that has none. FAILS IF one
    appears by any path."""
    assert not [k for k in _keys(_MAP.read_text(encoding="utf-8")) if k.endswith("/level2")]


# ==================================================================================================
# The front-door directives (textual: run everywhere)
# ==================================================================================================
def _fd_text() -> str:
    return _FD_CADDY.read_text(encoding="utf-8")


def _brace_match(text: str, open_at: int) -> str:
    i = text.index("{", open_at)
    depth = 0
    for j in range(i, len(text)):
        if text[j] == "{":
            depth += 1
        elif text[j] == "}":
            depth -= 1
            if depth == 0:
                return text[i:j + 1]
    raise AssertionError("unbalanced braces")


def _canonical_body(text: str) -> str:
    m = re.search(r"\{\$AUSMT_PUBLIC_NAME\} \{", text)
    assert m, "the canonical site block must exist"
    return _brace_match(text, text.index("{", m.end() - 1))[1:-1]


def _section(text: str) -> str:
    body = _canonical_body(text)
    o, c = body.index(_SECTION_OPEN), body.index(_SECTION_CLOSE)
    assert o < c
    return body[o:body.index("\n", c) + 1]


def _strip_section(text: str) -> str:
    out, dropping = [], False
    for line in text.splitlines(keepends=True):
        if _SECTION_OPEN in line:
            dropping = True
        if not dropping:
            out.append(line)
        if _SECTION_CLOSE in line:
            dropping = False
    return "".join(out)


def test_section_sits_in_the_canonical_block_above_the_deny():
    """The hand-off section is INSIDE the canonical site block, ABOVE the @nonpublic deny and BELOW
    the path-url contract whose map it chains off, and outside the legacy render markers (both
    renderings keep it). FAILS IF it moves anywhere that changes which handle wins."""
    text = _fd_text()
    body = _canonical_body(text)
    assert _SECTION_OPEN in body and _SECTION_CLOSE in body
    assert body.index("# ---- end path-url contract") < body.index(_SECTION_OPEN), (
        "the map keys off {ausmt_pathurl_rest}, so it belongs after that section")
    assert body.index(_SECTION_CLOSE) < body.index("@nonpublic path"), (
        "the hand-off handles must sit ABOVE the @nonpublic deny")
    legacy = text[text.index("# >>> legacy-redirect"):text.index("# <<< legacy-redirect")]
    assert _SECTION_OPEN not in legacy


def test_map_keys_off_the_query_stripped_uri_and_imports_the_committed_table():
    """The mechanism: the map reads {ausmt_pathurl_rest} (the raw URI up to the first '?', declared
    by the path-url section), imports the committed table at its mount path, and defaults to EMPTY.
    The query strip is what stops a decorated link riding onto an NCI URL. `default ""` is what 404s
    an unlisted path. FAILS IF the input becomes the full URI, the import moves, or the default
    grows a value."""
    section = _section(_fd_text())
    opener = "map {ausmt_pathurl_rest} {ausmt_ts_target} {"
    assert opener in section, "the map must key off the query-stripped remainder"
    block = _brace_match(section, section.rindex("{", section.index(opener),
                                                 section.index("\n", section.index(opener))))
    assert f"import {_MAP_MOUNT}" in block, f"the map must import {_MAP_MOUNT}"
    assert re.search(r'default\s+""', block), "an unlisted path must map to EMPTY, with no fallback"


def test_known_routes_redirect_302_to_the_one_canonical_archive_host():
    """@ts_known fires only on a non-empty map result and redirects 302 to the fileServer prefix the
    ENGINE declares (_stationcheck.TS_ACCESS_PREFIX), with the map value appended. The prefix is
    hard-coded in the directive on purpose: the redirect target is then structurally confined to that
    host, so no table line can ever aim a Location somewhere else. FAILS IF the host drifts from the
    engine's constant, the matcher stops testing for empty, or the status changes."""
    section = _section(_fd_text())
    assert '@ts_known expression {ausmt_ts_target} != ""' in section
    want = f"redir {stcheck.TS_ACCESS_PREFIX}{{ausmt_ts_target}} 302"
    assert want in section, f"the redirect must be exactly {want!r}"
    assert "permanent" not in section, (
        "a hand-off is temporary by design: the archive's own path is not an AusMT contract")


def test_unlisted_paths_404_and_nothing_in_the_section_proxies():
    """@ts_prefix 404s both slash forms of the namespace, and NEITHER handle proxies: the route is
    TERMINAL at the front door, so no /go/ts/ request reaches the box and the C47 wall-2 allowlist is
    untouched by construction. FAILS IF a slash form is dropped or a reverse_proxy appears."""
    section = _section(_fd_text())
    m = re.search(r"@ts_prefix path (.+)", section)
    assert m and m.group(1).split() == ["/go/ts", "/go/ts/*"], (
        f"the namespace must be refused in both slash forms, got {m and m.group(1)!r}")
    assert 'respond "not found" 404' in section
    assert "reverse_proxy" not in section, "a hand-off route must never reach the box"


def test_compose_and_installer_carry_the_table_into_the_config():
    """The table is part of the CONFIG: compose mounts it read-only at the import path, and the
    installer's validate step mounts it too (caddy validate FAILS on a missing import, which is the
    point). FAILS IF either mount is dropped - the edge would then refuse to start, or validate would
    pass on a config the container cannot load."""
    assert f"./ts-routes.map:{_MAP_MOUNT}:ro" in _COMPOSE.read_text(encoding="utf-8")
    install = _INSTALL.read_text(encoding="utf-8")
    assert f'"$HERE/ts-routes.map:{_MAP_MOUNT}:ro"' in install, (
        "the validate step must mount the table it imports")
    assert "ts-routes.map ]" in install and "will 404" in install, (
        "a missing table must degrade to an EMPTY table (every route 404s), not a failed deploy")


def test_doctor_carries_the_ts_routes_leg():
    """doctor.sh source pins: the leg hash-compares the container-mounted table against the repo
    copy, requires a 302 to the table's own NCI Location on an open route, requires a 404 on a route
    the table does not name, and skips cleanly on an unreachable edge. The behavioural proof is
    sh-driven in test_frontdoor_doctor_sh.py. FAILS IF any of the three facts is dropped."""
    src = _DOCTOR.read_text(encoding="utf-8")
    leg = src.split("check_ts_routes()")[1].split("check_tailscale()")[0]
    assert "sha256sum /etc/caddy/ts-routes.map" in leg, "the mounted table must be hash-compared"
    assert '"302"' in leg and stcheck.TS_ACCESS_PREFIX in leg, (
        "the open probe must require a 302 to the archive host")
    assert '"404"' in leg, "the unlisted probe must require a 404"
    assert "ts-routes: skipped" in leg, "an unreachable edge must skip cleanly, not FAIL"
    assert "check_ts_routes" in src.split("run_report()")[1], "the leg must run in the report"


def test_runbook_documents_the_route_step_and_the_rollback():
    """RUNBOOK pins: the operator can find how the table ships, that it goes out BEFORE the data (a
    station that stops being open has to lose its route first), and the one-line withdrawal. FAILS IF
    the published operating procedure loses any of them."""
    rb = _RUNBOOK.read_text(encoding="utf-8")
    assert "ts-routes.map" in rb, "the runbook must name the route table"
    assert "/go/ts/" in rb, "the runbook must name the route shape"
    assert "before the data" in rb.lower(), "the order rule must be stated where the operator reads it"
    assert "404" in rb and "gen_ts_routes.py" in rb, "the rollback and the regenerate must be findable"


# ==================================================================================================
# Runtime pins: a REAL Caddy over the shipped directives (CI class; textual pins stand in locally)
# ==================================================================================================
def _free_port() -> int:
    s = socket.socket()
    s.bind(("127.0.0.1", 0))
    p = s.getsockname()[1]
    s.close()
    return p


def _wait_port(port: int, timeout: float = 10.0) -> None:
    end = time.time() + timeout
    while time.time() < end:
        try:
            with socket.create_connection(("127.0.0.1", port), timeout=0.2):
                return
        except OSError:
            time.sleep(0.05)
    raise AssertionError(f"port {port} never came up")


def _hermetic(text: str, td: Path, listen_port: int, stub_port: int, mappath: Path) -> str:
    """The shipped composition on one local http port, with the map import repointed at the fixture
    table. Everything else - the matchers, the map, the redirect, the 404 - is the shipped text."""
    text = text.replace("{$AUSMT_PUBLIC_NAME} {", f"http://canonical.test:{listen_port} {{")
    text = text.replace("{$AUSMT_LEGACY_REDIRECT_NAME} {", f"http://legacy.test:{listen_port} {{")
    text = text.replace("{$AUSMT_PUBLIC_NAME}", "canonical.test")
    text = text.replace("{$AUSMT_BOX_READER_UPSTREAM}", f"127.0.0.1:{stub_port}")
    text = text.replace("{$AUSMT_ACME_EMAIL}", "test@example.org")
    text = re.sub(r"output file \S+", f"output file {(td / 'access.json').as_posix()}", text)
    text = text.replace("admin unix//run/caddy-admin.sock", "admin off")
    text = text.replace("admin off\n", "admin off\n\tauto_https off\n", 1)
    return text.replace(f"import {_MAP_MOUNT}", f"import {mappath.as_posix()}")


def _stub_cfg(port: int) -> str:
    return ("{\n\tadmin off\n\tauto_https off\n}\n"
            + f":{port} {{\n\trespond \"STUB {{http.request.uri}}\" 200\n}}\n")


def _run_caddy(cfg_text: str, td: Path, name: str) -> subprocess.Popen:
    cfgpath = td / f"{name}.caddy"
    cfgpath.write_text(cfg_text, encoding="utf-8")
    v = subprocess.run(["caddy", "validate", "--adapter", "caddyfile", "--config", str(cfgpath)],
                       capture_output=True, text=True)
    assert v.returncode == 0, f"composed {name} config invalid:\n{v.stdout}\n{v.stderr}"
    return subprocess.Popen(["caddy", "run", "--adapter", "caddyfile", "--config", str(cfgpath)],
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE)


def _stop(proc: subprocess.Popen) -> None:
    proc.terminate()
    try:
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        proc.kill()


def _get(port: int, path: str, host: str = "canonical.test") -> tuple:
    """(status, location-or-None, body) without following redirects."""
    req = urllib.request.Request(f"http://127.0.0.1:{port}{path}", headers={"Host": host})

    class _NoRedirect(urllib.request.HTTPRedirectHandler):
        def redirect_request(self, *a, **k):  # noqa: ARG002
            return None

    try:
        r = urllib.request.build_opener(_NoRedirect).open(req, timeout=5)
        hdrs, body, st = dict(r.headers), r.read().decode("utf-8", "replace"), r.status
    except urllib.error.HTTPError as e:
        hdrs, body, st = dict(e.headers), e.read().decode("utf-8", "replace"), e.code
    return st, {k.lower(): v for k, v in hdrs.items()}.get("location"), body


class _Edge:
    """A running hermetic edge over one fixture route table."""

    def __init__(self, td: Path, mappath: Path, text: str | None = None):
        self.td, self.stub_port, self.port = td, _free_port(), _free_port()
        self.stub = _run_caddy(_stub_cfg(self.stub_port), td, f"stub-{self.port}")
        cfg = _hermetic(text or _fd_text(), td, self.port, self.stub_port, mappath)
        self.fd = _run_caddy(cfg, td, f"frontdoor-{self.port}")
        _wait_port(self.stub_port)
        _wait_port(self.port)

    def get(self, path: str, host: str = "canonical.test"):
        return _get(self.port, path, host)

    def stop(self):
        _stop(self.fd)
        _stop(self.stub)


@pytest.fixture()
def gated(tmp_path):
    """The edge serving the GATED table: only the open, verified, routable row is in it."""
    if not _HAS_CADDY:
        pytest.skip("no caddy binary on PATH - runtime pins run in CI (gateway-ci)")
    mappath, _text = _generate(tmp_path)
    edge = _Edge(tmp_path, mappath)
    try:
        yield edge
    finally:
        edge.stop()


@pytest.fixture()
def ungated(tmp_path):
    """SENSITIVITY CONTROL edge: the same corpus with the embargoed survey flipped OPEN, so the
    withheld station's row IS in the table. Every 404 pin below has its resolving twin here."""
    if not _HAS_CADDY:
        pytest.skip("no caddy binary on PATH - runtime pins run in CI (gateway-ci)")
    work = tmp_path / "control"
    work.mkdir()
    mappath, _text = _generate(work, held_level="open")
    edge = _Edge(work, mappath)
    try:
        yield edge
    finally:
        edge.stop()


@pytest.mark.skipif(not _HAS_CADDY, reason="no caddy binary on PATH - runtime pins run in CI (gateway-ci)")
def test_runtime_mapped_route_302s_to_the_exact_encoded_nci_location(gated):
    """RUNTIME, the hand-off itself. A mapped route answers 302 with the EXACT NCI Location,
    percent-encoding intact - the corpus vector carries a space and brackets, and only the encoded
    form answers 200 at the archive. FAILS IF the status, the host, or one escape byte moves."""
    st, loc, _ = gated.get("/go/ts/open-survey/OPEN1/raw_packed")
    assert st == 302, f"a mapped route must 302, got {st}"
    assert loc == stcheck.TS_ACCESS_PREFIX + _ENC_ZIP, f"exact Location required, got {loc!r}"


@pytest.mark.skipif(not _HAS_CADDY, reason="no caddy binary on PATH - runtime pins run in CI (gateway-ci)")
def test_runtime_withheld_station_route_404s(gated, ungated):
    """RUNTIME, R5. An embargoed survey's station has a verified register row and (correctly)
    projects has_time_series, so its /go/ts/ path is fully enumerable from mtcat.json - and it must
    404. SENSITIVITY CONTROL: the SAME path on the edge whose survey is open resolves 302, so the
    404 measures the access gate rather than a typo in the path."""
    st, loc, _ = gated.get("/go/ts/held-survey/HELD1/raw_packed")
    assert st == 404 and loc is None, f"a withheld station's route must 404, got {st} {loc!r}"
    st, loc, _ = ungated.get("/go/ts/held-survey/HELD1/raw_packed")
    assert st == 302 and loc == stcheck.TS_ACCESS_PREFIX + "arch/HELD1.zip", (
        f"control: the same path must resolve when the row is admitted, got {st} {loc!r}")


@pytest.mark.skipif(not _HAS_CADDY, reason="no caddy binary on PATH - runtime pins run in CI (gateway-ci)")
def test_runtime_pending_and_retired_and_level2_routes_404(gated):
    """RUNTIME, D9 and D19. A `review: pending` row is an adjudication-queue entry, a retired row is
    evidence of a resource that ceased to exist, and a level2 row is a transfer function - none is a
    published time series, so none resolves. SENSITIVITY CONTROL: the open row on the SAME edge
    resolves, so the edge is answering and the 404s are the gate."""
    for path in ("/go/ts/open-survey/PEND1/raw_packed", "/go/ts/open-survey/RETIRE1/raw_packed",
                 "/go/ts/open-survey/OPEN1/level2"):
        st, loc, _ = gated.get(path)
        assert st == 404 and loc is None, f"{path} must 404, got {st} {loc!r}"
    assert gated.get("/go/ts/open-survey/OPEN1/raw_packed")[0] == 302, (
        "control: the admitted row on this same edge must resolve")


@pytest.mark.skipif(not _HAS_CADDY, reason="no caddy binary on PATH - runtime pins run in CI (gateway-ci)")
def test_runtime_bare_prefix_and_partial_paths_404(gated):
    """RUNTIME, the namespace. A bare /go/ts, /go/ts/ and any partial path 404 - there is nothing to
    browse and no directory to enumerate. SENSITIVITY CONTROL: a full mapped path on the same edge
    resolves, so the 404s are the matcher rather than a dead listener."""
    for path in ("/go/ts", "/go/ts/", "/go/ts/open-survey", "/go/ts/open-survey/OPEN1"):
        st, loc, _ = gated.get(path)
        assert st == 404 and loc is None, f"{path} must 404, got {st} {loc!r}"
    assert gated.get("/go/ts/open-survey/OPEN1/raw_packed")[0] == 302


@pytest.mark.skipif(not _HAS_CADDY, reason="no caddy binary on PATH - runtime pins run in CI (gateway-ci)")
def test_runtime_a_query_never_reaches_the_location(gated):
    """RUNTIME, the open-redirect refusal. The map keys off the QUERY-STRIPPED remainder, so a
    decorated link resolves to the same clean NCI Location and an attacker-supplied `?u=` cannot ride
    onto it or replace it. SENSITIVITY CONTROL: the request still 302s (the query is dropped from the
    TARGET, not treated as an unknown route), and the undecorated path gives the identical Location.
    FAILS IF any query byte appears in the Location."""
    clean = gated.get("/go/ts/open-survey/OPEN1/raw_packed")[1]
    for query in ("?u=https://evil.example", "?utm=1&v=2", "?u=https%3A%2F%2Fevil.example"):
        st, loc, _ = gated.get(f"/go/ts/open-survey/OPEN1/raw_packed{query}")
        assert st == 302, f"{query}: the route must still resolve, got {st}"
        assert loc == clean, f"{query}: the query must not reach the Location, got {loc!r}"
        assert "evil.example" not in (loc or "") and "?" not in (loc or "")
    st, loc, _ = gated.get("/go/ts/held-survey/HELD1/raw_packed?u=https://evil.example")
    assert st == 404 and loc is None, "a query cannot resurrect a suppressed route either"


@pytest.mark.skipif(not _HAS_CADDY, reason="no caddy binary on PATH - runtime pins run in CI (gateway-ci)")
def test_runtime_the_namespace_does_not_disturb_the_reader_or_the_walls(gated):
    """RUNTIME, the neighbours. /go/ts/ is a new top-level prefix: the reader catch-all, the path-url
    contract and the @nonpublic deny must all behave exactly as before. FAILS IF the new handles
    swallow a neighbouring path (handles are mutually exclusive in SOURCE order, so a widened matcher
    would show up here)."""
    assert gated.get("/data/mtcat.json")[2].startswith("STUB /data/mtcat.json")
    assert gated.get("/go/other")[2].startswith("STUB /go/other")
    assert gated.get("/surveys/vulcan-2022")[0] == 200 and \
            gated.get("/surveys/vulcan-2022")[2].startswith("STUB /surveys/vulcan-2022")
    assert gated.get("/gateway/queue")[0] == 404


@pytest.mark.skipif(not _HAS_CADDY, reason="no caddy binary on PATH - runtime pins run in CI (gateway-ci)")
def test_runtime_redproof_without_the_section_the_namespace_falls_through(tmp_path):
    """RED-PROOF. With the whole hand-off section STRIPPED (the pre-change canonical block), a
    /go/ts/ path is NOT redirected and NOT refused: it falls through to the reader catch-all and
    reaches the stub. Proves the section is load-bearing, so the 404 pins above are measuring the
    matchers rather than a namespace nothing ever handled."""
    if not _HAS_CADDY:
        pytest.skip("no caddy binary on PATH - runtime pins run in CI (gateway-ci)")
    mappath, _text = _generate(tmp_path)
    edge = _Edge(tmp_path, mappath, text=_strip_section(_fd_text()))
    try:
        st, loc, body = edge.get("/go/ts/open-survey/OPEN1/raw_packed")
        assert st == 200 and loc is None and "STUB /go/ts/" in body, (
            f"red-proof failed: without the section the namespace should fall through, got "
            f"{st} {loc!r} {body!r}")
    finally:
        edge.stop()
