"""The favicon and the app icons are the same mark, and every surface links them.

The favicon concept sheet asks for the AusMT mark in the browser tab, recognisable as
Australia at 16 px. That is one requirement with two halves:

  * ONE GEOMETRY. The favicon is not a second drawing. It is the same 180 dot lattice as the header
    mark and the logo lockups, differing only in the declared radius band: the 16 px band against the
    presentation ratio (0.78 and 0.44 as brand.json declares them today). The dots close into a solid
    silhouette at tab size, which is what a favicon should do, and dissolve into a haze if they do
    not. The pin rederives the favicon's circle count and its radius from contract/brand.json rather
    than trusting the file OR this sentence, so the band can move without stranding the test.
  * EVERY SURFACE LINKS IT. Before this module the generated entity pages shipped no icon link at all,
    so all 2,655 of them asked the server for /favicon.ico and got a 404 on every visit. They link the
    same file the static pages do, from the same origin.

The file KEEPS ITS NAME (vendor/favicon.svg) so the existing link tags on index, about, releases and
add-survey did not have to move; what changed is that it is now generated from the mark instead of
being the hand-drawn MT-curve placeholder. It is transparent, so the one file works on a light and a
dark browser chrome without a second variant.

NO WEB MANIFEST this module (architect default): 192 and 512 are generated and served so a manifest can
be added later, but an installable PWA is its own decision and its own rule.
"""
import json
import re
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]          # portal/
REPO = ROOT.parent
BRAND_JSON = REPO / "contract" / "brand.json"
FAVICON = ROOT / "vendor" / "favicon.svg"
BRAND_DIR = ROOT / "vendor" / "brand"
PAGES_PY = REPO / "engine" / "extract" / "_pages.py"

ICONS = {"ausmt-icon-180.png": 180, "ausmt-icon-192.png": 192, "ausmt-icon-512.png": 512}
# The static portal documents that carry the site chrome. 404.html is deliberately not in scope: it
# is a bare error document with no header. brand.html is here because this workflow created it,
# shipping both icon links; it was not in the contract's list only because it did not exist
# when that list was written, and leaving it out would mean the one page the workflow added is the one
# page whose icon links nothing holds.
CHROME_PAGES = ("index.html", "about.html", "add-survey.html", "brand.html", "releases.html")


def _brand():
    return json.loads(BRAND_JSON.read_text(encoding="utf-8"))


def _radius_ratio(doc, size):
    r = doc["geometry"]["radius_ratio_by_output_size"]
    for band in r["bands"]:
        if size <= band["max_px"]:
            return band["ratio"]
    return r["above"]


def test_the_favicon_is_the_canonical_mark_at_the_small_size_band():
    """FAILS IF the favicon stops being the shared lattice, or stops using the enlarged small-size
    radius. Both halves matter: a second geometry breaks the one-mark rule, and the presentation
    radius at 16 px is the version that dissolves into an unreadable haze."""
    doc = _brand()
    svg = FAVICON.read_text(encoding="utf-8")
    circles = re.findall(r'<circle cx="([-\d.]+)" cy="([-\d.]+)" r="([-\d.]+)"/>', svg)
    assert len(circles) == doc["geometry"]["dot_count"], (
        f"the favicon must carry the same {doc['geometry']['dot_count']} dots as the mark, "
        f"found {len(circles)}")
    radii = {c[2] for c in circles}
    assert len(radii) == 1, f"one radius across the lattice, got {sorted(radii)}"
    bb = doc["geometry"]["bbox"]
    span = max(bb["col_max"] - bb["col_min"] + 1, bb["row_max"] - bb["row_min"] + 1)
    pitch = doc["proportions"]["mark_units"] * (1 - 2 * doc["geometry"]["pad_fraction"]) / span
    want = pitch * _radius_ratio(doc, doc["geometry"]["svg_nominal_size_px"]["favicon"])
    assert abs(float(radii.pop()) - want) < 0.05, (
        "the favicon must use the 16 px radius band from brand.json, not the presentation radius")


def test_the_favicon_is_transparent_and_carries_no_second_drawing():
    """FAILS IF the favicon regrows a background plate or keeps any of the retired placeholder art.
    One transparent variant works on a light and a dark browser chrome; a plate picks a side."""
    svg = FAVICON.read_text(encoding="utf-8")
    assert "<rect" not in svg, "the favicon is transparent; a plate would pick one browser theme"
    for stale in ("<polyline", "MT sounding curve", "#10161C"):
        assert stale not in svg, f"the retired placeholder favicon art is still present: {stale!r}"
    assert "GENERATED by portal/tools/gen_brand.py" in svg, "the favicon must be generated, not drawn"


# THE RASTER ICONS SIT ON A NAVY DISC. A search engine crops a favicon to a circle and puts its own white
# disc behind a transparent one, which washes out the mark's pale end; so every raster icon is the mark
# on the site's own navy, inset so it sits inside the inscribed circle, and 20 percent brighter than the
# vector mark so the gradient reads at 16px. The SVG tab icon stays transparent: a tab does not crop.
NAVY = (0x11, 0x18, 0x2D, 255)


def _mark_pixels_inside_the_circle(im):
    w, h = im.size
    cx, cy, r = (w - 1) / 2, (h - 1) / 2, w / 2
    px = im.load()
    outside = [(x, y) for x in range(w) for y in range(h)
               if px[x, y][:3] != NAVY[:3] and ((x - cx) ** 2 + (y - cy) ** 2) ** 0.5 > r]
    return outside


@pytest.mark.parametrize("name,size", sorted(ICONS.items()))
def test_every_app_icon_is_the_mark_on_a_navy_disc_at_the_declared_size(name, size):
    """FAILS IF an app icon is missing, is not square at its declared size, loses its navy ground, or
    lets any mark pixel outside the inscribed circle a search engine's crop would cut."""
    from PIL import Image
    path = BRAND_DIR / name
    assert path.is_file(), f"vendor/brand/{name} must be committed"
    with Image.open(path) as im:
        assert im.mode == "RGBA", f"{name}: app icons are RGBA, got {im.mode}"
        assert im.size == (size, size), f"{name}: must be {size}x{size}, got {im.size}"
        for corner in ((0, 0), (size - 1, 0), (0, size - 1), (size - 1, size - 1)):
            assert im.getpixel(corner) == NAVY, f"{name}: the corner {corner} must be the navy ground"
        stray = _mark_pixels_inside_the_circle(im)
        assert not stray, f"{name}: {len(stray)} mark pixel(s) lie outside the inscribed circle, e.g. {stray[:3]}"


def test_the_raster_icons_are_generated_from_named_constants():
    """The disc colour, the inset and the brightness lift are named in the generator so they can be
    read and pinned; the ICO frames and the app icons all come from one raster_icon() renderer."""
    ns = _tool_namespace()
    assert ns["RASTER_ICON_BACKGROUND"].upper() == "#11182D"
    assert abs(ns["RASTER_ICON_INSET"] - 0.78) < 1e-9
    assert abs(ns["RASTER_ICON_BRIGHTNESS"] - 1.20) < 1e-9
    from PIL import Image
    size = 48
    mark = ns["png_mark"](round(size * ns["RASTER_ICON_INSET"])).convert("RGBA")
    plain = Image.new("RGBA", (size, size), NAVY)
    plain.alpha_composite(mark, ((size - mark.width) // 2, (size - mark.height) // 2))
    disc = ns["raster_icon"](size).convert("RGBA")

    def mean(im):
        return sum(sum(p[:3]) for p in im.getdata()) / (size * size)

    assert mean(disc) > mean(plain) * 1.03, \
        "the mark on the disc must render brighter than the same mark composited without the lift"


# EVERY SURFACE LINKS THE SAME THREE ICONS, IN THE SAME FORM. The static tier and the emitted pages
# state one block, root-absolute so a document served at /surveys/<slug> resolves it, and each href
# carries the eight hex digits its own file's bytes hash to. The version query is what reaches a
# returning visitor: /vendor/* is served with a thirty day cache, so a regenerated icon under an
# unchanged URL is answered from that cache and the old mark stays in the tab.
SHIPPED_PAGES = CHROME_PAGES + ("404.html",)
ICON_FILES = {
    "/favicon.ico": ROOT / "favicon.ico",
    "/vendor/favicon.svg": ROOT / "vendor" / "favicon.svg",
    "/vendor/brand/ausmt-icon-180.png": BRAND_DIR / "ausmt-icon-180.png",
}


def _version(href):
    """The generator's own picture hash of the COMMITTED file the href names."""
    ns = _tool_namespace()
    return ns["picture_digest"](href, (ROOT / href.lstrip("/")).read_bytes())




def _icon_block(sep="\n"):
    """The three icon links, in the declared order and form, at today's content hashes."""
    return sep.join((
        f'<link rel="icon" href="/favicon.ico?v={_version("/favicon.ico")}" sizes="any">',
        f'<link rel="icon" href="/vendor/favicon.svg?v={_version("/vendor/favicon.svg")}"'
        ' type="image/svg+xml">',
        '<link rel="apple-touch-icon" href="/vendor/brand/ausmt-icon-180.png'
        f'?v={_version("/vendor/brand/ausmt-icon-180.png")}">',
    ))


@pytest.mark.parametrize("name", SHIPPED_PAGES)
def test_every_shipped_page_carries_the_versioned_icon_block(name):
    """FAILS IF a page loses an icon link, keeps an unversioned href, carries a stale hash, or writes
    the three in a different order or a relative form. 404.html is in scope with the rest: it is the
    document a browser lands on for any unknown path, and a relative href there resolves against that
    path rather than against the site root."""
    text = (ROOT / name).read_text(encoding="utf-8")
    assert _icon_block() in text, (
        f"{name}: the head must carry the three icon links at their current content hashes:\n"
        + _icon_block())


@pytest.mark.parametrize("name", SHIPPED_PAGES + ("_pages.py",))
def test_no_surface_links_a_mask_icon(name):
    """FAILS IF a pinned-tab mask icon appears anywhere. Safari's mask wants a single-colour SVG it
    fills with the reader's accent, and the mark is a four colour lattice: shipping one would put a
    flat silhouette of Australia in a pinned tab and call it the brand."""
    text = (PAGES_PY if name == "_pages.py" else ROOT / name).read_text(encoding="utf-8")
    assert "mask-icon" not in text, f"{name}: no surface may link a pinned-tab mask icon"


def test_the_generated_pages_link_the_same_versioned_block_same_origin():
    """FAILS IF the pages' shell stops emitting the block, emits it anywhere but the portal's own
    origin, or drifts from the static tier's copy. The hrefs are absolute because a page served at
    /surveys/<slug> cannot resolve a relative vendor path."""
    src = PAGES_PY.read_text(encoding="utf-8")
    for tag in _icon_block().split("\n"):
        assert tag in src, f"engine/extract/_pages.py must emit {tag}"
    hrefs = re.findall(r'<link rel="(?:icon|apple-touch-icon)" href="([^"]+)"', src)
    assert hrefs, "the pages' shell must emit icon links"
    for href in hrefs:
        assert href.startswith("/") and not href.startswith("//"), (
            f"the pages' icon links must be same-origin portal paths, got {href}")
        assert "://" not in href and not href.startswith("data:"), (
            f"an icon href is same-origin only; {href} is not")


def test_the_version_query_is_the_hash_of_the_file_it_names():
    """FAILS IF a version query stops being the picture hash of the file actually served at that path,
    read back from the committed bytes. A query that is any other token still busts a cache once and
    then lies: the next regeneration leaves it unchanged and the stale icon comes back. The hash is of
    the decoded picture, not the encoding, so CI and a checkout agree whatever their PNG encoder does."""
    for name in SHIPPED_PAGES + ("_pages.py",):
        text = (PAGES_PY if name == "_pages.py" else ROOT / name).read_text(encoding="utf-8")
        for href, ver in re.findall(
                r'<link rel="(?:icon|apple-touch-icon)" href="([^"?]+)\?v=([^"]+)"', text):
            assert href in ICON_FILES, f"{name}: {href} is not one of the three declared icons"
            assert ver == _version(href), (
                f"{name}: {href} carries v={ver}, but that file's picture hashes to {_version(href)}")


def test_the_drift_gate_fails_on_a_stale_version_query():
    """FAILS IF the generator does not own the version queries. A hash written by hand goes stale the
    first time an icon is regenerated, and the whole point of the query is that it cannot."""
    target = ROOT / "index.html"
    original = target.read_bytes()
    try:
        target.write_text(
            original.decode("utf-8").replace(
                f'/favicon.ico?v={_version("/favicon.ico")}', "/favicon.ico?v=00000000"),
            encoding="utf-8")
        r = subprocess.run([sys.executable, str(TOOL), "--check"], capture_output=True,
                           text=True, encoding="utf-8", cwd=str(REPO))
        assert r.returncode == 1, \
            f"the gate must fail on a stale version query, it returned {r.returncode}"
        assert "index.html" in r.stdout + r.stderr, \
            f"the gate must name the page that drifted:\n{r.stdout}\n{r.stderr}"
    finally:
        target.write_bytes(original)


def test_no_web_manifest_was_smuggled_in():
    """The architect's default, pinned so it stays a decision rather than a drift. 192 and 512 exist
    for a future manifest; shipping one would make the portal installable to a home screen, which is
    a product decision that has not been made. FAILS IF a manifest link appears on any chrome page."""
    for name in CHROME_PAGES:
        text = (ROOT / name).read_text(encoding="utf-8")
        assert 'rel="manifest"' not in text, (
            f"{name}: an installable-PWA manifest is its own decision, not a side effect of the "
            "icon work")


# THE ROOT ICON. A browser that reads no SVG icon link asks the site root for /favicon.ico by name,
# so the file has to exist at the root of the portal image and be the same lattice as everything
# else. It is generated, multi-size, and held by the same drift gate as the other exports.
FAVICON_ICO = ROOT / "favicon.ico"
TOOL = ROOT / "tools" / "gen_brand.py"
ICO_SIZES = (16, 32, 48)


def _tool_namespace():
    """The generator's own constants and renderers, read from its CURRENT source.

    Compiled and run rather than imported for the reason tests/test_brand_exports.py gives: an import
    is answered from __pycache__ whenever the stamped source mtime matches to the second."""
    ns = {"__file__": str(TOOL), "__name__": "gen_brand_pin"}
    exec(compile(TOOL.read_text(encoding="utf-8"), str(TOOL), "exec"), ns)
    return ns


def test_the_root_icon_exists_and_carries_three_sizes():
    """FAILS IF the portal ships no /favicon.ico, or if the file stops carrying all three entries.
    A browser that ignores the SVG icon link requests this path by name, and nothing else on the site
    answers it."""
    from PIL import Image
    assert FAVICON_ICO.is_file(), \
        "portal/favicon.ico must be committed; the portal image serves portal/ at the site root"
    with Image.open(FAVICON_ICO) as ico:
        assert ico.format == "ICO", f"the root icon must decode as an ICO, got {ico.format!r}"
        got = sorted(s[0] for s in ico.info["sizes"])
        assert got == list(ICO_SIZES), \
            f"the root icon must carry {list(ICO_SIZES)} px entries, got {got}"


def test_every_root_icon_entry_is_the_generated_mark_at_its_own_size():
    """FAILS IF an entry stops being the navy-disc icon the generator renders at that size. Each entry
    is rendered at its own size, so the 16 px frame carries the small-size radius band rather than a
    resampled copy of the 48 px one."""
    from PIL import Image
    ns = _tool_namespace()
    with Image.open(FAVICON_ICO) as ico:
        for size in ICO_SIZES:
            ico.size = (size, size)
            assert ico.convert("RGBA").tobytes() == ns["raster_icon"](size).convert("RGBA").tobytes(), \
                f"the {size} px entry is not the generator's navy-disc icon rendered at {size} px"


def test_the_root_icon_is_declared_and_the_drift_gate_compares_it():
    """FAILS IF the icon is not a declared output, or if the gate lists it without comparing it: a
    generated file the gate does not compare is a file anyone can hand-edit. The teeth are the
    perturbation, which is what tells a listing apart from a comparison."""
    ns = _tool_namespace()
    assert "portal/favicon.ico" in [row[0] for row in ns["_OUTPUT_INDEX"]], \
        "portal/favicon.ico must be a declared output, or the gate never looks at it"
    from PIL import Image
    original = FAVICON_ICO.read_bytes()
    try:
        frames = []
        with Image.open(FAVICON_ICO) as ico:
            for size in ICO_SIZES:
                ico.size = (size, size)
                frames.append(ico.convert("RGBA"))
        frames[0].putpixel((0, 0), (255, 0, 0, 255))
        frames[-1].save(FAVICON_ICO, "ICO", sizes=[(s, s) for s in ICO_SIZES],
                        append_images=frames[:-1])
        r = subprocess.run([sys.executable, str(TOOL), "--check"], capture_output=True,
                           text=True, encoding="utf-8", cwd=str(REPO))
        assert r.returncode == 1, \
            f"the gate must fail on a perturbed favicon.ico, it returned {r.returncode}"
        assert "favicon.ico" in r.stdout + r.stderr, \
            f"the gate must name the file that drifted:\n{r.stdout}\n{r.stderr}"
    finally:
        FAVICON_ICO.write_bytes(original)


def test_two_runs_of_the_generator_write_the_same_root_icon():
    """FAILS IF the icon carries a timestamp or any other per-run byte. A regenerated icon that
    differs on identical inputs makes every rebuild a spurious diff and defeats the drift gate it is
    held by."""
    ns = _tool_namespace()
    assert ns["ico_bytes"]() == ns["ico_bytes"](), \
        "two renders of the root icon must be byte-identical"
    assert FAVICON_ICO.read_bytes() == ns["ico_bytes"](), \
        "the committed root icon must be the bytes the generator writes today"
