"""The favicon and the app icons are the same mark, and every surface links them.

The favicon concept sheet asks for the AusMT mark in the browser tab, recognisable as
Australia at 16 px. That is one requirement with two halves:

  * ONE GEOMETRY. The favicon is not a second drawing. It is the same 180 dot lattice as the header
    mark and the logo lockups, differing only in the declared radius band: the 16 px band against the
    presentation ratio (0.78 and 0.44 as brand.json declares them today). The dots close into a solid
    silhouette at tab size, which is what a favicon should do, and dissolve into a haze if they do
    not. The pin rederives the favicon's circle count and its radius from contract/brand.json rather
    than trusting the file OR this sentence, so the band can move without stranding the test.
  * EVERY SURFACE LINKS IT. Before this module the generated entity pages shipped no icon link at all,
    so all 2,655 of them asked the server for /favicon.ico and got a 404 on every visit. They link the
    same file the static pages do, from the same origin.

The file KEEPS ITS NAME (vendor/favicon.svg) so the existing link tags on index, about, releases and
add-survey did not have to move; what changed is that it is now generated from the mark instead of
being the hand-drawn MT-curve placeholder. It is transparent, so the one file works on a light and a
dark browser chrome without a second variant.

NO WEB MANIFEST this module (architect default): 192 and 512 are generated and served so a manifest can
be added later, but an installable PWA is its own decision and its own rule.
"""
import json
import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]          # portal/
REPO = ROOT.parent
BRAND_JSON = REPO / "contract" / "brand.json"
FAVICON = ROOT / "vendor" / "favicon.svg"
BRAND_DIR = ROOT / "vendor" / "brand"
PAGES_PY = REPO / "engine" / "extract" / "_pages.py"

ICONS = {"ausmt-icon-180.png": 180, "ausmt-icon-192.png": 192, "ausmt-icon-512.png": 512}
# The static portal documents that carry the site chrome. 404.html is deliberately not in scope: it
# is a bare error document with no header. brand.html is here because this workflow created it,
# shipping both icon links; it was not in the contract's list only because it did not exist
# when that list was written, and leaving it out would mean the one page the workflow added is the one
# page whose icon links nothing holds.
CHROME_PAGES = ("index.html", "about.html", "add-survey.html", "brand.html", "releases.html")


def _brand():
    return json.loads(BRAND_JSON.read_text(encoding="utf-8"))


def _radius_ratio(doc, size):
    r = doc["geometry"]["radius_ratio_by_output_size"]
    for band in r["bands"]:
        if size <= band["max_px"]:
            return band["ratio"]
    return r["above"]


def test_the_favicon_is_the_canonical_mark_at_the_small_size_band():
    """FAILS IF the favicon stops being the shared lattice, or stops using the enlarged small-size
    radius. Both halves matter: a second geometry breaks the one-mark rule, and the presentation
    radius at 16 px is the version that dissolves into an unreadable haze."""
    doc = _brand()
    svg = FAVICON.read_text(encoding="utf-8")
    circles = re.findall(r'<circle cx="([-\d.]+)" cy="([-\d.]+)" r="([-\d.]+)"/>', svg)
    assert len(circles) == doc["geometry"]["dot_count"], (
        f"the favicon must carry the same {doc['geometry']['dot_count']} dots as the mark, "
        f"found {len(circles)}")
    radii = {c[2] for c in circles}
    assert len(radii) == 1, f"one radius across the lattice, got {sorted(radii)}"
    bb = doc["geometry"]["bbox"]
    span = max(bb["col_max"] - bb["col_min"] + 1, bb["row_max"] - bb["row_min"] + 1)
    pitch = doc["proportions"]["mark_units"] * (1 - 2 * doc["geometry"]["pad_fraction"]) / span
    want = pitch * _radius_ratio(doc, doc["geometry"]["svg_nominal_size_px"]["favicon"])
    assert abs(float(radii.pop()) - want) < 0.05, (
        "the favicon must use the 16 px radius band from brand.json, not the presentation radius")


def test_the_favicon_is_transparent_and_carries_no_second_drawing():
    """FAILS IF the favicon regrows a background plate or keeps any of the retired placeholder art.
    One transparent variant works on a light and a dark browser chrome; a plate picks a side."""
    svg = FAVICON.read_text(encoding="utf-8")
    assert "<rect" not in svg, "the favicon is transparent; a plate would pick one browser theme"
    for stale in ("<polyline", "MT sounding curve", "#10161C"):
        assert stale not in svg, f"the retired placeholder favicon art is still present: {stale!r}"
    assert "GENERATED by portal/tools/gen_brand.py" in svg, "the favicon must be generated, not drawn"


@pytest.mark.parametrize("name,size", sorted(ICONS.items()))
def test_every_app_icon_is_square_transparent_and_the_declared_size(name, size):
    """FAILS IF an app icon is missing, is not square at its declared size, or loses transparency.
    They come from the same lattice as everything else; only the pixel size differs."""
    from PIL import Image
    path = BRAND_DIR / name
    assert path.is_file(), f"vendor/brand/{name} must be committed"
    with Image.open(path) as im:
        assert im.mode == "RGBA", f"{name}: app icons are transparent (RGBA), got {im.mode}"
        assert im.size == (size, size), f"{name}: must be {size}x{size}, got {im.size}"
        assert im.getpixel((0, 0))[3] == 0, f"{name}: the corner must be transparent"


@pytest.mark.parametrize("name", CHROME_PAGES)
def test_every_chrome_page_links_the_favicon_and_the_apple_touch_icon(name):
    """FAILS IF a static portal page loses either icon link. The favicon link already existed and
    keeps its href (the file kept its name); the apple-touch-icon is new, and without it an iOS
    home-screen shortcut renders a screenshot of the page instead of the mark."""
    text = (ROOT / name).read_text(encoding="utf-8")
    assert '<link rel="icon" href="vendor/favicon.svg" type="image/svg+xml">' in text, \
        f"{name}: the favicon link must stay as it is"
    assert '<link rel="apple-touch-icon" href="vendor/brand/ausmt-icon-180.png">' in text, \
        f"{name}: an apple-touch-icon must point at the 180 px app icon"


def test_the_generated_pages_link_both_icons_same_origin():
    """FAILS IF the static pages' shell stops emitting the icon links, or emits them anywhere but the
    portal's own origin. Every entity page asked for /favicon.ico and got a 404 before this module; the
    links are absolute because a page served at /surveys/<slug> cannot resolve a relative vendor path."""
    src = PAGES_PY.read_text(encoding="utf-8")
    for tag in ('<link rel="icon" href="/vendor/favicon.svg" type="image/svg+xml">',
                '<link rel="apple-touch-icon" href="/vendor/brand/ausmt-icon-180.png">'):
        assert tag in src, f"engine/extract/_pages.py must emit {tag}"
    hrefs = re.findall(r'<link rel="(?:icon|apple-touch-icon)" href="([^"]+)"', src)
    assert hrefs and all(h.startswith("/vendor/") for h in hrefs), \
        f"the pages' icon links must be same-origin portal paths, got {hrefs}"


def test_no_web_manifest_was_smuggled_in():
    """The architect's default, pinned so it stays a decision rather than a drift. 192 and 512 exist
    for a future manifest; shipping one would make the portal installable to a home screen, which is
    a product decision the brief has not made. FAILS IF a manifest link appears on any chrome page."""
    for name in CHROME_PAGES:
        text = (ROOT / name).read_text(encoding="utf-8")
        assert 'rel="manifest"' not in text, (
            f"{name}: an installable-PWA manifest is its own decision, not a side effect of the "
            "icon work")
