"""Intake generation of LICENSE.md and README.md into a submitted package.

The gw-runner calls generate_intake_files AFTER safe-extraction and BEFORE the validator runs
(runner._do_work), so a package that arrived without these files carries them by the time the
validator checks structure — the two 'LICENSE.md/README.md missing' WARNINGs flip to PASS in the
SAME run, and the curator reviews/approves the COMPLETE package (approve-what-you-publish).

Design rules (maintainer/C34-IntakeFilesDesign.md), all fail-closed:
  * LICENSE.md is generated ONLY for a licence id the engine RECOGNISES (recognised()); an
    unrecognised id (typo / 'TBD' / free text / absent) generates nothing and the validator WARNING
    correctly stands. The rights text is the engine's single source (_license_text), byte-shared
    with the bundle LICENSE.txt so the two can never drift.
  * README.md is a skeleton from survey.yaml: name, organisation, year/dates, abstract, station
    count (cheap — a count of the package's EDI files), citation guidance, licence line. It carries
    NO submitter contact details of any kind — the runner never sees PII (a job file carries only
    ids + paths, never the DB's submitter fields), and this module reads ONLY survey.yaml, so the
    PII confinement invariant holds by construction.
  * Both files OPEN with a machine stamp naming their provenance and how to replace them.
  * A package that ALREADY carries either file is UNTOUCHED — existing bytes are never overwritten.

STDLIB + PyYAML only (the reader the validator and build_portal use; present on the engine image
where the runner runs). It imports the engine's _license_text leaf for the rights text — a
stdlib-only module, so no heavy scientific stack is pulled into the runner. This module is import-
safe without the engine installed: _license_text is imported LAZILY inside the generator (a bare
`import gateway.runner.intake` in the stack-less gateway test run must not require `extract`).
"""
from __future__ import annotations

from datetime import date, datetime, timezone
from pathlib import Path

LICENSE_FILE = "LICENSE.md"
README_FILE = "README.md"

# Per-field ceiling on any survey.yaml value rendered into a generated file. Generation runs BEFORE
# the validator (see the module docstring), so every value here is still attacker-supplied and the
# write lands in the quarantine volume. Generous against any honest field (an abstract runs to a few
# thousand characters at most) and small enough that a hostile survey.yaml cannot amplify.
_MAX_FIELD_CHARS = 4096
_TRUNCATION_MARKER = " [truncated]"

# The YAML types that may be rendered as text. A list or a map is NOT one: coercing an aliased
# collection to text expands the whole DAG (x10 per alias level for a nested-alias file), turning a
# few hundred bytes of survey.yaml into an unbounded write. Refusing them at the type check keeps the
# expansion from ever happening, and reads as 'no declared metadata' - the module's fail-closed
# posture everywhere else. PyYAML safe_load also yields date/datetime for a bare YYYY-MM-DD. bool is
# NOT here and is excluded explicitly below (it is an int subclass): 'license: yes' declares nothing.
_SCALAR_TYPES = (str, int, float, date, datetime)


def _import_license_text():
    """Resolve the engine's stdlib-only _license_text leaf (the single source) in whichever context the
    runner runs. On the engine image `extract` is an installed package, so `extract._license_text` is
    the resolvable path; a sibling checkout with engine/extract on sys.path resolves the bare name.
    Returns (license_instrument_text, recognised, redistributable, instrument_params_from_survey). Lazy so
    a bare import of this module in the stack-less gateway test run never requires the engine installed."""
    try:
        from extract._license_text import (license_instrument_text, recognised, redistributable,
                                            instrument_params_from_survey)
    except ImportError:  # pragma: no cover - sibling-on-sys.path fallback (engine cwd / dev checkout)
        from _license_text import (license_instrument_text, recognised,  # type: ignore[no-redef]
                                   redistributable, instrument_params_from_survey)
    return license_instrument_text, recognised, redistributable, instrument_params_from_survey


def _stamp(now_utc: datetime) -> str:
    """The machine provenance line both generated files open with, verbatim. The date is
    the UTC calendar date only (no clock time) so the stamp is stable within a day and never leaks a
    sub-day processing timestamp."""
    stamp_date = now_utc.astimezone(timezone.utc).strftime("%Y-%m-%d")
    return (f"Generated by the AusMT gateway from the survey's declared metadata on {stamp_date}. "
            "Replace via a metadata edit or resubmission.")


def _scalar_text(v) -> str:
    """The ONLY route from a survey.yaml value into generated text. Returns '' for a value that is not
    a scalar (see _SCALAR_TYPES) so a collection is never coerced, and caps a scalar at
    _MAX_FIELD_CHARS with a visible marker so a curator is never quietly shown a shortened field.
    Every reader below goes through here: an uncapped str of a survey.yaml value is the defect."""
    if v is None or isinstance(v, bool) or not isinstance(v, _SCALAR_TYPES):
        return ""
    s = str(v).strip()
    if len(s) <= _MAX_FIELD_CHARS:
        return s
    return s[:_MAX_FIELD_CHARS].rstrip() + _TRUNCATION_MARKER


def _org_of(y: dict) -> str:
    """Organisation display name, tolerating both survey.yaml schemas: a nested {name, ror} map
    (Prototype-20) or a bare string (legacy flat schema). Mirrors build_portal._org_of's name pick."""
    org = y.get("organisation")
    if isinstance(org, dict):
        return _scalar_text(org.get("name")) or "the survey custodian"
    return _scalar_text(org) or "the survey custodian"


def _name_of(y: dict) -> str:
    """Survey display name — project_name, else name, else the slug (never empty)."""
    for key in ("project_name", "name", "slug"):
        text = _scalar_text(y.get(key))
        if text:
            return text
    return "AusMT survey"


def _dates_of(y: dict) -> str:
    """'YYYY–YYYY' (or a single year) from a dates {start,end} map, else a bare dates string, else ''.
    Each year goes through _scalar_text so an unquoted YAML int or a null year never raises
    (build_portal._date_range_of) and no collection is expanded."""
    d = y.get("dates")
    if isinstance(d, dict):
        s, e = _scalar_text(d.get("start"))[:4], _scalar_text(d.get("end"))[:4]
        return f"{s}–{e}".strip("–")
    return _scalar_text(d)


def _citation_year_of(y: dict) -> str:
    """4-digit citation year: dates.end, else dates.start, else '' (build_portal._citation_year_of)."""
    d = y.get("dates")
    if not isinstance(d, dict):
        return ""
    return (_scalar_text(d.get("end")) or _scalar_text(d.get("start")))[:4]


def _abstract_of(y: dict) -> str:
    return _scalar_text(y.get("abstract"))


def _license_of(y: dict) -> str:
    """The declared licence id as text. Capped like every other field, and '' for a non-scalar: the
    engine's canon_license calls .strip on what it is given, so a collection here would raise out
    of a module whose contract is to never raise on bad input (generate_intake_files)."""
    return _scalar_text(y.get("license"))


def _station_count(package_root: Path) -> int:
    """A CHEAP station count: the number of one-station transfer-function files under
    transfer_functions/edi/ and transfer_functions/emtfxml/. Not a parse, just a glob, so it is a best-effort figure the README states
    honestly ('N stations') and omits when zero/unknown.

    It deliberately does NOT de-duplicate a station supplied in both formats, and does not count
    MTH5 (one file holds many stations): both would need a parse, which this is not. build_portal's
    real catalogue is authoritative; this is a convenience line."""
    n = 0
    for folder, suffix in (("edi", ".edi"), ("emtfxml", ".xml")):
        d = package_root / "transfer_functions" / folder
        if not d.is_dir():
            continue
        n += sum(1 for p in d.iterdir() if p.is_file() and p.suffix.lower() == suffix)
    return n


def _read_survey_yaml(package_root: Path) -> dict:
    """Read survey.yaml with PyYAML (the reader the validator + build_portal use). A missing or
    unparseable file yields {} — the caller then generates nothing (fail-closed: no metadata, no
    files), never crashes. PyYAML is present on the engine image where the runner runs."""
    path = package_root / "survey.yaml"
    if not path.is_file():
        return {}
    try:
        import yaml  # noqa: PLC0415  (engine image ships PyYAML; lazy so import-time stays light)
    except ModuleNotFoundError:  # pragma: no cover -- engine image always ships PyYAML
        return {}
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except yaml.YAMLError:
        return {}
    return data if isinstance(data, dict) else {}


def _license_md_body(y: dict, now_utc: datetime) -> str | None:
    """The LICENSE.md text, or None when the declared licence is NOT recognised (fail-closed an
    unrecognised id generates nothing so the validator WARNING stands). The rights statement is the
    engine's single-source license_instrument_text so LICENSE.md and the bundle LICENSE.txt
    carry byte-identical rights wording for the same licence id."""
    lic = _license_of(y)
    (license_instrument_text, recognised, redistributable,
     instrument_params_from_survey) = _import_license_text()
    if not recognised(lic):
        return None
    org = _org_of(y)
    year = _citation_year_of(y)
    # Thread the survey's attribution/sources blocks + a changes descriptor so LICENSE.md carries
    # the SAME rights the bundle LICENSE.txt does — both call sites derive them through the shared
    # instrument_params_from_survey helper, so intake and build cannot state divergent attribution.
    # Attribution mirrors the bundle default (custodian + year) when the survey states no explicit
    # attribution.statement (synthesized_attribution=None -> license_instrument_text builds "who (year)").
    # `derived_products` = redistributable(lic): a survey whose bytes AusMT serves gets AusMT-derived
    # renditions (EMTF XML / MTH5), so the CC-BY §3(a) changes clause applies; a recognised-but-metadata-
    # only survey (bytes withheld) gets no changes clause.
    p = instrument_params_from_survey(
        attribution_block=y.get("attribution"), sources_block=y.get("sources"),
        derived_products=redistributable(lic))
    rights = license_instrument_text(lic, org, year, filename="LICENSE.md", **p)
    return f"{_stamp(now_utc)}\n\n{rights}"


def _readme_md_body(y: dict, package_root: Path, now_utc: datetime) -> str:
    """The README.md skeleton: name, organisation, year/dates, abstract, station count
    (when cheaply known), citation guidance, licence line. NO submitter contact details — only
    survey.yaml-declared fields are used."""
    name = _name_of(y)
    org = _org_of(y)
    dates = _dates_of(y)
    year = _citation_year_of(y)
    abstract = _abstract_of(y)
    lic = _license_of(y)
    n_stations = _station_count(package_root)

    lines: list[str] = [
        _stamp(now_utc),
        "",
        f"# {name}",
        "",
        f"- Organisation: {org}",
    ]
    if dates:
        lines.append(f"- Dates: {dates}")
    if n_stations:
        lines.append(f"- Stations: {n_stations}")
    lines.append(f"- Licence: {lic or 'not stated'}")
    lines.append("")
    if abstract:
        lines += ["## Abstract", "", abstract, ""]
    # Citation guidance: honest and generic. Uses only declared fields (org + year + name), no PII.
    cite_year = year or "n.d."
    lines += [
        "## Citation",
        "",
        f"When you use this dataset, please cite it as: {org} ({cite_year}). {name}. "
        + (f"Distributed under {lic}." if lic else "See the accompanying LICENSE.md for terms."),
        "",
    ]
    return "\n".join(lines)


def generate_intake_files(package_root: Path, *, now_utc: datetime | None = None) -> list[str]:
    """Generate LICENSE.md and README.md into `package_root` (the extracted <slug>/ folder) when they
    are ABSENT, rules. Returns the sorted list of filenames actually written (so the
    caller can log/report exactly what was generated).

    Fail-closed and non-destructive:
      * An existing file is NEVER overwritten (its bytes are left byte-identical).
      * LICENSE.md is skipped entirely when the licence is unrecognised (no file, WARNING stands).
      * A missing/unparseable survey.yaml yields NOTHING (no metadata -> no generation).
    The function must never raise on ordinary bad input — the runner treats packaging as best-effort
    and the validator remains the authority; a crash here would wrongly quarantine a valid package.
    """
    now_utc = now_utc or datetime.now(timezone.utc)
    written: list[str] = []
    if not package_root.is_dir():
        return written
    y = _read_survey_yaml(package_root)
    if not y:
        return written  # no declared metadata -> generate nothing (fail-closed)

    license_path = package_root / LICENSE_FILE
    if not license_path.exists():
        body = _license_md_body(y, now_utc)
        if body is not None:
            license_path.write_text(body + "\n", encoding="utf-8")
            written.append(LICENSE_FILE)

    readme_path = package_root / README_FILE
    if not readme_path.exists():
        readme_path.write_text(_readme_md_body(y, package_root, now_utc) + "\n", encoding="utf-8")
        written.append(README_FILE)

    return sorted(written)
