"""C34/D1 — intake generation of LICENSE.md and README.md into a submitted package.

The gw-runner calls generate_intake_files() AFTER safe-extraction and BEFORE the validator runs
(runner._do_work), so a package that arrived without these files carries them by the time the
validator checks structure — the two 'LICENSE.md/README.md missing' WARNINGs flip to PASS in the
SAME run, and the curator reviews/approves the COMPLETE package (approve-what-you-publish).

Design rules (maintainer/C34-IntakeFilesDesign.md D3), all fail-closed:
  * LICENSE.md is generated ONLY for a licence id the engine RECOGNISES (recognised()); an
    unrecognised id (typo / 'TBD' / free text / absent) generates nothing and the validator WARNING
    correctly stands. The rights text is the engine's single source (_license_text), byte-shared
    with the bundle LICENSE.txt so the two can never drift (D2).
  * README.md is a skeleton from survey.yaml: name, organisation, year/dates, abstract, station
    count (cheap — a count of the package's EDI files), citation guidance, licence line. It carries
    NO submitter contact details of any kind — the runner never sees PII (a job file carries only
    ids + paths, never the DB's submitter fields), and this module reads ONLY survey.yaml, so the
    PII confinement invariant holds by construction.
  * Both files OPEN with a machine stamp naming their provenance and how to replace them.
  * A package that ALREADY carries either file is UNTOUCHED — existing bytes are never overwritten.

STDLIB + PyYAML only (the reader the validator and build_portal use; present on the engine image
where the runner runs). It imports the engine's _license_text leaf for the rights text — a
stdlib-only module, so no heavy scientific stack is pulled into the runner. This module is import-
safe without the engine installed: _license_text is imported LAZILY inside the generator (a bare
`import gateway.runner.intake` in the stack-less gateway test lane must not require `extract`).
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

LICENSE_FILE = "LICENSE.md"
README_FILE = "README.md"


def _import_license_text():
    """Resolve the engine's stdlib-only _license_text leaf (D2 single source) in whichever context the
    runner runs. On the engine image `extract` is an installed package, so `extract._license_text` is
    the resolvable path; a sibling checkout with engine/extract on sys.path resolves the bare name.
    Returns (license_instrument_text, recognised, redistributable, instrument_params_from_survey). Lazy so
    a bare import of this module in the stack-less gateway test lane never requires the engine installed."""
    try:
        from extract._license_text import (license_instrument_text, recognised, redistributable,
                                            instrument_params_from_survey)
    except ImportError:  # pragma: no cover - sibling-on-sys.path fallback (engine cwd / dev checkout)
        from _license_text import (license_instrument_text, recognised,  # type: ignore[no-redef]
                                   redistributable, instrument_params_from_survey)
    return license_instrument_text, recognised, redistributable, instrument_params_from_survey


def _stamp(now_utc: datetime) -> str:
    """The machine provenance line both generated files open with (design D3, verbatim). The date is
    the UTC calendar date only (no clock time) so the stamp is stable within a day and never leaks a
    sub-day processing timestamp."""
    date = now_utc.astimezone(timezone.utc).strftime("%Y-%m-%d")
    return (f"Generated by the AusMT gateway from the survey's declared metadata on {date}. "
            "Replace via a metadata edit or resubmission.")


def _org_of(y: dict) -> str:
    """Organisation display name, tolerating both survey.yaml schemas: a nested {name, ror} map
    (Prototype-20) or a bare string (legacy flat schema). Mirrors build_portal._org_of's name pick."""
    org = y.get("organisation")
    if isinstance(org, dict):
        return str(org.get("name") or "").strip() or "the survey custodian"
    return (str(org).strip() if org else "") or "the survey custodian"


def _name_of(y: dict) -> str:
    """Survey display name — project_name, else name, else the slug (never empty)."""
    return (str(y.get("project_name") or y.get("name") or y.get("slug") or "").strip()
            or "AusMT survey")


def _dates_of(y: dict) -> str:
    """'YYYY–YYYY' (or a single year) from a dates {start,end} map, else a bare dates string, else ''.
    str()-coerces each year so an unquoted YAML int or a null year never raises (build_portal._date_range_of)."""
    d = y.get("dates")
    if isinstance(d, dict):
        s, e = str(d.get("start") or "")[:4], str(d.get("end") or "")[:4]
        return f"{s}–{e}".strip("–")
    return str(d).strip() if d else ""


def _citation_year_of(y: dict) -> str:
    """4-digit citation year: dates.end, else dates.start, else '' (build_portal._citation_year_of)."""
    d = y.get("dates")
    if not isinstance(d, dict):
        return ""
    return str(d.get("end") or d.get("start") or "")[:4]


def _abstract_of(y: dict) -> str:
    v = y.get("abstract")
    return str(v).strip() if v else ""


def _station_count(package_root: Path) -> int:
    """A CHEAP station count: the number of .edi files under transfer_functions/edi/. Not a parse —
    just a glob — so it is a best-effort figure the README states honestly ('N stations') and omits
    when zero/unknown. build_portal's real catalogue is authoritative; this is a convenience line."""
    edi_dir = package_root / "transfer_functions" / "edi"
    if not edi_dir.is_dir():
        return 0
    return sum(1 for p in edi_dir.iterdir()
               if p.is_file() and p.suffix.lower() == ".edi")


def _read_survey_yaml(package_root: Path) -> dict:
    """Read survey.yaml with PyYAML (the reader the validator + build_portal use). A missing or
    unparseable file yields {} — the caller then generates nothing (fail-closed: no metadata, no
    files), never crashes. PyYAML is present on the engine image where the runner runs."""
    path = package_root / "survey.yaml"
    if not path.is_file():
        return {}
    try:
        import yaml  # noqa: PLC0415  (engine image ships PyYAML; lazy so import-time stays light)
    except ModuleNotFoundError:  # pragma: no cover -- engine image always ships PyYAML
        return {}
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except yaml.YAMLError:
        return {}
    return data if isinstance(data, dict) else {}


def _license_md_body(y: dict, now_utc: datetime) -> str | None:
    """The LICENSE.md text, or None when the declared licence is NOT recognised (fail-closed D3: an
    unrecognised id generates nothing so the validator WARNING stands). The rights statement is the
    engine's single-source license_instrument_text (D2) so LICENSE.md and the bundle LICENSE.txt
    carry byte-identical rights wording for the same licence id."""
    lic = y.get("license")
    (license_instrument_text, recognised, redistributable,
     instrument_params_from_survey) = _import_license_text()
    if not recognised(lic):
        return None
    org = _org_of(y)
    year = _citation_year_of(y)
    # C46: thread the survey's attribution/sources blocks + a changes descriptor so LICENSE.md carries
    # the SAME rights the bundle LICENSE.txt does — both call sites derive them through the shared
    # instrument_params_from_survey helper, so intake and build cannot state divergent attribution.
    # Attribution mirrors the bundle default (custodian + year) when the survey states no explicit
    # attribution.statement (synthesized_attribution=None -> license_instrument_text builds "who (year)").
    # `derived_products` = redistributable(lic): a survey whose bytes AusMT serves gets AusMT-derived
    # renditions (EMTF XML / MTH5), so the CC-BY §3(a) changes clause applies; a recognised-but-metadata-
    # only survey (bytes withheld) gets no changes clause.
    p = instrument_params_from_survey(
        attribution_block=y.get("attribution"), sources_block=y.get("sources"),
        derived_products=redistributable(lic))
    rights = license_instrument_text(lic, org, year, filename="LICENSE.md", **p)
    return f"{_stamp(now_utc)}\n\n{rights}"


def _readme_md_body(y: dict, package_root: Path, now_utc: datetime) -> str:
    """The README.md skeleton (design D3): name, organisation, year/dates, abstract, station count
    (when cheaply known), citation guidance, licence line. NO submitter contact details — only
    survey.yaml-declared fields are used."""
    name = _name_of(y)
    org = _org_of(y)
    dates = _dates_of(y)
    year = _citation_year_of(y)
    abstract = _abstract_of(y)
    lic = str(y.get("license") or "").strip()
    n_stations = _station_count(package_root)

    lines: list[str] = [
        _stamp(now_utc),
        "",
        f"# {name}",
        "",
        f"- Organisation: {org}",
    ]
    if dates:
        lines.append(f"- Dates: {dates}")
    if n_stations:
        lines.append(f"- Stations: {n_stations}")
    lines.append(f"- Licence: {lic or 'not stated'}")
    lines.append("")
    if abstract:
        lines += ["## Abstract", "", abstract, ""]
    # Citation guidance: honest and generic. Uses only declared fields (org + year + name), no PII.
    cite_year = year or "n.d."
    lines += [
        "## Citation",
        "",
        f"When you use this dataset, please cite it as: {org} ({cite_year}). {name}. "
        + (f"Distributed under {lic}." if lic else "See the accompanying LICENSE.md for terms."),
        "",
    ]
    return "\n".join(lines)


def generate_intake_files(package_root: Path, *, now_utc: datetime | None = None) -> list[str]:
    """Generate LICENSE.md and README.md into `package_root` (the extracted <slug>/ folder) when they
    are ABSENT, per the C34/D3 rules. Returns the sorted list of filenames actually written (so the
    caller can log/report exactly what was generated).

    Fail-closed and non-destructive:
      * An existing file is NEVER overwritten (its bytes are left byte-identical).
      * LICENSE.md is skipped entirely when the licence is unrecognised (no file, WARNING stands).
      * A missing/unparseable survey.yaml yields NOTHING (no metadata -> no generation).
    The function must never raise on ordinary bad input — the runner treats packaging as best-effort
    and the validator remains the authority; a crash here would wrongly quarantine a valid package.
    """
    now_utc = now_utc or datetime.now(timezone.utc)
    written: list[str] = []
    if not package_root.is_dir():
        return written
    y = _read_survey_yaml(package_root)
    if not y:
        return written  # no declared metadata -> generate nothing (fail-closed)

    license_path = package_root / LICENSE_FILE
    if not license_path.exists():
        body = _license_md_body(y, now_utc)
        if body is not None:
            license_path.write_text(body + "\n", encoding="utf-8")
            written.append(LICENSE_FILE)

    readme_path = package_root / README_FILE
    if not readme_path.exists():
        readme_path.write_text(_readme_md_body(y, package_root, now_utc) + "\n", encoding="utf-8")
        written.append(README_FILE)

    return sorted(written)
