# GENERATED by contract/generate.py from contract/columns.json + licenses.json — DO NOT EDIT.
# The authoritative positional column order of catalogue.json / sci.json / tf.json. Read BY
# POSITION across the engine and the portal (see docs/docs/developer/data-files.md). APPEND,
# never reorder. To change: edit contract/columns.json, then `python contract/generate.py`.

CATALOGUE_COLUMNS = ['id', 'survey', 'lat', 'lon', 'period_min_s', 'period_max_s', 'n_periods', 'comps', 'type', 'region', 'file', 'coord_flag', 'ausmt_id', 'edi_available', 'sha256']
SCI_COLUMNS = ['q', 'qb', 'rr', 'sw', 'alg', 'dim', 'p3d', 'gd', 'ellip', 'skew', 'mre', 'decades']
TF_COLUMNS = ['periods', 'rho_xy', 'rho_yx', 'phs_xy', 'phs_yx_adj', 'tip_mag', 'pt_min', 'pt_max', 'pt_az', 'pt_beta']

# C6 licence instrument (single-sourced in contract/licenses.json): the redistribution allow-list
# read by build_portal.redistributable(), plus recognised metadata-only ids, legacy aliases and
# per-id deed URLs. Edit contract/licenses.json, then regenerate — never hand-edit here.
LICENSES = {
    "redistributable": [
        "CC0-1.0",
        "CC-BY-3.0",
        "CC-BY-3.0-AU",
        "CC-BY-4.0",
        "CC-BY-SA-3.0",
        "CC-BY-SA-4.0",
        "CC-BY-NC-4.0",
        "CC-BY-NC-SA-4.0",
        "CC-BY-ND-4.0",
        "CC-BY-NC-ND-4.0",
        "PUBLIC DOMAIN",
        "ODBL-1.0",
        "ODC-BY-1.0"
    ],
    "recognised_only": [
        "CC-BY-NC-3.0",
        "CC-BY-NC-SA-3.0",
        "CC-BY-ND-3.0",
        "CC-BY-NC-ND-3.0",
        "ALL RIGHTS RESERVED",
        "COPYRIGHT"
    ],
    "aliases": {
        "CC0": "CC0-1.0",
        "CC-BY": "CC-BY-4.0",
        "CC-BY-SA": "CC-BY-SA-4.0",
        "CC-BY-NC": "CC-BY-NC-4.0",
        "CC-BY-ND": "CC-BY-ND-4.0",
        "CC-BY-NC-SA": "CC-BY-NC-SA-4.0",
        "CC-BY-NC-ND": "CC-BY-NC-ND-4.0",
        "ODBL": "ODBL-1.0",
        "ODC-BY": "ODC-BY-1.0"
    },
    "urls": {
        "CC0-1.0": "https://creativecommons.org/publicdomain/zero/1.0/",
        "CC-BY-3.0": "https://creativecommons.org/licenses/by/3.0/",
        "CC-BY-3.0-AU": "https://creativecommons.org/licenses/by/3.0/au/",
        "CC-BY-4.0": "https://creativecommons.org/licenses/by/4.0/",
        "CC-BY-SA-3.0": "https://creativecommons.org/licenses/by-sa/3.0/",
        "CC-BY-SA-4.0": "https://creativecommons.org/licenses/by-sa/4.0/",
        "CC-BY-NC-4.0": "https://creativecommons.org/licenses/by-nc/4.0/",
        "CC-BY-NC-SA-4.0": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
        "CC-BY-ND-4.0": "https://creativecommons.org/licenses/by-nd/4.0/",
        "CC-BY-NC-ND-4.0": "https://creativecommons.org/licenses/by-nc-nd/4.0/",
        "PUBLIC DOMAIN": "",
        "ODBL-1.0": "https://opendatacommons.org/licenses/odbl/1-0/",
        "ODC-BY-1.0": "https://opendatacommons.org/licenses/by/1-0/"
    }
}
