# GENERATED by contract/generate.py from contract/columns.json + licenses.json + attribution_profiles.json — DO NOT EDIT.
# The authoritative positional column order of catalogue.json / sci.json / tf.json. Read BY
# POSITION across the engine and the portal (see docs/docs/developer/data-files.md). APPEND,
# never reorder. To change: edit contract/columns.json, then `python contract/generate.py`.

CATALOGUE_COLUMNS = ['id', 'survey', 'lat', 'lon', 'period_min_s', 'period_max_s', 'n_periods', 'comps', 'type', 'region', 'file', 'coord_flag', 'ausmt_id', 'edi_available', 'sha256', 'site_name']
SCI_COLUMNS = ['q', 'qb', 'rr', 'sw', 'alg', 'dim', 'p3d', 'gd', 'ellip', 'skew', 'mre', 'decades']
TF_COLUMNS = ['periods', 'rho_xy', 'rho_yx', 'phs_xy', 'phs_yx_adj', 'tip_mag', 'pt_min', 'pt_max', 'pt_az', 'pt_beta', 'rho_xy_err', 'rho_yx_err', 'phs_xy_err', 'phs_yx_err', 'tzx_re', 'tzx_im', 'tzy_re', 'tzy_im']

# C6 licence instrument (single-sourced in contract/licenses.json): the redistribution allow-list
# read by build_portal.redistributable(), plus recognised metadata-only ids, legacy aliases and
# per-id deed URLs. Edit contract/licenses.json, then regenerate — never hand-edit here.
LICENSES = {
    "redistributable": [
        "CC0-1.0",
        "CC-BY-3.0",
        "CC-BY-3.0-AU",
        "CC-BY-4.0",
        "CC-BY-SA-3.0",
        "CC-BY-SA-4.0",
        "CC-BY-NC-4.0",
        "CC-BY-NC-SA-4.0",
        "CC-BY-ND-4.0",
        "CC-BY-NC-ND-4.0",
        "PUBLIC DOMAIN",
        "ODBL-1.0",
        "ODC-BY-1.0"
    ],
    "recognised_only": [
        "CC-BY-NC-3.0",
        "CC-BY-NC-SA-3.0",
        "CC-BY-ND-3.0",
        "CC-BY-NC-ND-3.0",
        "ALL RIGHTS RESERVED",
        "COPYRIGHT"
    ],
    "aliases": {
        "CC0": "CC0-1.0",
        "CC-BY": "CC-BY-4.0",
        "CC-BY-SA": "CC-BY-SA-4.0",
        "CC-BY-NC": "CC-BY-NC-4.0",
        "CC-BY-ND": "CC-BY-ND-4.0",
        "CC-BY-NC-SA": "CC-BY-NC-SA-4.0",
        "CC-BY-NC-ND": "CC-BY-NC-ND-4.0",
        "ODBL": "ODBL-1.0",
        "ODC-BY": "ODC-BY-1.0"
    },
    "urls": {
        "CC0-1.0": "https://creativecommons.org/publicdomain/zero/1.0/",
        "CC-BY-3.0": "https://creativecommons.org/licenses/by/3.0/",
        "CC-BY-3.0-AU": "https://creativecommons.org/licenses/by/3.0/au/",
        "CC-BY-4.0": "https://creativecommons.org/licenses/by/4.0/",
        "CC-BY-SA-3.0": "https://creativecommons.org/licenses/by-sa/3.0/",
        "CC-BY-SA-4.0": "https://creativecommons.org/licenses/by-sa/4.0/",
        "CC-BY-NC-4.0": "https://creativecommons.org/licenses/by-nc/4.0/",
        "CC-BY-NC-SA-4.0": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
        "CC-BY-ND-4.0": "https://creativecommons.org/licenses/by-nd/4.0/",
        "CC-BY-NC-ND-4.0": "https://creativecommons.org/licenses/by-nc-nd/4.0/",
        "PUBLIC DOMAIN": "",
        "ODBL-1.0": "https://opendatacommons.org/licenses/odbl/1-0/",
        "ODC-BY-1.0": "https://opendatacommons.org/licenses/by/1-0/"
    }
}

# C46 custodian attribution profiles (single-sourced in contract/attribution_profiles.json): the
# per-custodian required-attribution templates rendered by _license_text.license_instrument_text().
# Edit contract/attribution_profiles.json, then regenerate — never hand-edit here.
PROFILES = {
    "generic": {
        "attribution": "{licensor} ({year})"
    },
    "ga": {
        "attribution": "© Commonwealth of Australia (Geoscience Australia) {year}",
        "derivative": "Based on {source_title} by Geoscience Australia ({year}), used under CC-BY 4.0.",
        "disclaimer": "This product incorporates data which is © Commonwealth of Australia (Geoscience Australia). The data has been used with the permission of Geoscience Australia under Creative Commons Attribution 4.0 International Licence. Geoscience Australia has not evaluated the data as altered and incorporated within this product, and gives no warranty regarding its accuracy, completeness, currency or suitability for any particular purpose.",
        "_draft_note": "wording pending owner confirmation against GA's published licensing page (owner decision C46-2, 2026-07-13)"
    }
}
